# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogNutrientPumpCalibrate.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogNutrientPumpCalibrate(object):
    def setupUi(self, dialogNutrientPumpCalibrate):
        dialogNutrientPumpCalibrate.setObjectName("dialogNutrientPumpCalibrate")
        dialogNutrientPumpCalibrate.resize(837, 321)
        font = QtGui.QFont()
        font.setPointSize(10)
        dialogNutrientPumpCalibrate.setFont(font)
        self.frame_2 = QtWidgets.QFrame(dialogNutrientPumpCalibrate)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 831, 321))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(100, 30, 54, 18))
        self.label_4.setObjectName("label_4")
        self.lbl_name_c_1 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_1.setGeometry(QtCore.QRect(5, 61, 85, 18))
        self.lbl_name_c_1.setObjectName("lbl_name_c_1")
        self.le_dur_1 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_1.setGeometry(QtCore.QRect(97, 59, 46, 24))
        self.le_dur_1.setObjectName("le_dur_1")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(147, 62, 51, 18))
        self.label_6.setObjectName("label_6")
        self.pb_run_1 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_1.setGeometry(QtCore.QRect(193, 58, 70, 26))
        self.pb_run_1.setObjectName("pb_run_1")
        self.le_result_1 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_1.setGeometry(QtCore.QRect(270, 59, 33, 24))
        self.le_result_1.setText("")
        self.le_result_1.setObjectName("le_result_1")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(310, 63, 22, 18))
        self.label_7.setObjectName("label_7")
        self.lbl_name_c_2 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_2.setGeometry(QtCore.QRect(5, 93, 85, 18))
        self.lbl_name_c_2.setObjectName("lbl_name_c_2")
        self.le_dur_2 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_2.setGeometry(QtCore.QRect(97, 91, 46, 24))
        self.le_dur_2.setObjectName("le_dur_2")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(147, 94, 45, 18))
        self.label_9.setObjectName("label_9")
        self.pb_run_2 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_2.setGeometry(QtCore.QRect(193, 90, 70, 26))
        self.pb_run_2.setObjectName("pb_run_2")
        self.le_result_2 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_2.setGeometry(QtCore.QRect(270, 91, 33, 24))
        self.le_result_2.setObjectName("le_result_2")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(310, 95, 22, 18))
        self.label_11.setObjectName("label_11")
        self.lbl_name_c_3 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_3.setGeometry(QtCore.QRect(5, 125, 85, 18))
        self.lbl_name_c_3.setObjectName("lbl_name_c_3")
        self.le_dur_3 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_3.setGeometry(QtCore.QRect(97, 123, 46, 24))
        self.le_dur_3.setObjectName("le_dur_3")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(147, 126, 45, 18))
        self.label_12.setObjectName("label_12")
        self.pb_run_3 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_3.setGeometry(QtCore.QRect(193, 122, 70, 26))
        self.pb_run_3.setObjectName("pb_run_3")
        self.le_result_3 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_3.setGeometry(QtCore.QRect(270, 123, 33, 24))
        self.le_result_3.setObjectName("le_result_3")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(310, 127, 22, 18))
        self.label_14.setObjectName("label_14")
        self.lbl_name_c_4 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_4.setGeometry(QtCore.QRect(5, 157, 85, 18))
        self.lbl_name_c_4.setObjectName("lbl_name_c_4")
        self.le_dur_4 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_4.setGeometry(QtCore.QRect(97, 155, 46, 24))
        self.le_dur_4.setObjectName("le_dur_4")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(147, 158, 45, 18))
        self.label_15.setObjectName("label_15")
        self.pb_run_4 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_4.setGeometry(QtCore.QRect(193, 154, 70, 26))
        self.pb_run_4.setObjectName("pb_run_4")
        self.le_result_4 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_4.setGeometry(QtCore.QRect(270, 155, 33, 24))
        self.le_result_4.setObjectName("le_result_4")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(310, 159, 22, 18))
        self.label_17.setObjectName("label_17")
        self.lbl_name_c_6 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_6.setGeometry(QtCore.QRect(5, 220, 85, 18))
        self.lbl_name_c_6.setObjectName("lbl_name_c_6")
        self.le_dur_5 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_5.setGeometry(QtCore.QRect(97, 187, 46, 24))
        self.le_dur_5.setObjectName("le_dur_5")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(147, 190, 45, 18))
        self.label_18.setObjectName("label_18")
        self.pb_run_5 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_5.setGeometry(QtCore.QRect(193, 186, 70, 26))
        self.pb_run_5.setObjectName("pb_run_5")
        self.le_result_5 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_5.setGeometry(QtCore.QRect(270, 187, 33, 24))
        self.le_result_5.setObjectName("le_result_5")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(310, 191, 22, 18))
        self.label_20.setObjectName("label_20")
        self.lbl_name_c_5 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_5.setGeometry(QtCore.QRect(5, 189, 85, 18))
        self.lbl_name_c_5.setObjectName("lbl_name_c_5")
        self.le_dur_6 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_6.setGeometry(QtCore.QRect(97, 219, 46, 24))
        self.le_dur_6.setObjectName("le_dur_6")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(147, 222, 45, 18))
        self.label_21.setObjectName("label_21")
        self.pb_run_6 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_6.setGeometry(QtCore.QRect(193, 218, 70, 26))
        self.pb_run_6.setObjectName("pb_run_6")
        self.le_result_6 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_6.setGeometry(QtCore.QRect(270, 219, 33, 24))
        self.le_result_6.setObjectName("le_result_6")
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setGeometry(QtCore.QRect(310, 223, 22, 18))
        self.label_23.setObjectName("label_23")
        self.lbl_name_c_7 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_7.setGeometry(QtCore.QRect(5, 250, 85, 18))
        self.lbl_name_c_7.setObjectName("lbl_name_c_7")
        self.le_dur_7 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_7.setGeometry(QtCore.QRect(97, 251, 46, 24))
        self.le_dur_7.setObjectName("le_dur_7")
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        self.label_24.setGeometry(QtCore.QRect(147, 254, 45, 18))
        self.label_24.setObjectName("label_24")
        self.pb_run_7 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_7.setGeometry(QtCore.QRect(193, 250, 70, 26))
        self.pb_run_7.setObjectName("pb_run_7")
        self.le_result_7 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_7.setGeometry(QtCore.QRect(270, 251, 33, 24))
        self.le_result_7.setObjectName("le_result_7")
        self.label_26 = QtWidgets.QLabel(self.frame_2)
        self.label_26.setGeometry(QtCore.QRect(310, 255, 22, 18))
        self.label_26.setObjectName("label_26")
        self.lbl_name_c_8 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_8.setGeometry(QtCore.QRect(5, 282, 85, 18))
        self.lbl_name_c_8.setObjectName("lbl_name_c_8")
        self.le_dur_8 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_8.setGeometry(QtCore.QRect(97, 283, 46, 24))
        self.le_dur_8.setObjectName("le_dur_8")
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        self.label_27.setGeometry(QtCore.QRect(147, 286, 45, 18))
        self.label_27.setObjectName("label_27")
        self.pb_run_8 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_8.setGeometry(QtCore.QRect(193, 282, 70, 26))
        self.pb_run_8.setObjectName("pb_run_8")
        self.le_result_8 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_8.setGeometry(QtCore.QRect(270, 283, 33, 24))
        self.le_result_8.setObjectName("le_result_8")
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        self.label_29.setGeometry(QtCore.QRect(310, 287, 22, 18))
        self.label_29.setObjectName("label_29")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(270, 34, 39, 18))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 181, 18))
        self.label_3.setObjectName("label_3")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(510, 30, 39, 18))
        self.label_22.setObjectName("label_22")
        self.le_test_1 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_1.setGeometry(QtCore.QRect(410, 61, 31, 24))
        self.le_test_1.setObjectName("le_test_1")
        self.label_25 = QtWidgets.QLabel(self.frame_2)
        self.label_25.setGeometry(QtCore.QRect(445, 63, 22, 18))
        self.label_25.setObjectName("label_25")
        self.pb_dispense_1 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_1.setGeometry(QtCore.QRect(552, 60, 70, 26))
        self.pb_dispense_1.setObjectName("pb_dispense_1")
        self.lbl_current_1 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_1.setGeometry(QtCore.QRect(630, 64, 190, 18))
        self.lbl_current_1.setText("")
        self.lbl_current_1.setObjectName("lbl_current_1")
        self.pb_dispense_2 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_2.setGeometry(QtCore.QRect(550, 91, 70, 26))
        self.pb_dispense_2.setObjectName("pb_dispense_2")
        self.lbl_current_2 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_2.setGeometry(QtCore.QRect(628, 95, 190, 18))
        self.lbl_current_2.setText("")
        self.lbl_current_2.setObjectName("lbl_current_2")
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        self.label_28.setGeometry(QtCore.QRect(443, 94, 22, 18))
        self.label_28.setObjectName("label_28")
        self.le_test_2 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_2.setGeometry(QtCore.QRect(409, 92, 31, 24))
        self.le_test_2.setObjectName("le_test_2")
        self.pb_dispense_3 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_3.setGeometry(QtCore.QRect(550, 122, 70, 26))
        self.pb_dispense_3.setObjectName("pb_dispense_3")
        self.lbl_current_3 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_3.setGeometry(QtCore.QRect(628, 126, 190, 18))
        self.lbl_current_3.setText("")
        self.lbl_current_3.setObjectName("lbl_current_3")
        self.label_30 = QtWidgets.QLabel(self.frame_2)
        self.label_30.setGeometry(QtCore.QRect(443, 125, 22, 18))
        self.label_30.setObjectName("label_30")
        self.le_test_3 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_3.setGeometry(QtCore.QRect(409, 123, 31, 24))
        self.le_test_3.setObjectName("le_test_3")
        self.pb_dispense_4 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_4.setGeometry(QtCore.QRect(550, 154, 70, 26))
        self.pb_dispense_4.setObjectName("pb_dispense_4")
        self.lbl_current_4 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_4.setGeometry(QtCore.QRect(628, 158, 190, 18))
        self.lbl_current_4.setText("")
        self.lbl_current_4.setObjectName("lbl_current_4")
        self.label_31 = QtWidgets.QLabel(self.frame_2)
        self.label_31.setGeometry(QtCore.QRect(443, 157, 22, 18))
        self.label_31.setObjectName("label_31")
        self.le_test_4 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_4.setGeometry(QtCore.QRect(409, 155, 31, 24))
        self.le_test_4.setObjectName("le_test_4")
        self.pb_dispense_5 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_5.setGeometry(QtCore.QRect(550, 186, 70, 26))
        self.pb_dispense_5.setObjectName("pb_dispense_5")
        self.lbl_current_5 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_5.setGeometry(QtCore.QRect(628, 190, 190, 18))
        self.lbl_current_5.setText("")
        self.lbl_current_5.setObjectName("lbl_current_5")
        self.label_32 = QtWidgets.QLabel(self.frame_2)
        self.label_32.setGeometry(QtCore.QRect(443, 189, 22, 18))
        self.label_32.setObjectName("label_32")
        self.le_test_5 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_5.setGeometry(QtCore.QRect(409, 187, 31, 24))
        self.le_test_5.setObjectName("le_test_5")
        self.pb_dispense_6 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_6.setGeometry(QtCore.QRect(550, 219, 70, 26))
        self.pb_dispense_6.setObjectName("pb_dispense_6")
        self.lbl_current_6 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_6.setGeometry(QtCore.QRect(628, 223, 190, 18))
        self.lbl_current_6.setText("")
        self.lbl_current_6.setObjectName("lbl_current_6")
        self.label_33 = QtWidgets.QLabel(self.frame_2)
        self.label_33.setGeometry(QtCore.QRect(443, 222, 22, 18))
        self.label_33.setObjectName("label_33")
        self.le_test_6 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_6.setGeometry(QtCore.QRect(409, 220, 31, 24))
        self.le_test_6.setObjectName("le_test_6")
        self.pb_dispense_7 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_7.setGeometry(QtCore.QRect(550, 250, 70, 26))
        self.pb_dispense_7.setObjectName("pb_dispense_7")
        self.lbl_current_7 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_7.setGeometry(QtCore.QRect(628, 254, 190, 18))
        self.lbl_current_7.setText("")
        self.lbl_current_7.setObjectName("lbl_current_7")
        self.label_34 = QtWidgets.QLabel(self.frame_2)
        self.label_34.setGeometry(QtCore.QRect(443, 253, 22, 18))
        self.label_34.setObjectName("label_34")
        self.le_test_7 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_7.setGeometry(QtCore.QRect(409, 251, 31, 24))
        self.le_test_7.setObjectName("le_test_7")
        self.pb_dispense_8 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_8.setGeometry(QtCore.QRect(550, 282, 70, 26))
        self.pb_dispense_8.setObjectName("pb_dispense_8")
        self.lbl_current_8 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_8.setGeometry(QtCore.QRect(628, 286, 190, 18))
        self.lbl_current_8.setText("")
        self.lbl_current_8.setObjectName("lbl_current_8")
        self.label_35 = QtWidgets.QLabel(self.frame_2)
        self.label_35.setGeometry(QtCore.QRect(443, 285, 22, 18))
        self.label_35.setObjectName("label_35")
        self.le_test_8 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_8.setGeometry(QtCore.QRect(409, 283, 31, 24))
        self.le_test_8.setObjectName("le_test_8")
        self.pb_save_1 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_1.setGeometry(QtCore.QRect(340, 60, 61, 26))
        self.pb_save_1.setObjectName("pb_save_1")
        self.pb_save_3 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_3.setGeometry(QtCore.QRect(340, 120, 61, 26))
        self.pb_save_3.setObjectName("pb_save_3")
        self.pb_save_4 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_4.setGeometry(QtCore.QRect(340, 150, 61, 26))
        self.pb_save_4.setObjectName("pb_save_4")
        self.pb_save_5 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_5.setGeometry(QtCore.QRect(340, 186, 61, 26))
        self.pb_save_5.setObjectName("pb_save_5")
        self.pb_save_6 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_6.setGeometry(QtCore.QRect(340, 220, 61, 26))
        self.pb_save_6.setObjectName("pb_save_6")
        self.pb_save_7 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_7.setGeometry(QtCore.QRect(340, 250, 61, 26))
        self.pb_save_7.setObjectName("pb_save_7")
        self.pb_save_8 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_8.setGeometry(QtCore.QRect(340, 280, 61, 26))
        self.pb_save_8.setObjectName("pb_save_8")
        self.pb_save_2 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_2.setGeometry(QtCore.QRect(340, 90, 61, 26))
        self.pb_save_2.setObjectName("pb_save_2")
        self.lbl_running = QtWidgets.QLabel(self.frame_2)
        self.lbl_running.setGeometry(QtCore.QRect(410, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_running.setFont(font)
        self.lbl_running.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.lbl_running.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_running.setObjectName("lbl_running")
        self.label_36 = QtWidgets.QLabel(self.frame_2)
        self.label_36.setGeometry(QtCore.QRect(520, 62, 31, 18))
        self.label_36.setObjectName("label_36")
        self.le_seconds_1 = QtWidgets.QLineEdit(self.frame_2)
        self.le_seconds_1.setEnabled(False)
        self.le_seconds_1.setGeometry(QtCore.QRect(474, 61, 40, 24))
        self.le_seconds_1.setMouseTracking(False)
        self.le_seconds_1.setReadOnly(True)
        self.le_seconds_1.setObjectName("le_seconds_1")
        self.label_37 = QtWidgets.QLabel(self.frame_2)
        self.label_37.setGeometry(QtCore.QRect(520, 92, 31, 18))
        self.label_37.setObjectName("label_37")
        self.le_seconds_2 = QtWidgets.QLineEdit(self.frame_2)
        self.le_seconds_2.setEnabled(False)
        self.le_seconds_2.setGeometry(QtCore.QRect(474, 91, 40, 24))
        self.le_seconds_2.setMouseTracking(False)
        self.le_seconds_2.setReadOnly(True)
        self.le_seconds_2.setObjectName("le_seconds_2")
        self.label_38 = QtWidgets.QLabel(self.frame_2)
        self.label_38.setGeometry(QtCore.QRect(520, 124, 31, 18))
        self.label_38.setObjectName("label_38")
        self.le_seconds_3 = QtWidgets.QLineEdit(self.frame_2)
        self.le_seconds_3.setEnabled(False)
        self.le_seconds_3.setGeometry(QtCore.QRect(474, 123, 40, 24))
        self.le_seconds_3.setMouseTracking(False)
        self.le_seconds_3.setReadOnly(True)
        self.le_seconds_3.setObjectName("le_seconds_3")
        self.label_39 = QtWidgets.QLabel(self.frame_2)
        self.label_39.setGeometry(QtCore.QRect(520, 156, 31, 18))
        self.label_39.setObjectName("label_39")
        self.le_seconds_4 = QtWidgets.QLineEdit(self.frame_2)
        self.le_seconds_4.setEnabled(False)
        self.le_seconds_4.setGeometry(QtCore.QRect(474, 155, 40, 24))
        self.le_seconds_4.setMouseTracking(False)
        self.le_seconds_4.setReadOnly(True)
        self.le_seconds_4.setObjectName("le_seconds_4")
        self.label_40 = QtWidgets.QLabel(self.frame_2)
        self.label_40.setGeometry(QtCore.QRect(520, 188, 31, 18))
        self.label_40.setObjectName("label_40")
        self.le_seconds_5 = QtWidgets.QLineEdit(self.frame_2)
        self.le_seconds_5.setEnabled(False)
        self.le_seconds_5.setGeometry(QtCore.QRect(474, 187, 40, 24))
        self.le_seconds_5.setMouseTracking(False)
        self.le_seconds_5.setReadOnly(True)
        self.le_seconds_5.setObjectName("le_seconds_5")
        self.label_41 = QtWidgets.QLabel(self.frame_2)
        self.label_41.setGeometry(QtCore.QRect(520, 221, 31, 18))
        self.label_41.setObjectName("label_41")
        self.le_seconds_6 = QtWidgets.QLineEdit(self.frame_2)
        self.le_seconds_6.setEnabled(False)
        self.le_seconds_6.setGeometry(QtCore.QRect(474, 220, 40, 24))
        self.le_seconds_6.setMouseTracking(False)
        self.le_seconds_6.setReadOnly(True)
        self.le_seconds_6.setObjectName("le_seconds_6")
        self.label_42 = QtWidgets.QLabel(self.frame_2)
        self.label_42.setGeometry(QtCore.QRect(520, 251, 31, 18))
        self.label_42.setObjectName("label_42")
        self.le_seconds_7 = QtWidgets.QLineEdit(self.frame_2)
        self.le_seconds_7.setEnabled(False)
        self.le_seconds_7.setGeometry(QtCore.QRect(474, 250, 40, 24))
        self.le_seconds_7.setMouseTracking(False)
        self.le_seconds_7.setReadOnly(True)
        self.le_seconds_7.setObjectName("le_seconds_7")
        self.label_43 = QtWidgets.QLabel(self.frame_2)
        self.label_43.setGeometry(QtCore.QRect(520, 281, 31, 18))
        self.label_43.setObjectName("label_43")
        self.le_seconds_8 = QtWidgets.QLineEdit(self.frame_2)
        self.le_seconds_8.setEnabled(False)
        self.le_seconds_8.setGeometry(QtCore.QRect(474, 280, 40, 24))
        self.le_seconds_8.setMouseTracking(False)
        self.le_seconds_8.setReadOnly(True)
        self.le_seconds_8.setObjectName("le_seconds_8")
        self.pb_stop = QtWidgets.QPushButton(self.frame_2)
        self.pb_stop.setGeometry(QtCore.QRect(580, 10, 81, 41))
        self.pb_stop.setObjectName("pb_stop")
        self.pb_close = QtWidgets.QPushButton(self.frame_2)
        self.pb_close.setGeometry(QtCore.QRect(750, 10, 75, 23))
        self.pb_close.setObjectName("pb_close")

        self.retranslateUi(dialogNutrientPumpCalibrate)
        QtCore.QMetaObject.connectSlotsByName(dialogNutrientPumpCalibrate)

    def retranslateUi(self, dialogNutrientPumpCalibrate):
        _translate = QtCore.QCoreApplication.translate
        dialogNutrientPumpCalibrate.setWindowTitle(_translate("dialogNutrientPumpCalibrate", "Nutrient Pump Calibration"))
        self.label_4.setText(_translate("dialogNutrientPumpCalibrate", "Duration"))
        self.lbl_name_c_1.setText(_translate("dialogNutrientPumpCalibrate", "TextLabel"))
        self.le_dur_1.setText(_translate("dialogNutrientPumpCalibrate", "10000"))
        self.label_6.setText(_translate("dialogNutrientPumpCalibrate", "mSecs"))
        self.pb_run_1.setText(_translate("dialogNutrientPumpCalibrate", "Run"))
        self.label_7.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.lbl_name_c_2.setText(_translate("dialogNutrientPumpCalibrate", "TextLabel"))
        self.le_dur_2.setText(_translate("dialogNutrientPumpCalibrate", "10000"))
        self.label_9.setText(_translate("dialogNutrientPumpCalibrate", "mSecs"))
        self.pb_run_2.setText(_translate("dialogNutrientPumpCalibrate", "Run"))
        self.label_11.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.lbl_name_c_3.setText(_translate("dialogNutrientPumpCalibrate", "TextLabel"))
        self.le_dur_3.setText(_translate("dialogNutrientPumpCalibrate", "10000"))
        self.label_12.setText(_translate("dialogNutrientPumpCalibrate", "mSecs"))
        self.pb_run_3.setText(_translate("dialogNutrientPumpCalibrate", "Run"))
        self.label_14.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.lbl_name_c_4.setText(_translate("dialogNutrientPumpCalibrate", "TextLabel"))
        self.le_dur_4.setText(_translate("dialogNutrientPumpCalibrate", "10000"))
        self.label_15.setText(_translate("dialogNutrientPumpCalibrate", "mSecs"))
        self.pb_run_4.setText(_translate("dialogNutrientPumpCalibrate", "Run"))
        self.label_17.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.lbl_name_c_6.setText(_translate("dialogNutrientPumpCalibrate", "TextLabel"))
        self.le_dur_5.setText(_translate("dialogNutrientPumpCalibrate", "10000"))
        self.label_18.setText(_translate("dialogNutrientPumpCalibrate", "mSecs"))
        self.pb_run_5.setText(_translate("dialogNutrientPumpCalibrate", "Run"))
        self.label_20.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.lbl_name_c_5.setText(_translate("dialogNutrientPumpCalibrate", "TextLabel"))
        self.le_dur_6.setText(_translate("dialogNutrientPumpCalibrate", "10000"))
        self.label_21.setText(_translate("dialogNutrientPumpCalibrate", "mSecs"))
        self.pb_run_6.setText(_translate("dialogNutrientPumpCalibrate", "Run"))
        self.label_23.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.lbl_name_c_7.setText(_translate("dialogNutrientPumpCalibrate", "TextLabel"))
        self.le_dur_7.setText(_translate("dialogNutrientPumpCalibrate", "10000"))
        self.label_24.setText(_translate("dialogNutrientPumpCalibrate", "mSecs"))
        self.pb_run_7.setText(_translate("dialogNutrientPumpCalibrate", "Run"))
        self.label_26.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.lbl_name_c_8.setText(_translate("dialogNutrientPumpCalibrate", "TextLabel"))
        self.le_dur_8.setText(_translate("dialogNutrientPumpCalibrate", "10000"))
        self.label_27.setText(_translate("dialogNutrientPumpCalibrate", "mSecs"))
        self.pb_run_8.setText(_translate("dialogNutrientPumpCalibrate", "Run"))
        self.label_29.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.label_5.setText(_translate("dialogNutrientPumpCalibrate", "Result"))
        self.label_3.setText(_translate("dialogNutrientPumpCalibrate", "Nutrient Pump Calibration"))
        self.label_22.setText(_translate("dialogNutrientPumpCalibrate", "Test"))
        self.le_test_1.setText(_translate("dialogNutrientPumpCalibrate", "88"))
        self.label_25.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.pb_dispense_1.setText(_translate("dialogNutrientPumpCalibrate", "Dispense"))
        self.pb_dispense_2.setText(_translate("dialogNutrientPumpCalibrate", "Dispense"))
        self.label_28.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.pb_dispense_3.setText(_translate("dialogNutrientPumpCalibrate", "Dispense"))
        self.label_30.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.pb_dispense_4.setText(_translate("dialogNutrientPumpCalibrate", "Dispense"))
        self.label_31.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.pb_dispense_5.setText(_translate("dialogNutrientPumpCalibrate", "Dispense"))
        self.label_32.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.pb_dispense_6.setText(_translate("dialogNutrientPumpCalibrate", "Dispense"))
        self.label_33.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.pb_dispense_7.setText(_translate("dialogNutrientPumpCalibrate", "Dispense"))
        self.label_34.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.pb_dispense_8.setText(_translate("dialogNutrientPumpCalibrate", "Dispense"))
        self.label_35.setText(_translate("dialogNutrientPumpCalibrate", "mls"))
        self.pb_save_1.setText(_translate("dialogNutrientPumpCalibrate", "Save"))
        self.pb_save_3.setText(_translate("dialogNutrientPumpCalibrate", "Save"))
        self.pb_save_4.setText(_translate("dialogNutrientPumpCalibrate", "Save"))
        self.pb_save_5.setText(_translate("dialogNutrientPumpCalibrate", "Save"))
        self.pb_save_6.setText(_translate("dialogNutrientPumpCalibrate", "Save"))
        self.pb_save_7.setText(_translate("dialogNutrientPumpCalibrate", "Save"))
        self.pb_save_8.setText(_translate("dialogNutrientPumpCalibrate", "Save"))
        self.pb_save_2.setText(_translate("dialogNutrientPumpCalibrate", "Save"))
        self.lbl_running.setText(_translate("dialogNutrientPumpCalibrate", "Running"))
        self.label_36.setText(_translate("dialogNutrientPumpCalibrate", "secs"))
        self.label_37.setText(_translate("dialogNutrientPumpCalibrate", "secs"))
        self.label_38.setText(_translate("dialogNutrientPumpCalibrate", "secs"))
        self.label_39.setText(_translate("dialogNutrientPumpCalibrate", "secs"))
        self.label_40.setText(_translate("dialogNutrientPumpCalibrate", "secs"))
        self.label_41.setText(_translate("dialogNutrientPumpCalibrate", "secs"))
        self.label_42.setText(_translate("dialogNutrientPumpCalibrate", "secs"))
        self.label_43.setText(_translate("dialogNutrientPumpCalibrate", "secs"))
        self.pb_stop.setText(_translate("dialogNutrientPumpCalibrate", "Stop"))
        self.pb_close.setText(_translate("dialogNutrientPumpCalibrate", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialogNutrientPumpCalibrate = QtWidgets.QDialog()
    ui = Ui_dialogNutrientPumpCalibrate()
    ui.setupUi(dialogNutrientPumpCalibrate)
    dialogNutrientPumpCalibrate.show()
    sys.exit(app.exec_())

