# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogSettingsAll.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogSettingsAll(object):
    def setupUi(self, dialogSettingsAll):
        dialogSettingsAll.setObjectName("dialogSettingsAll")
        dialogSettingsAll.resize(944, 793)
        self.toolBox = QtWidgets.QToolBox(dialogSettingsAll)
        self.toolBox.setGeometry(QtCore.QRect(10, 10, 921, 771))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.toolBox.setFont(font)
        self.toolBox.setObjectName("toolBox")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_9)
        self.groupBox_3.setGeometry(QtCore.QRect(150, 10, 261, 181))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.label_22.setObjectName("label_22")
        self.pb_db_open = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_db_open.setGeometry(QtCore.QRect(150, 150, 75, 23))
        self.pb_db_open.setObjectName("pb_db_open")
        self.le_db_host = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_db_host.setGeometry(QtCore.QRect(100, 30, 141, 20))
        self.le_db_host.setObjectName("le_db_host")
        self.le_db_user_name = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_db_user_name.setGeometry(QtCore.QRect(100, 60, 141, 20))
        self.le_db_user_name.setObjectName("le_db_user_name")
        self.le_db_password = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_db_password.setGeometry(QtCore.QRect(100, 90, 141, 20))
        self.le_db_password.setObjectName("le_db_password")
        self.le_db_name = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_db_name.setGeometry(QtCore.QRect(100, 120, 141, 20))
        self.le_db_name.setObjectName("le_db_name")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(20, 120, 81, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(20, 60, 81, 16))
        self.label_25.setObjectName("label_25")
        self.pb_back_up = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_back_up.setGeometry(QtCore.QRect(20, 150, 75, 25))
        self.pb_back_up.setAutoDefault(False)
        self.pb_back_up.setObjectName("pb_back_up")
        self.groupBox = QtWidgets.QGroupBox(self.page_9)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 131, 61))
        self.groupBox.setObjectName("groupBox")
        self.cb_system_mode = QtWidgets.QComboBox(self.groupBox)
        self.cb_system_mode.setGeometry(QtCore.QRect(10, 30, 111, 22))
        self.cb_system_mode.setObjectName("cb_system_mode")
        self.toolBox.addItem(self.page_9, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 921, 355))
        self.page.setObjectName("page")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 921, 355))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_14)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 301, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.te_ports = QtWidgets.QTextEdit(self.groupBox_2)
        self.te_ports.setGeometry(QtCore.QRect(10, 20, 281, 121))
        self.te_ports.setObjectName("te_ports")
        self.pb_rescan_ports = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_rescan_ports.setGeometry(QtCore.QRect(120, 150, 75, 23))
        self.pb_rescan_ports.setObjectName("pb_rescan_ports")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_14)
        self.groupBox_4.setGeometry(QtCore.QRect(310, 10, 120, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pb_ss_update = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_ss_update.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.pb_ss_update.setObjectName("pb_ss_update")
        self.le_ss_port = QtWidgets.QLineEdit(self.groupBox_4)
        self.le_ss_port.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.le_ss_port.setObjectName("le_ss_port")
        self.toolBox.addItem(self.page_14, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 0, 251, 231))
        self.groupBox_5.setObjectName("groupBox_5")
        self.le_kd_1 = QtWidgets.QLineEdit(self.groupBox_5)
        self.le_kd_1.setGeometry(QtCore.QRect(50, 90, 51, 20))
        self.le_kd_1.setObjectName("le_kd_1")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(20, 60, 31, 21))
        self.label_17.setObjectName("label_17")
        self.le_kp_1 = QtWidgets.QLineEdit(self.groupBox_5)
        self.le_kp_1.setGeometry(QtCore.QRect(50, 30, 51, 20))
        self.le_kp_1.setObjectName("le_kp_1")
        self.le_ki_1 = QtWidgets.QLineEdit(self.groupBox_5)
        self.le_ki_1.setGeometry(QtCore.QRect(50, 60, 51, 20))
        self.le_ki_1.setObjectName("le_ki_1")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(20, 90, 31, 21))
        self.label_18.setObjectName("label_18")
        self.pb_reset_fan_1 = QtWidgets.QPushButton(self.groupBox_5)
        self.pb_reset_fan_1.setGeometry(QtCore.QRect(20, 160, 61, 23))
        self.pb_reset_fan_1.setObjectName("pb_reset_fan_1")
        self.pb_save_fans_1 = QtWidgets.QPushButton(self.groupBox_5)
        self.pb_save_fans_1.setGeometry(QtCore.QRect(20, 190, 61, 23))
        self.pb_save_fans_1.setObjectName("pb_save_fans_1")
        self.ck_test = QtWidgets.QCheckBox(self.groupBox_5)
        self.ck_test.setGeometry(QtCore.QRect(170, 200, 61, 21))
        self.ck_test.setObjectName("ck_test")
        self.pb_show_log_1 = QtWidgets.QPushButton(self.groupBox_5)
        self.pb_show_log_1.setGeometry(QtCore.QRect(160, 160, 75, 31))
        self.pb_show_log_1.setObjectName("pb_show_log_1")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_6.setGeometry(QtCore.QRect(270, 0, 251, 231))
        self.groupBox_6.setObjectName("groupBox_6")
        self.le_kd_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.le_kd_2.setGeometry(QtCore.QRect(50, 90, 51, 20))
        self.le_kd_2.setObjectName("le_kd_2")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(20, 60, 31, 21))
        self.label_20.setObjectName("label_20")
        self.le_kp_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.le_kp_2.setGeometry(QtCore.QRect(50, 30, 51, 20))
        self.le_kp_2.setObjectName("le_kp_2")
        self.le_ki_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.le_ki_2.setGeometry(QtCore.QRect(50, 60, 51, 20))
        self.le_ki_2.setObjectName("le_ki_2")
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(20, 90, 31, 21))
        self.label_21.setObjectName("label_21")
        self.pb_reset_fan_2 = QtWidgets.QPushButton(self.groupBox_6)
        self.pb_reset_fan_2.setGeometry(QtCore.QRect(20, 160, 61, 23))
        self.pb_reset_fan_2.setObjectName("pb_reset_fan_2")
        self.pb_save_fans_2 = QtWidgets.QPushButton(self.groupBox_6)
        self.pb_save_fans_2.setGeometry(QtCore.QRect(20, 190, 61, 23))
        self.pb_save_fans_2.setObjectName("pb_save_fans_2")
        self.ck_test_2 = QtWidgets.QCheckBox(self.groupBox_6)
        self.ck_test_2.setGeometry(QtCore.QRect(170, 200, 61, 21))
        self.ck_test_2.setObjectName("ck_test_2")
        self.pb_show_log_2 = QtWidgets.QPushButton(self.groupBox_6)
        self.pb_show_log_2.setGeometry(QtCore.QRect(160, 160, 75, 31))
        self.pb_show_log_2.setObjectName("pb_show_log_2")
        self.toolBox.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.toolBox.addItem(self.page_6, "")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.toolBox.addItem(self.page_7, "")
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.toolBox.addItem(self.page_13, "")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.toolBox.addItem(self.page_8, "")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.toolBox.addItem(self.page_10, "")
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.toolBox.addItem(self.page_11, "")
        self.pb_close = QtWidgets.QPushButton(dialogSettingsAll)
        self.pb_close.setGeometry(QtCore.QRect(860, 10, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pb_close.setFont(font)
        self.pb_close.setAutoDefault(False)
        self.pb_close.setObjectName("pb_close")

        self.retranslateUi(dialogSettingsAll)
        self.toolBox.setCurrentIndex(4)
        self.toolBox.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(dialogSettingsAll)

    def retranslateUi(self, dialogSettingsAll):
        _translate = QtCore.QCoreApplication.translate
        dialogSettingsAll.setWindowTitle(_translate("dialogSettingsAll", "Settings"))
        self.groupBox_3.setTitle(_translate("dialogSettingsAll", "Database"))
        self.label_22.setText(_translate("dialogSettingsAll", "Host"))
        self.pb_db_open.setText(_translate("dialogSettingsAll", "Save"))
        self.label_23.setText(_translate("dialogSettingsAll", "Password"))
        self.label_24.setText(_translate("dialogSettingsAll", "DB Name"))
        self.label_25.setText(_translate("dialogSettingsAll", "User Name"))
        self.pb_back_up.setText(_translate("dialogSettingsAll", "Back Up"))
        self.groupBox.setTitle(_translate("dialogSettingsAll", "Operation Mode"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_9), _translate("dialogSettingsAll", "General"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("dialogSettingsAll", "Access"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("dialogSettingsAll", "Areas"))
        self.groupBox_2.setTitle(_translate("dialogSettingsAll", "Ports"))
        self.pb_rescan_ports.setText(_translate("dialogSettingsAll", "Rescan"))
        self.groupBox_4.setTitle(_translate("dialogSettingsAll", "Scales Unit Port"))
        self.pb_ss_update.setText(_translate("dialogSettingsAll", "Update"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_14), _translate("dialogSettingsAll", "Com Ports"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("dialogSettingsAll", "Dispatch"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("dialogSettingsAll", "Drying Area"))
        self.groupBox_5.setTitle(_translate("dialogSettingsAll", "Fan 1"))
        self.label_16.setText(_translate("dialogSettingsAll", "Kp"))
        self.label_17.setText(_translate("dialogSettingsAll", "Ki"))
        self.label_18.setText(_translate("dialogSettingsAll", "Kd"))
        self.pb_reset_fan_1.setText(_translate("dialogSettingsAll", "Reset"))
        self.pb_save_fans_1.setText(_translate("dialogSettingsAll", "Save"))
        self.ck_test.setText(_translate("dialogSettingsAll", "Log"))
        self.pb_show_log_1.setText(_translate("dialogSettingsAll", "Show Log"))
        self.groupBox_6.setTitle(_translate("dialogSettingsAll", "Fan 2"))
        self.label_19.setText(_translate("dialogSettingsAll", "Kp"))
        self.label_20.setText(_translate("dialogSettingsAll", "Ki"))
        self.label_21.setText(_translate("dialogSettingsAll", "Kd"))
        self.pb_reset_fan_2.setText(_translate("dialogSettingsAll", "Reset"))
        self.pb_save_fans_2.setText(_translate("dialogSettingsAll", "Save"))
        self.ck_test_2.setText(_translate("dialogSettingsAll", "Log"))
        self.pb_show_log_2.setText(_translate("dialogSettingsAll", "Show Log"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("dialogSettingsAll", "Fans"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("dialogSettingsAll", "Feeder Unit"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("dialogSettingsAll", "Logs"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_13), _translate("dialogSettingsAll", "Outputs"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_8), _translate("dialogSettingsAll", "Network"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_10), _translate("dialogSettingsAll", "Soil Sensors"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_11), _translate("dialogSettingsAll", "Water"))
        self.pb_close.setText(_translate("dialogSettingsAll", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialogSettingsAll = QtWidgets.QWidget()
    ui = Ui_dialogSettingsAll()
    ui.setupUi(dialogSettingsAll)
    dialogSettingsAll.show()
    sys.exit(app.exec_())

