# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogPatterns.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogPatterns(object):
    def setupUi(self, DialogPatterns):
        DialogPatterns.setObjectName("DialogPatterns")
        DialogPatterns.resize(451, 453)
        font = QtGui.QFont()
        font.setPointSize(10)
        DialogPatterns.setFont(font)
        self.label = QtWidgets.QLabel(DialogPatterns)
        self.label.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label.setObjectName("label")
        self.cb_patterns = QtWidgets.QComboBox(DialogPatterns)
        self.cb_patterns.setGeometry(QtCore.QRect(80, 20, 241, 22))
        self.cb_patterns.setEditable(False)
        self.cb_patterns.setObjectName("cb_patterns")
        self.le_id = QtWidgets.QLineEdit(DialogPatterns)
        self.le_id.setGeometry(QtCore.QRect(380, 20, 41, 20))
        self.le_id.setReadOnly(True)
        self.le_id.setObjectName("le_id")
        self.label_2 = QtWidgets.QLabel(DialogPatterns)
        self.label_2.setGeometry(QtCore.QRect(20, 105, 101, 21))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(DialogPatterns)
        self.label_5.setGeometry(QtCore.QRect(350, 23, 47, 13))
        self.label_5.setObjectName("label_5")
        self.tw_pattern_stages = QtWidgets.QTableWidget(DialogPatterns)
        self.tw_pattern_stages.setGeometry(QtCore.QRect(10, 125, 421, 161))
        self.tw_pattern_stages.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_pattern_stages.setAlternatingRowColors(True)
        self.tw_pattern_stages.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_pattern_stages.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_pattern_stages.setObjectName("tw_pattern_stages")
        self.tw_pattern_stages.setColumnCount(0)
        self.tw_pattern_stages.setRowCount(0)
        self.tw_pattern_stages.verticalHeader().setVisible(False)
        self.pb_close = QtWidgets.QPushButton(DialogPatterns)
        self.pb_close.setGeometry(QtCore.QRect(370, 420, 71, 23))
        self.pb_close.setObjectName("pb_close")
        self.pb_add_item = QtWidgets.QPushButton(DialogPatterns)
        self.pb_add_item.setGeometry(QtCore.QRect(370, 103, 31, 23))
        self.pb_add_item.setObjectName("pb_add_item")
        self.pb_remove_item = QtWidgets.QPushButton(DialogPatterns)
        self.pb_remove_item.setGeometry(QtCore.QRect(400, 103, 31, 23))
        self.pb_remove_item.setObjectName("pb_remove_item")
        self.lbl_error = QtWidgets.QLabel(DialogPatterns)
        self.lbl_error.setEnabled(True)
        self.lbl_error.setGeometry(QtCore.QRect(270, 100, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_error.setFont(font)
        self.lbl_error.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 0);")
        self.lbl_error.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_error.setObjectName("lbl_error")
        self.frm_edit = QtWidgets.QFrame(DialogPatterns)
        self.frm_edit.setEnabled(False)
        self.frm_edit.setGeometry(QtCore.QRect(10, 290, 351, 151))
        self.frm_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.frm_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_edit.setObjectName("frm_edit")
        self.le_stage = QtWidgets.QLineEdit(self.frm_edit)
        self.le_stage.setGeometry(QtCore.QRect(13, 20, 31, 20))
        self.le_stage.setObjectName("le_stage")
        self.le_days = QtWidgets.QLineEdit(self.frm_edit)
        self.le_days.setGeometry(QtCore.QRect(50, 20, 31, 20))
        self.le_days.setObjectName("le_days")
        self.cb_lighting = QtWidgets.QComboBox(self.frm_edit)
        self.cb_lighting.setGeometry(QtCore.QRect(90, 51, 141, 22))
        self.cb_lighting.setObjectName("cb_lighting")
        self.pb_open_1 = QtWidgets.QPushButton(self.frm_edit)
        self.pb_open_1.setGeometry(QtCore.QRect(230, 50, 31, 24))
        self.pb_open_1.setObjectName("pb_open_1")
        self.pb_save = QtWidgets.QPushButton(self.frm_edit)
        self.pb_save.setGeometry(QtCore.QRect(270, 40, 75, 23))
        self.pb_save.setObjectName("pb_save")
        self.pb_save_as = QtWidgets.QPushButton(self.frm_edit)
        self.pb_save_as.setGeometry(QtCore.QRect(270, 70, 75, 23))
        self.pb_save_as.setObjectName("pb_save_as")
        self.label_6 = QtWidgets.QLabel(self.frm_edit)
        self.label_6.setGeometry(QtCore.QRect(10, 5, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frm_edit)
        self.label_7.setGeometry(QtCore.QRect(55, 6, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.frm_edit)
        self.label_9.setGeometry(QtCore.QRect(104, 5, 47, 13))
        self.label_9.setObjectName("label_9")
        self.le_area = QtWidgets.QLineEdit(self.frm_edit)
        self.le_area.setGeometry(QtCore.QRect(100, 20, 31, 20))
        self.le_area.setObjectName("le_area")
        self.pb_cancel = QtWidgets.QPushButton(self.frm_edit)
        self.pb_cancel.setGeometry(QtCore.QRect(270, 110, 75, 23))
        self.pb_cancel.setObjectName("pb_cancel")
        self.label_3 = QtWidgets.QLabel(self.frm_edit)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 47, 21))
        self.label_3.setObjectName("label_3")
        self.pb_open_2 = QtWidgets.QPushButton(self.frm_edit)
        self.pb_open_2.setGeometry(QtCore.QRect(230, 81, 31, 24))
        self.pb_open_2.setObjectName("pb_open_2")
        self.cb_temperature = QtWidgets.QComboBox(self.frm_edit)
        self.cb_temperature.setGeometry(QtCore.QRect(90, 82, 141, 22))
        self.cb_temperature.setObjectName("cb_temperature")
        self.label_8 = QtWidgets.QLabel(self.frm_edit)
        self.label_8.setGeometry(QtCore.QRect(10, 81, 81, 21))
        self.label_8.setObjectName("label_8")
        self.pb_open_3 = QtWidgets.QPushButton(self.frm_edit)
        self.pb_open_3.setGeometry(QtCore.QRect(230, 113, 31, 24))
        self.pb_open_3.setObjectName("pb_open_3")
        self.cb_feeding = QtWidgets.QComboBox(self.frm_edit)
        self.cb_feeding.setGeometry(QtCore.QRect(90, 114, 141, 22))
        self.cb_feeding.setObjectName("cb_feeding")
        self.label_10 = QtWidgets.QLabel(self.frm_edit)
        self.label_10.setGeometry(QtCore.QRect(10, 113, 47, 21))
        self.label_10.setObjectName("label_10")
        self.te_info = QtWidgets.QTextEdit(DialogPatterns)
        self.te_info.setGeometry(QtCore.QRect(90, 50, 331, 41))
        self.te_info.setReadOnly(False)
        self.te_info.setObjectName("te_info")
        self.label_11 = QtWidgets.QLabel(DialogPatterns)
        self.label_11.setGeometry(QtCore.QRect(20, 60, 71, 20))
        self.label_11.setObjectName("label_11")
        self.ck_auto_cal = QtWidgets.QCheckBox(DialogPatterns)
        self.ck_auto_cal.setGeometry(QtCore.QRect(130, 100, 111, 17))
        self.ck_auto_cal.setObjectName("ck_auto_cal")

        self.retranslateUi(DialogPatterns)
        QtCore.QMetaObject.connectSlotsByName(DialogPatterns)

    def retranslateUi(self, DialogPatterns):
        _translate = QtCore.QCoreApplication.translate
        DialogPatterns.setWindowTitle(_translate("DialogPatterns", "Process Patterns"))
        self.label.setText(_translate("DialogPatterns", "Pattern"))
        self.label_2.setText(_translate("DialogPatterns", "Pattern Stages"))
        self.label_5.setText(_translate("DialogPatterns", "ID"))
        self.pb_close.setText(_translate("DialogPatterns", "Close"))
        self.pb_add_item.setText(_translate("DialogPatterns", "+"))
        self.pb_remove_item.setText(_translate("DialogPatterns", "-"))
        self.lbl_error.setText(_translate("DialogPatterns", "Error"))
        self.pb_open_1.setText(_translate("DialogPatterns", "..."))
        self.pb_save.setText(_translate("DialogPatterns", "Save"))
        self.pb_save_as.setText(_translate("DialogPatterns", "Save As"))
        self.label_6.setText(_translate("DialogPatterns", "Stage"))
        self.label_7.setText(_translate("DialogPatterns", "Days"))
        self.label_9.setText(_translate("DialogPatterns", "Area"))
        self.pb_cancel.setText(_translate("DialogPatterns", "Cancel"))
        self.label_3.setText(_translate("DialogPatterns", "Lighting"))
        self.pb_open_2.setText(_translate("DialogPatterns", "..."))
        self.label_8.setText(_translate("DialogPatterns", "Temperature"))
        self.pb_open_3.setText(_translate("DialogPatterns", "..."))
        self.label_10.setText(_translate("DialogPatterns", "Feeding"))
        self.label_11.setText(_translate("DialogPatterns", "Description"))
        self.ck_auto_cal.setText(_translate("DialogPatterns", "Auto Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogPatterns = QtWidgets.QWidget()
    ui = Ui_DialogPatterns()
    ui.setupUi(DialogPatterns)
    DialogPatterns.show()
    sys.exit(app.exec_())

