# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogNutrients.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogNutrients(object):
    def setupUi(self, DialogNutrients):
        DialogNutrients.setObjectName("DialogNutrients")
        DialogNutrients.resize(722, 648)
        font = QtGui.QFont()
        font.setPointSize(11)
        DialogNutrients.setFont(font)
        self.tw_nutrients = QtWidgets.QTableWidget(DialogNutrients)
        self.tw_nutrients.setGeometry(QtCore.QRect(20, 10, 431, 311))
        self.tw_nutrients.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_nutrients.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_nutrients.setObjectName("tw_nutrients")
        self.tw_nutrients.setColumnCount(0)
        self.tw_nutrients.setRowCount(0)
        self.tw_nutrients.verticalHeader().setVisible(False)
        self.pb_close = QtWidgets.QPushButton(DialogNutrients)
        self.pb_close.setGeometry(QtCore.QRect(630, 600, 75, 26))
        self.pb_close.setAutoDefault(False)
        self.pb_close.setObjectName("pb_close")
        self.tw_pots = QtWidgets.QTableWidget(DialogNutrients)
        self.tw_pots.setGeometry(QtCore.QRect(20, 325, 431, 311))
        self.tw_pots.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_pots.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_pots.setObjectName("tw_pots")
        self.tw_pots.setColumnCount(0)
        self.tw_pots.setRowCount(0)
        self.tw_pots.verticalHeader().setVisible(False)
        self.frame = QtWidgets.QFrame(DialogNutrients)
        self.frame.setEnabled(False)
        self.frame.setGeometry(QtCore.QRect(460, 60, 251, 241))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_id = QtWidgets.QLabel(self.frame)
        self.lbl_id.setGeometry(QtCore.QRect(20, 16, 47, 16))
        self.lbl_id.setObjectName("lbl_id")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 47, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 47, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 47, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 47, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 210, 47, 16))
        self.label_6.setObjectName("label_6")
        self.le_stock = QtWidgets.QLineEdit(self.frame)
        self.le_stock.setGeometry(QtCore.QRect(70, 120, 61, 20))
        self.le_stock.setReadOnly(True)
        self.le_stock.setObjectName("le_stock")
        self.cb_pot = QtWidgets.QComboBox(self.frame)
        self.cb_pot.setGeometry(QtCore.QRect(70, 150, 69, 22))
        self.cb_pot.setObjectName("cb_pot")
        self.le_price = QtWidgets.QLineEdit(self.frame)
        self.le_price.setGeometry(QtCore.QRect(70, 180, 61, 20))
        self.le_price.setObjectName("le_price")
        self.le_size = QtWidgets.QLineEdit(self.frame)
        self.le_size.setGeometry(QtCore.QRect(70, 210, 61, 20))
        self.le_size.setObjectName("le_size")
        self.pb_save = QtWidgets.QPushButton(self.frame)
        self.pb_save.setGeometry(QtCore.QRect(160, 210, 75, 23))
        self.pb_save.setObjectName("pb_save")
        self.pb_top_up = QtWidgets.QPushButton(self.frame)
        self.pb_top_up.setGeometry(QtCore.QRect(20, 47, 61, 23))
        self.pb_top_up.setObjectName("pb_top_up")
        self.le_nutrient_add = QtWidgets.QLineEdit(self.frame)
        self.le_nutrient_add.setGeometry(QtCore.QRect(100, 49, 61, 20))
        self.le_nutrient_add.setObjectName("le_nutrient_add")
        self.pb_nutrient_add = QtWidgets.QPushButton(self.frame)
        self.pb_nutrient_add.setGeometry(QtCore.QRect(170, 47, 61, 23))
        self.pb_nutrient_add.setObjectName("pb_nutrient_add")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(10, 73, 231, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pb_clear = QtWidgets.QPushButton(self.frame)
        self.pb_clear.setGeometry(QtCore.QRect(160, 180, 75, 23))
        self.pb_clear.setObjectName("pb_clear")
        self.cb_name = QtWidgets.QComboBox(self.frame)
        self.cb_name.setGeometry(QtCore.QRect(70, 90, 141, 22))
        self.cb_name.setObjectName("cb_name")
        self.frame_2 = QtWidgets.QFrame(DialogNutrients)
        self.frame_2.setEnabled(False)
        self.frame_2.setGeometry(QtCore.QRect(460, 330, 251, 241))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lbl_pot = QtWidgets.QLabel(self.frame_2)
        self.lbl_pot.setGeometry(QtCore.QRect(20, 20, 47, 16))
        self.lbl_pot.setObjectName("lbl_pot")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(20, 90, 47, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(20, 180, 47, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(20, 150, 47, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(20, 120, 47, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(20, 210, 47, 16))
        self.label_11.setObjectName("label_11")
        self.le_current = QtWidgets.QLineEdit(self.frame_2)
        self.le_current.setGeometry(QtCore.QRect(80, 120, 61, 20))
        self.le_current.setReadOnly(True)
        self.le_current.setObjectName("le_current")
        self.le_max = QtWidgets.QLineEdit(self.frame_2)
        self.le_max.setGeometry(QtCore.QRect(80, 150, 61, 20))
        self.le_max.setObjectName("le_max")
        self.le_min = QtWidgets.QLineEdit(self.frame_2)
        self.le_min.setGeometry(QtCore.QRect(80, 180, 61, 20))
        self.le_min.setObjectName("le_min")
        self.le_pot_size = QtWidgets.QLineEdit(self.frame_2)
        self.le_pot_size.setGeometry(QtCore.QRect(80, 210, 61, 20))
        self.le_pot_size.setObjectName("le_pot_size")
        self.pb_save_pot = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_pot.setGeometry(QtCore.QRect(160, 210, 75, 23))
        self.pb_save_pot.setObjectName("pb_save_pot")
        self.pb_fill_pot = QtWidgets.QPushButton(self.frame_2)
        self.pb_fill_pot.setGeometry(QtCore.QRect(20, 50, 61, 23))
        self.pb_fill_pot.setObjectName("pb_fill_pot")
        self.le_pot_add = QtWidgets.QLineEdit(self.frame_2)
        self.le_pot_add.setGeometry(QtCore.QRect(100, 52, 61, 20))
        self.le_pot_add.setObjectName("le_pot_add")
        self.pb_pot_add = QtWidgets.QPushButton(self.frame_2)
        self.pb_pot_add.setGeometry(QtCore.QRect(170, 50, 61, 23))
        self.pb_pot_add.setObjectName("pb_pot_add")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(10, 76, 231, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pb_clear_2 = QtWidgets.QPushButton(self.frame_2)
        self.pb_clear_2.setGeometry(QtCore.QRect(160, 180, 75, 23))
        self.pb_clear_2.setObjectName("pb_clear_2")
        self.le_nutrient = QtWidgets.QLineEdit(self.frame_2)
        self.le_nutrient.setGeometry(QtCore.QRect(80, 90, 121, 20))
        self.le_nutrient.setReadOnly(True)
        self.le_nutrient.setObjectName("le_nutrient")
        self.pb_new = QtWidgets.QPushButton(DialogNutrients)
        self.pb_new.setGeometry(QtCore.QRect(630, 30, 75, 23))
        self.pb_new.setObjectName("pb_new")

        self.retranslateUi(DialogNutrients)
        QtCore.QMetaObject.connectSlotsByName(DialogNutrients)

    def retranslateUi(self, DialogNutrients):
        _translate = QtCore.QCoreApplication.translate
        DialogNutrients.setWindowTitle(_translate("DialogNutrients", "Nutrients"))
        self.pb_close.setText(_translate("DialogNutrients", "Close"))
        self.lbl_id.setText(_translate("DialogNutrients", "ID:"))
        self.label_2.setText(_translate("DialogNutrients", "Name"))
        self.label_3.setText(_translate("DialogNutrients", "Stock"))
        self.label_4.setText(_translate("DialogNutrients", "Pot"))
        self.label_5.setText(_translate("DialogNutrients", "Price"))
        self.label_6.setText(_translate("DialogNutrients", "Size"))
        self.pb_save.setText(_translate("DialogNutrients", "Save"))
        self.pb_top_up.setText(_translate("DialogNutrients", "Top Up"))
        self.pb_nutrient_add.setText(_translate("DialogNutrients", "Add"))
        self.pb_clear.setText(_translate("DialogNutrients", "Clear"))
        self.lbl_pot.setText(_translate("DialogNutrients", "Pot:"))
        self.label_7.setText(_translate("DialogNutrients", "Name"))
        self.label_8.setText(_translate("DialogNutrients", "Min"))
        self.label_9.setText(_translate("DialogNutrients", "Max"))
        self.label_10.setText(_translate("DialogNutrients", "Current Level"))
        self.label_11.setText(_translate("DialogNutrients", "Size"))
        self.pb_save_pot.setText(_translate("DialogNutrients", "Save"))
        self.pb_fill_pot.setText(_translate("DialogNutrients", "Fill"))
        self.pb_pot_add.setText(_translate("DialogNutrients", "Add"))
        self.pb_clear_2.setText(_translate("DialogNutrients", "Clear"))
        self.pb_new.setText(_translate("DialogNutrients", "New"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogNutrients = QtWidgets.QWidget()
    ui = Ui_DialogNutrients()
    ui.setupUi(DialogNutrients)
    DialogNutrients.show()
    sys.exit(app.exec_())

