# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogMixTankCalibration.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogMixTankCalibrate(object):
    def setupUi(self, DialogMixTankCalibrate):
        DialogMixTankCalibrate.setObjectName("DialogMixTankCalibrate")
        DialogMixTankCalibrate.resize(288, 379)
        font = QtGui.QFont()
        font.setPointSize(11)
        DialogMixTankCalibrate.setFont(font)
        self.lbl_name = QtWidgets.QLabel(DialogMixTankCalibrate)
        self.lbl_name.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name.setFont(font)
        self.lbl_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_name.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_name.setObjectName("lbl_name")
        self.pb_close = QtWidgets.QPushButton(DialogMixTankCalibrate)
        self.pb_close.setGeometry(QtCore.QRect(200, 340, 75, 23))
        self.pb_close.setObjectName("pb_close")
        self.label = QtWidgets.QLabel(DialogMixTankCalibrate)
        self.label.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.label.setObjectName("label")
        self.le_current_level = QtWidgets.QLineEdit(DialogMixTankCalibrate)
        self.le_current_level.setGeometry(QtCore.QRect(110, 50, 61, 21))
        self.le_current_level.setReadOnly(True)
        self.le_current_level.setObjectName("le_current_level")
        self.pb_cal_start = QtWidgets.QPushButton(DialogMixTankCalibrate)
        self.pb_cal_start.setGeometry(QtCore.QRect(2, 130, 81, 41))
        self.pb_cal_start.setObjectName("pb_cal_start")
        self.pb_tare = QtWidgets.QPushButton(DialogMixTankCalibrate)
        self.pb_tare.setGeometry(QtCore.QRect(190, 10, 71, 31))
        self.pb_tare.setObjectName("pb_tare")
        self.lbl_status = QtWidgets.QLabel(DialogMixTankCalibrate)
        self.lbl_status.setGeometry(QtCore.QRect(90, 123, 181, 41))
        self.lbl_status.setText("")
        self.lbl_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_status.setObjectName("lbl_status")
        self.line = QtWidgets.QFrame(DialogMixTankCalibrate)
        self.line.setGeometry(QtCore.QRect(0, 70, 281, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pb_read = QtWidgets.QPushButton(DialogMixTankCalibrate)
        self.pb_read.setGeometry(QtCore.QRect(190, 50, 75, 23))
        self.pb_read.setObjectName("pb_read")
        self.label_2 = QtWidgets.QLabel(DialogMixTankCalibrate)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 121, 21))
        self.label_2.setObjectName("label_2")
        self.le_cal_weight = QtWidgets.QLineEdit(DialogMixTankCalibrate)
        self.le_cal_weight.setGeometry(QtCore.QRect(140, 90, 61, 21))
        self.le_cal_weight.setObjectName("le_cal_weight")
        self.label_3 = QtWidgets.QLabel(DialogMixTankCalibrate)
        self.label_3.setGeometry(QtCore.QRect(210, 90, 21, 21))
        self.label_3.setObjectName("label_3")
        self.pb_set_weight = QtWidgets.QPushButton(DialogMixTankCalibrate)
        self.pb_set_weight.setGeometry(QtCore.QRect(230, 90, 51, 23))
        self.pb_set_weight.setObjectName("pb_set_weight")
        self.line_2 = QtWidgets.QFrame(DialogMixTankCalibrate)
        self.line_2.setGeometry(QtCore.QRect(0, 170, 281, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(DialogMixTankCalibrate)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 141, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(DialogMixTankCalibrate)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 91, 21))
        self.label_5.setObjectName("label_5")
        self.le_fill_correction = QtWidgets.QLineEdit(DialogMixTankCalibrate)
        self.le_fill_correction.setGeometry(QtCore.QRect(150, 183, 51, 20))
        self.le_fill_correction.setObjectName("le_fill_correction")
        self.le_dispense_correction = QtWidgets.QLineEdit(DialogMixTankCalibrate)
        self.le_dispense_correction.setGeometry(QtCore.QRect(150, 210, 51, 20))
        self.le_dispense_correction.setObjectName("le_dispense_correction")
        self.pb_save = QtWidgets.QPushButton(DialogMixTankCalibrate)
        self.pb_save.setGeometry(QtCore.QRect(214, 208, 61, 23))
        self.pb_save.setObjectName("pb_save")
        self.line_3 = QtWidgets.QFrame(DialogMixTankCalibrate)
        self.line_3.setGeometry(QtCore.QRect(3, 233, 281, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pb_fill_1 = QtWidgets.QPushButton(DialogMixTankCalibrate)
        self.pb_fill_1.setGeometry(QtCore.QRect(10, 293, 59, 26))
        self.pb_fill_1.setAutoDefault(False)
        self.pb_fill_1.setObjectName("pb_fill_1")
        self.pb_fill_2 = QtWidgets.QPushButton(DialogMixTankCalibrate)
        self.pb_fill_2.setGeometry(QtCore.QRect(80, 293, 59, 26))
        self.pb_fill_2.setAutoDefault(False)
        self.pb_fill_2.setObjectName("pb_fill_2")
        self.label_6 = QtWidgets.QLabel(DialogMixTankCalibrate)
        self.label_6.setGeometry(QtCore.QRect(50, 265, 71, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(DialogMixTankCalibrate)
        self.label_7.setGeometry(QtCore.QRect(190, 267, 91, 21))
        self.label_7.setObjectName("label_7")
        self.pb_pump = QtWidgets.QPushButton(DialogMixTankCalibrate)
        self.pb_pump.setGeometry(QtCore.QRect(183, 290, 59, 26))
        self.pb_pump.setObjectName("pb_pump")
        self.pb_stop = QtWidgets.QPushButton(DialogMixTankCalibrate)
        self.pb_stop.setGeometry(QtCore.QRect(80, 340, 59, 26))
        self.pb_stop.setObjectName("pb_stop")
        self.label_8 = QtWidgets.QLabel(DialogMixTankCalibrate)
        self.label_8.setGeometry(QtCore.QRect(10, 248, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(244, 244, 244);")
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(DialogMixTankCalibrate)
        QtCore.QMetaObject.connectSlotsByName(DialogMixTankCalibrate)

    def retranslateUi(self, DialogMixTankCalibrate):
        _translate = QtCore.QCoreApplication.translate
        DialogMixTankCalibrate.setWindowTitle(_translate("DialogMixTankCalibrate", "Mix Tank"))
        self.lbl_name.setText(_translate("DialogMixTankCalibrate", "Mix Tank "))
        self.pb_close.setText(_translate("DialogMixTankCalibrate", "Close"))
        self.label.setText(_translate("DialogMixTankCalibrate", "Current Level"))
        self.pb_cal_start.setText(_translate("DialogMixTankCalibrate", "Calibration\n"
"Start"))
        self.pb_tare.setText(_translate("DialogMixTankCalibrate", "Tare"))
        self.pb_read.setText(_translate("DialogMixTankCalibrate", "Read"))
        self.label_2.setText(_translate("DialogMixTankCalibrate", "Calibration Weight"))
        self.label_3.setText(_translate("DialogMixTankCalibrate", "g"))
        self.pb_set_weight.setText(_translate("DialogMixTankCalibrate", "Set"))
        self.label_4.setText(_translate("DialogMixTankCalibrate", "Dispense correction"))
        self.label_5.setText(_translate("DialogMixTankCalibrate", "Fill correction"))
        self.pb_save.setText(_translate("DialogMixTankCalibrate", "Save"))
        self.pb_fill_1.setText(_translate("DialogMixTankCalibrate", "Tank 1"))
        self.pb_fill_2.setText(_translate("DialogMixTankCalibrate", "Tank 2"))
        self.label_6.setText(_translate("DialogMixTankCalibrate", "Add from"))
        self.label_7.setText(_translate("DialogMixTankCalibrate", "Output"))
        self.pb_pump.setText(_translate("DialogMixTankCalibrate", "Pump"))
        self.pb_stop.setText(_translate("DialogMixTankCalibrate", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogMixTankCalibrate = QtWidgets.QWidget()
    ui = Ui_DialogMixTankCalibrate()
    ui.setupUi(DialogMixTankCalibrate)
    DialogMixTankCalibrate.show()
    sys.exit(app.exec_())

