# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogDispatchReconcilation.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogDispatchReconcilation(object):
    def setupUi(self, DialogDispatchReconcilation):
        DialogDispatchReconcilation.setObjectName("DialogDispatchReconcilation")
        DialogDispatchReconcilation.resize(400, 347)
        font = QtGui.QFont()
        font.setPointSize(11)
        DialogDispatchReconcilation.setFont(font)
        self.pb_close = QtWidgets.QPushButton(DialogDispatchReconcilation)
        self.pb_close.setGeometry(QtCore.QRect(310, 310, 75, 23))
        self.pb_close.setObjectName("pb_close")
        self.le_weight = QtWidgets.QLineEdit(DialogDispatchReconcilation)
        self.le_weight.setGeometry(QtCore.QRect(210, 40, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Digital-7")
        font.setPointSize(48)
        self.le_weight.setFont(font)
        self.le_weight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_weight.setReadOnly(True)
        self.le_weight.setClearButtonEnabled(False)
        self.le_weight.setObjectName("le_weight")
        self.pb_tare = QtWidgets.QPushButton(DialogDispatchReconcilation)
        self.pb_tare.setGeometry(QtCore.QRect(10, 310, 75, 23))
        self.pb_tare.setObjectName("pb_tare")
        self.le_start_amount = QtWidgets.QLineEdit(DialogDispatchReconcilation)
        self.le_start_amount.setGeometry(QtCore.QRect(132, 210, 71, 20))
        self.le_start_amount.setReadOnly(True)
        self.le_start_amount.setObjectName("le_start_amount")
        self.le_current_amount = QtWidgets.QLineEdit(DialogDispatchReconcilation)
        self.le_current_amount.setGeometry(QtCore.QRect(132, 240, 71, 20))
        self.le_current_amount.setReadOnly(True)
        self.le_current_amount.setObjectName("le_current_amount")
        self.le_amount_diff = QtWidgets.QLineEdit(DialogDispatchReconcilation)
        self.le_amount_diff.setGeometry(QtCore.QRect(130, 270, 71, 20))
        self.le_amount_diff.setReadOnly(True)
        self.le_amount_diff.setObjectName("le_amount_diff")
        self.label = QtWidgets.QLabel(DialogDispatchReconcilation)
        self.label.setGeometry(QtCore.QRect(20, 210, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DialogDispatchReconcilation)
        self.label_2.setGeometry(QtCore.QRect(20, 240, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(DialogDispatchReconcilation)
        self.label_3.setGeometry(QtCore.QRect(20, 270, 91, 21))
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(DialogDispatchReconcilation)
        self.frame.setGeometry(QtCore.QRect(209, 70, 181, 231))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.le_opening_w = QtWidgets.QLineEdit(self.frame)
        self.le_opening_w.setGeometry(QtCore.QRect(100, 40, 71, 20))
        self.le_opening_w.setReadOnly(True)
        self.le_opening_w.setObjectName("le_opening_w")
        self.le_opening_g = QtWidgets.QLineEdit(self.frame)
        self.le_opening_g.setGeometry(QtCore.QRect(100, 110, 71, 20))
        self.le_opening_g.setReadOnly(True)
        self.le_opening_g.setObjectName("le_opening_g")
        self.le_error_w = QtWidgets.QLineEdit(self.frame)
        self.le_error_w.setGeometry(QtCore.QRect(100, 70, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_error_w.setFont(font)
        self.le_error_w.setText("")
        self.le_error_w.setReadOnly(True)
        self.le_error_w.setObjectName("le_error_w")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 76, 91, 21))
        self.label_6.setObjectName("label_6")
        self.pb_store = QtWidgets.QPushButton(self.frame)
        self.pb_store.setGeometry(QtCore.QRect(50, 180, 91, 41))
        self.pb_store.setObjectName("pb_store")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 91, 21))
        self.label_7.setObjectName("label_7")
        self.le_current_g = QtWidgets.QLineEdit(self.frame)
        self.le_current_g.setGeometry(QtCore.QRect(100, 140, 71, 20))
        self.le_current_g.setReadOnly(True)
        self.le_current_g.setObjectName("le_current_g")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 140, 91, 21))
        self.label_8.setObjectName("label_8")
        self.lw_jars = QtWidgets.QListWidget(DialogDispatchReconcilation)
        self.lw_jars.setGeometry(QtCore.QRect(10, 10, 191, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lw_jars.setFont(font)
        self.lw_jars.setObjectName("lw_jars")
        self.lbl_jar = QtWidgets.QLabel(DialogDispatchReconcilation)
        self.lbl_jar.setGeometry(QtCore.QRect(210, 10, 131, 21))
        self.lbl_jar.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_jar.setText("")
        self.lbl_jar.setObjectName("lbl_jar")
        self.lbl_count = QtWidgets.QLabel(DialogDispatchReconcilation)
        self.lbl_count.setGeometry(QtCore.QRect(350, 10, 31, 21))
        self.lbl_count.setText("")
        self.lbl_count.setObjectName("lbl_count")

        self.retranslateUi(DialogDispatchReconcilation)
        QtCore.QMetaObject.connectSlotsByName(DialogDispatchReconcilation)

    def retranslateUi(self, DialogDispatchReconcilation):
        _translate = QtCore.QCoreApplication.translate
        DialogDispatchReconcilation.setWindowTitle(_translate("DialogDispatchReconcilation", "Dispatch - Reconcilation"))
        self.pb_close.setText(_translate("DialogDispatchReconcilation", "Close"))
        self.le_weight.setText(_translate("DialogDispatchReconcilation", "0000.0"))
        self.pb_tare.setText(_translate("DialogDispatchReconcilation", "Tare"))
        self.label.setText(_translate("DialogDispatchReconcilation", "Opening Bal"))
        self.label_2.setText(_translate("DialogDispatchReconcilation", "Current Bal"))
        self.label_3.setText(_translate("DialogDispatchReconcilation", "Deviation"))
        self.label_4.setText(_translate("DialogDispatchReconcilation", "Opening W"))
        self.label_6.setText(_translate("DialogDispatchReconcilation", "Deviation"))
        self.pb_store.setText(_translate("DialogDispatchReconcilation", "Store"))
        self.label_7.setText(_translate("DialogDispatchReconcilation", "Opening G"))
        self.label_8.setText(_translate("DialogDispatchReconcilation", "Current G"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogDispatchReconcilation = QtWidgets.QDialog()
    ui = Ui_DialogDispatchReconcilation()
    ui.setupUi(DialogDispatchReconcilation)
    DialogDispatchReconcilation.show()
    sys.exit(app.exec_())

