# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogProcessInfo.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogProcessInfo(object):
    def setupUi(self, DialogProcessInfo):
        DialogProcessInfo.setObjectName("DialogProcessInfo")
        DialogProcessInfo.resize(838, 824)
        font = QtGui.QFont()
        font.setPointSize(10)
        DialogProcessInfo.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(DialogProcessInfo)
        self.gridLayout.setObjectName("gridLayout")
        self.lbltitle = QtWidgets.QLabel(DialogProcessInfo)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbltitle.setFont(font)
        self.lbltitle.setObjectName("lbltitle")
        self.gridLayout.addWidget(self.lbltitle, 0, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(DialogProcessInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(DialogProcessInfo)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(DialogProcessInfo)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 3, 1, 1)
        self.tetime = QtWidgets.QTextEdit(DialogProcessInfo)
        self.tetime.setObjectName("tetime")
        self.gridLayout.addWidget(self.tetime, 2, 0, 1, 2)
        self.telighting = QtWidgets.QTextEdit(DialogProcessInfo)
        self.telighting.setObjectName("telighting")
        self.gridLayout.addWidget(self.telighting, 2, 2, 1, 1)
        self.tefeed = QtWidgets.QTextEdit(DialogProcessInfo)
        self.tefeed.setReadOnly(True)
        self.tefeed.setObjectName("tefeed")
        self.gridLayout.addWidget(self.tefeed, 2, 3, 10, 2)
        self.label_15 = QtWidgets.QLabel(DialogProcessInfo)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.te_strains = QtWidgets.QTextEdit(DialogProcessInfo)
        self.te_strains.setObjectName("te_strains")
        self.gridLayout.addWidget(self.te_strains, 4, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(DialogProcessInfo)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(DialogProcessInfo)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 2, 1, 1)
        self.teStages = QtWidgets.QTextEdit(DialogProcessInfo)
        self.teStages.setReadOnly(True)
        self.teStages.setTabStopWidth(10)
        self.teStages.setObjectName("teStages")
        self.gridLayout.addWidget(self.teStages, 6, 0, 1, 2)
        self.tewater = QtWidgets.QTextEdit(DialogProcessInfo)
        self.tewater.setReadOnly(True)
        self.tewater.setObjectName("tewater")
        self.gridLayout.addWidget(self.tewater, 6, 2, 3, 1)
        self.label_9 = QtWidgets.QLabel(DialogProcessInfo)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 2)
        self.teTemperatures = QtWidgets.QTextEdit(DialogProcessInfo)
        self.teTemperatures.setEnabled(True)
        self.teTemperatures.setReadOnly(True)
        self.teTemperatures.setObjectName("teTemperatures")
        self.gridLayout.addWidget(self.teTemperatures, 8, 0, 5, 2)
        self.label_13 = QtWidgets.QLabel(DialogProcessInfo)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 2, 1, 1)
        self.tenutrient = QtWidgets.QTextEdit(DialogProcessInfo)
        self.tenutrient.setObjectName("tenutrient")
        self.gridLayout.addWidget(self.tenutrient, 10, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(DialogProcessInfo)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 11, 2, 1, 1)
        self.teoutputs = QtWidgets.QTextEdit(DialogProcessInfo)
        self.teoutputs.setReadOnly(True)
        self.teoutputs.setObjectName("teoutputs")
        self.gridLayout.addWidget(self.teoutputs, 12, 2, 1, 3)
        self.pb_close = QtWidgets.QPushButton(DialogProcessInfo)
        self.pb_close.setObjectName("pb_close")
        self.gridLayout.addWidget(self.pb_close, 0, 4, 1, 1)

        self.retranslateUi(DialogProcessInfo)
        QtCore.QMetaObject.connectSlotsByName(DialogProcessInfo)

    def retranslateUi(self, DialogProcessInfo):
        _translate = QtCore.QCoreApplication.translate
        DialogProcessInfo.setWindowTitle(_translate("DialogProcessInfo", "Process Info"))
        self.lbltitle.setText(_translate("DialogProcessInfo", "TextLabel"))
        self.label_5.setText(_translate("DialogProcessInfo", "Time Schedule"))
        self.label_4.setText(_translate("DialogProcessInfo", "Lighting"))
        self.label_11.setText(_translate("DialogProcessInfo", "Feed Schedule"))
        self.label_15.setText(_translate("DialogProcessInfo", "Strains"))
        self.label_3.setText(_translate("DialogProcessInfo", "Stages"))
        self.label_12.setText(_translate("DialogProcessInfo", "Water Supply"))
        self.label_9.setText(_translate("DialogProcessInfo", "Enviroment"))
        self.label_13.setText(_translate("DialogProcessInfo", "Nutrient Status"))
        self.label_14.setText(_translate("DialogProcessInfo", "Sensors and Outputs"))
        self.pb_close.setText(_translate("DialogProcessInfo", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogProcessInfo = QtWidgets.QDialog()
    ui = Ui_DialogProcessInfo()
    ui.setupUi(DialogProcessInfo)
    DialogProcessInfo.show()
    sys.exit(app.exec_())

