# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogMessage.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogMessage(object):
    def setupUi(self, DialogMessage):
        DialogMessage.setObjectName("DialogMessage")
        DialogMessage.resize(438, 464)
        font = QtGui.QFont()
        font.setPointSize(11)
        DialogMessage.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(DialogMessage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ckb_this_2 = QtWidgets.QCheckBox(DialogMessage)
        self.ckb_this_2.setChecked(True)
        self.ckb_this_2.setObjectName("ckb_this_2")
        self.horizontalLayout.addWidget(self.ckb_this_2)
        self.ckb_other_2 = QtWidgets.QCheckBox(DialogMessage)
        self.ckb_other_2.setChecked(True)
        self.ckb_other_2.setObjectName("ckb_other_2")
        self.horizontalLayout.addWidget(self.ckb_other_2)
        self.ckb_relay_2 = QtWidgets.QCheckBox(DialogMessage)
        self.ckb_relay_2.setObjectName("ckb_relay_2")
        self.horizontalLayout.addWidget(self.ckb_relay_2)
        self.ckb_de_2 = QtWidgets.QCheckBox(DialogMessage)
        self.ckb_de_2.setChecked(True)
        self.ckb_de_2.setObjectName("ckb_de_2")
        self.horizontalLayout.addWidget(self.ckb_de_2)
        self.ckb_io_2 = QtWidgets.QCheckBox(DialogMessage)
        self.ckb_io_2.setChecked(True)
        self.ckb_io_2.setObjectName("ckb_io_2")
        self.horizontalLayout.addWidget(self.ckb_io_2)
        self.pb_close = QtWidgets.QPushButton(DialogMessage)
        self.pb_close.setObjectName("pb_close")
        self.horizontalLayout.addWidget(self.pb_close)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ckb_this = QtWidgets.QCheckBox(DialogMessage)
        self.ckb_this.setChecked(True)
        self.ckb_this.setObjectName("ckb_this")
        self.horizontalLayout_2.addWidget(self.ckb_this)
        self.ckb_other = QtWidgets.QCheckBox(DialogMessage)
        self.ckb_other.setChecked(True)
        self.ckb_other.setObjectName("ckb_other")
        self.horizontalLayout_2.addWidget(self.ckb_other)
        self.ckb_relay = QtWidgets.QCheckBox(DialogMessage)
        self.ckb_relay.setObjectName("ckb_relay")
        self.horizontalLayout_2.addWidget(self.ckb_relay)
        self.ckb_de = QtWidgets.QCheckBox(DialogMessage)
        self.ckb_de.setChecked(True)
        self.ckb_de.setObjectName("ckb_de")
        self.horizontalLayout_2.addWidget(self.ckb_de)
        self.ckb_io = QtWidgets.QCheckBox(DialogMessage)
        self.ckb_io.setChecked(True)
        self.ckb_io.setObjectName("ckb_io")
        self.horizontalLayout_2.addWidget(self.ckb_io)
        self.pb_clear = QtWidgets.QPushButton(DialogMessage)
        self.pb_clear.setObjectName("pb_clear")
        self.horizontalLayout_2.addWidget(self.pb_clear)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.te_message = QtWidgets.QTextEdit(DialogMessage)
        self.te_message.setReadOnly(True)
        self.te_message.setObjectName("te_message")
        self.gridLayout.addWidget(self.te_message, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(DialogMessage)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(DialogMessage)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(DialogMessage)
        QtCore.QMetaObject.connectSlotsByName(DialogMessage)

    def retranslateUi(self, DialogMessage):
        _translate = QtCore.QCoreApplication.translate
        DialogMessage.setWindowTitle(_translate("DialogMessage", "Dialog"))
        self.ckb_this_2.setText(_translate("DialogMessage", "This PC"))
        self.ckb_other_2.setText(_translate("DialogMessage", "Other PC"))
        self.ckb_relay_2.setText(_translate("DialogMessage", "Relay"))
        self.ckb_de_2.setText(_translate("DialogMessage", "D/E"))
        self.ckb_io_2.setText(_translate("DialogMessage", "I/O"))
        self.pb_close.setText(_translate("DialogMessage", "Close"))
        self.ckb_this.setText(_translate("DialogMessage", "This PC"))
        self.ckb_other.setText(_translate("DialogMessage", "Other PC"))
        self.ckb_relay.setText(_translate("DialogMessage", "Relay"))
        self.ckb_de.setText(_translate("DialogMessage", "D/E"))
        self.ckb_io.setText(_translate("DialogMessage", "I/O"))
        self.pb_clear.setText(_translate("DialogMessage", "Clear"))
        self.label.setText(_translate("DialogMessage", "From"))
        self.label_2.setText(_translate("DialogMessage", "To"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogMessage = QtWidgets.QDialog()
    ui = Ui_DialogMessage()
    ui.setupUi(DialogMessage)
    DialogMessage.show()
    sys.exit(app.exec_())

