# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogFeederManualMix.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogFeederManualMix(object):
    def setupUi(self, DialogFeederManualMix):
        DialogFeederManualMix.setObjectName("DialogFeederManualMix")
        DialogFeederManualMix.resize(687, 559)
        font = QtGui.QFont()
        font.setPointSize(11)
        DialogFeederManualMix.setFont(font)
        self.label_6 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_6.setGeometry(QtCore.QRect(9, 9, 80, 18))
        self.label_6.setObjectName("label_6")
        self.pb_load_1 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_load_1.setGeometry(QtCore.QRect(197, 9, 75, 26))
        self.pb_load_1.setAutoDefault(False)
        self.pb_load_1.setObjectName("pb_load_1")
        self.pb_load_2 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_load_2.setGeometry(QtCore.QRect(293, 9, 75, 26))
        self.pb_load_2.setAutoDefault(False)
        self.pb_load_2.setObjectName("pb_load_2")
        self.label_8 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_8.setGeometry(QtCore.QRect(9, 41, 44, 18))
        self.label_8.setObjectName("label_8")
        self.lbl_recipie = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_recipie.setGeometry(QtCore.QRect(197, 41, 201, 18))
        self.lbl_recipie.setObjectName("lbl_recipie")
        self.label_10 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_10.setGeometry(QtCore.QRect(9, 65, 131, 18))
        self.label_10.setObjectName("label_10")
        self.lbl_feed_total = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_feed_total.setGeometry(QtCore.QRect(197, 65, 25, 18))
        self.lbl_feed_total.setObjectName("lbl_feed_total")
        self.label_11 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_11.setGeometry(QtCore.QRect(293, 65, 65, 18))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.line_6 = QtWidgets.QFrame(DialogFeederManualMix)
        self.line_6.setGeometry(QtCore.QRect(9, 90, 401, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_4 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_4.setGeometry(QtCore.QRect(9, 101, 40, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_5.setGeometry(QtCore.QRect(9, 125, 33, 18))
        self.label_5.setObjectName("label_5")
        self.label_27 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_27.setGeometry(QtCore.QRect(228, 125, 16, 18))
        self.label_27.setObjectName("label_27")
        self.pb_read = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_read.setGeometry(QtCore.QRect(250, 125, 59, 26))
        self.pb_read.setAutoDefault(False)
        self.pb_read.setObjectName("pb_read")
        self.pb_zero = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_zero.setGeometry(QtCore.QRect(320, 120, 59, 26))
        self.pb_zero.setAutoDefault(False)
        self.pb_zero.setObjectName("pb_zero")
        self.label_26 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_26.setGeometry(QtCore.QRect(130, 126, 37, 18))
        self.label_26.setObjectName("label_26")
        self.le_fill_to = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_fill_to.setGeometry(QtCore.QRect(173, 124, 51, 24))
        self.le_fill_to.setObjectName("le_fill_to")
        self.label_28 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_28.setGeometry(QtCore.QRect(107, 126, 16, 18))
        self.label_28.setObjectName("label_28")
        self.pb_fill_1 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_fill_1.setGeometry(QtCore.QRect(20, 160, 59, 26))
        self.pb_fill_1.setAutoDefault(False)
        self.pb_fill_1.setObjectName("pb_fill_1")
        self.pb_drain = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_drain.setGeometry(QtCore.QRect(250, 160, 59, 26))
        self.pb_drain.setObjectName("pb_drain")
        self.line_4 = QtWidgets.QFrame(DialogFeederManualMix)
        self.line_4.setGeometry(QtCore.QRect(9, 184, 671, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_7 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 20, 18))
        self.label_7.setObjectName("label_7")
        self.pb_stir_n = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_stir_n.setGeometry(QtCore.QRect(60, 200, 75, 26))
        self.pb_stir_n.setAutoDefault(False)
        self.pb_stir_n.setObjectName("pb_stir_n")
        self.pb_stir_m = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_stir_m.setGeometry(QtCore.QRect(510, 200, 75, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_stir_m.sizePolicy().hasHeightForWidth())
        self.pb_stir_m.setSizePolicy(sizePolicy)
        self.pb_stir_m.setAutoDefault(False)
        self.pb_stir_m.setObjectName("pb_stir_m")
        self.line_3 = QtWidgets.QFrame(DialogFeederManualMix)
        self.line_3.setGeometry(QtCore.QRect(9, 225, 671, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_3 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_3.setGeometry(QtCore.QRect(10, 240, 88, 18))
        self.label_3.setObjectName("label_3")
        self.le_ml_1 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_1.setGeometry(QtCore.QRect(9, 265, 36, 24))
        self.le_ml_1.setObjectName("le_ml_1")
        self.label_18 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_18.setGeometry(QtCore.QRect(50, 264, 16, 18))
        self.label_18.setObjectName("label_18")
        self.lbl_added_1 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_1.setGeometry(QtCore.QRect(90, 264, 16, 18))
        self.lbl_added_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_1.setObjectName("lbl_added_1")
        self.pb_pump_1 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_1.setGeometry(QtCore.QRect(126, 264, 88, 26))
        self.pb_pump_1.setAutoDefault(False)
        self.pb_pump_1.setObjectName("pb_pump_1")
        self.le_ml_2 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_2.setGeometry(QtCore.QRect(9, 297, 36, 24))
        self.le_ml_2.setObjectName("le_ml_2")
        self.label_19 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_19.setGeometry(QtCore.QRect(50, 296, 16, 18))
        self.label_19.setObjectName("label_19")
        self.lbl_added_2 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_2.setGeometry(QtCore.QRect(90, 296, 16, 18))
        self.lbl_added_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_2.setObjectName("lbl_added_2")
        self.pb_pump_2 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_2.setGeometry(QtCore.QRect(126, 296, 88, 26))
        self.pb_pump_2.setAutoDefault(False)
        self.pb_pump_2.setObjectName("pb_pump_2")
        self.le_ml_3 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_3.setGeometry(QtCore.QRect(9, 329, 36, 24))
        self.le_ml_3.setObjectName("le_ml_3")
        self.label_20 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_20.setGeometry(QtCore.QRect(50, 328, 16, 18))
        self.label_20.setObjectName("label_20")
        self.lbl_added_3 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_3.setGeometry(QtCore.QRect(90, 328, 16, 18))
        self.lbl_added_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_3.setObjectName("lbl_added_3")
        self.pb_pump_3 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_3.setGeometry(QtCore.QRect(126, 328, 88, 26))
        self.pb_pump_3.setAutoDefault(False)
        self.pb_pump_3.setObjectName("pb_pump_3")
        self.le_ml_4 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_4.setGeometry(QtCore.QRect(9, 361, 36, 24))
        self.le_ml_4.setObjectName("le_ml_4")
        self.label_21 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_21.setGeometry(QtCore.QRect(50, 360, 16, 18))
        self.label_21.setObjectName("label_21")
        self.lbl_added_4 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_4.setGeometry(QtCore.QRect(90, 360, 16, 18))
        self.lbl_added_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_4.setObjectName("lbl_added_4")
        self.pb_pump_4 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_4.setGeometry(QtCore.QRect(126, 360, 88, 26))
        self.pb_pump_4.setAutoDefault(False)
        self.pb_pump_4.setObjectName("pb_pump_4")
        self.le_ml_5 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_5.setGeometry(QtCore.QRect(316, 264, 36, 24))
        self.le_ml_5.setObjectName("le_ml_5")
        self.label_22 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_22.setGeometry(QtCore.QRect(357, 265, 16, 18))
        self.label_22.setObjectName("label_22")
        self.lbl_added_5 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_5.setGeometry(QtCore.QRect(396, 268, 16, 18))
        self.lbl_added_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_5.setObjectName("lbl_added_5")
        self.pb_pump_5 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_5.setGeometry(QtCore.QRect(432, 264, 88, 26))
        self.pb_pump_5.setAutoDefault(False)
        self.pb_pump_5.setObjectName("pb_pump_5")
        self.le_ml_6 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_6.setGeometry(QtCore.QRect(316, 296, 36, 24))
        self.le_ml_6.setObjectName("le_ml_6")
        self.label_23 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_23.setGeometry(QtCore.QRect(357, 297, 16, 18))
        self.label_23.setObjectName("label_23")
        self.lbl_added_6 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_6.setGeometry(QtCore.QRect(396, 300, 16, 18))
        self.lbl_added_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_6.setObjectName("lbl_added_6")
        self.pb_pump_6 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_6.setGeometry(QtCore.QRect(432, 296, 88, 26))
        self.pb_pump_6.setAutoDefault(False)
        self.pb_pump_6.setObjectName("pb_pump_6")
        self.le_ml_7 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_7.setGeometry(QtCore.QRect(316, 328, 36, 24))
        self.le_ml_7.setObjectName("le_ml_7")
        self.label_24 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_24.setGeometry(QtCore.QRect(357, 329, 16, 18))
        self.label_24.setObjectName("label_24")
        self.lbl_added_7 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_7.setGeometry(QtCore.QRect(396, 332, 16, 18))
        self.lbl_added_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_7.setObjectName("lbl_added_7")
        self.pb_pump_7 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_7.setGeometry(QtCore.QRect(432, 328, 88, 26))
        self.pb_pump_7.setAutoDefault(False)
        self.pb_pump_7.setObjectName("pb_pump_7")
        self.le_ml_8 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_8.setGeometry(QtCore.QRect(316, 360, 36, 24))
        self.le_ml_8.setObjectName("le_ml_8")
        self.label_25 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_25.setGeometry(QtCore.QRect(357, 361, 16, 18))
        self.label_25.setObjectName("label_25")
        self.lbl_added_8 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_8.setGeometry(QtCore.QRect(396, 364, 16, 18))
        self.lbl_added_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_8.setObjectName("lbl_added_8")
        self.pb_pump_8 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_8.setGeometry(QtCore.QRect(432, 360, 88, 26))
        self.pb_pump_8.setAutoDefault(False)
        self.pb_pump_8.setObjectName("pb_pump_8")
        self.line_2 = QtWidgets.QFrame(DialogFeederManualMix)
        self.line_2.setGeometry(QtCore.QRect(10, 390, 681, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pb_clear = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_clear.setGeometry(QtCore.QRect(600, 290, 75, 26))
        self.pb_clear.setAutoDefault(False)
        self.pb_clear.setObjectName("pb_clear")
        self.pb_stop = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_stop.setGeometry(QtCore.QRect(600, 360, 75, 26))
        self.pb_stop.setObjectName("pb_stop")
        self.pb_close = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_close.setGeometry(QtCore.QRect(600, 520, 75, 26))
        self.pb_close.setAutoDefault(False)
        self.pb_close.setObjectName("pb_close")
        self.le_tank_level = QtWidgets.QLabel(DialogFeederManualMix)
        self.le_tank_level.setGeometry(QtCore.QRect(50, 125, 51, 20))
        self.le_tank_level.setFrameShape(QtWidgets.QFrame.Box)
        self.le_tank_level.setText("")
        self.le_tank_level.setObjectName("le_tank_level")
        self.pb_fill_2 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_fill_2.setGeometry(QtCore.QRect(90, 160, 59, 26))
        self.pb_fill_2.setAutoDefault(False)
        self.pb_fill_2.setObjectName("pb_fill_2")
        self.frm_v6 = QtWidgets.QFrame(DialogFeederManualMix)
        self.frm_v6.setGeometry(QtCore.QRect(90, 440, 91, 51))
        self.frm_v6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_v6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_v6.setObjectName("frm_v6")
        self.rb_v6_1 = QtWidgets.QRadioButton(self.frm_v6)
        self.rb_v6_1.setGeometry(QtCore.QRect(30, 0, 51, 21))
        self.rb_v6_1.setObjectName("rb_v6_1")
        self.rb_v6_2 = QtWidgets.QRadioButton(self.frm_v6)
        self.rb_v6_2.setGeometry(QtCore.QRect(31, 30, 51, 21))
        self.rb_v6_2.setObjectName("rb_v6_2")
        self.frm_v4 = QtWidgets.QFrame(DialogFeederManualMix)
        self.frm_v4.setGeometry(QtCore.QRect(10, 410, 91, 80))
        self.frm_v4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_v4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_v4.setObjectName("frm_v4")
        self.rb_v4_1 = QtWidgets.QRadioButton(self.frm_v4)
        self.rb_v4_1.setGeometry(QtCore.QRect(20, -3, 82, 21))
        self.rb_v4_1.setObjectName("rb_v4_1")
        self.rb_v4_2 = QtWidgets.QRadioButton(self.frm_v4)
        self.rb_v4_2.setGeometry(QtCore.QRect(20, 27, 82, 21))
        self.rb_v4_2.setObjectName("rb_v4_2")
        self.frm_v5 = QtWidgets.QFrame(DialogFeederManualMix)
        self.frm_v5.setGeometry(QtCore.QRect(110, 407, 191, 21))
        self.frm_v5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_v5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_v5.setObjectName("frm_v5")
        self.rb_v5_1 = QtWidgets.QRadioButton(self.frm_v5)
        self.rb_v5_1.setGeometry(QtCore.QRect(10, -3, 82, 21))
        self.rb_v5_1.setObjectName("rb_v5_1")
        self.rb_v5_2 = QtWidgets.QRadioButton(self.frm_v5)
        self.rb_v5_2.setGeometry(QtCore.QRect(100, -1, 82, 21))
        self.rb_v5_2.setObjectName("rb_v5_2")
        self.frm_v7 = QtWidgets.QFrame(DialogFeederManualMix)
        self.frm_v7.setGeometry(QtCore.QRect(200, 430, 81, 61))
        self.frm_v7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_v7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_v7.setObjectName("frm_v7")
        self.rb_v7_1 = QtWidgets.QRadioButton(self.frm_v7)
        self.rb_v7_1.setGeometry(QtCore.QRect(10, 10, 61, 17))
        self.rb_v7_1.setObjectName("rb_v7_1")
        self.rb_v7_2 = QtWidgets.QRadioButton(self.frm_v7)
        self.rb_v7_2.setGeometry(QtCore.QRect(10, 40, 61, 17))
        self.rb_v7_2.setObjectName("rb_v7_2")
        self.pb_add_all = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_add_all.setGeometry(QtCore.QRect(600, 260, 75, 23))
        self.pb_add_all.setObjectName("pb_add_all")
        self.lbl_status = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_status.setGeometry(QtCore.QRect(190, 204, 261, 16))
        self.lbl_status.setText("")
        self.lbl_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_status.setObjectName("lbl_status")
        self.te_recipe = QtWidgets.QTextEdit(DialogFeederManualMix)
        self.te_recipe.setGeometry(QtCore.QRect(420, 0, 241, 191))
        self.te_recipe.setObjectName("te_recipe")
        self.pb_stop_mix = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_stop_mix.setGeometry(QtCore.QRect(320, 160, 59, 26))
        self.pb_stop_mix.setObjectName("pb_stop_mix")
        self.pb_stop_feed = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_stop_feed.setGeometry(QtCore.QRect(300, 520, 111, 26))
        self.pb_stop_feed.setObjectName("pb_stop_feed")
        self.frame = QtWidgets.QFrame(DialogFeederManualMix)
        self.frame.setGeometry(QtCore.QRect(570, 400, 111, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 33, 18))
        self.label_13.setObjectName("label_13")
        self.le_flush_litres = QtWidgets.QLineEdit(self.frame)
        self.le_flush_litres.setGeometry(QtCore.QRect(50, 10, 31, 21))
        self.le_flush_litres.setObjectName("le_flush_litres")
        self.label_30 = QtWidgets.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(85, 11, 16, 18))
        self.label_30.setObjectName("label_30")
        self.pb_flush_2 = QtWidgets.QPushButton(self.frame)
        self.pb_flush_2.setGeometry(QtCore.QRect(20, 70, 75, 26))
        self.pb_flush_2.setAutoDefault(False)
        self.pb_flush_2.setObjectName("pb_flush_2")
        self.pb_flush_1 = QtWidgets.QPushButton(self.frame)
        self.pb_flush_1.setGeometry(QtCore.QRect(20, 40, 75, 26))
        self.pb_flush_1.setAutoDefault(False)
        self.pb_flush_1.setObjectName("pb_flush_1")
        self.frame_2 = QtWidgets.QFrame(DialogFeederManualMix)
        self.frame_2.setGeometry(QtCore.QRect(300, 400, 241, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pb_feed_continue = QtWidgets.QPushButton(self.frame_2)
        self.pb_feed_continue.setGeometry(QtCore.QRect(160, 70, 75, 23))
        self.pb_feed_continue.setObjectName("pb_feed_continue")
        self.pb_feed = QtWidgets.QPushButton(self.frame_2)
        self.pb_feed.setGeometry(QtCore.QRect(160, 40, 75, 23))
        self.pb_feed.setObjectName("pb_feed")
        self.label_31 = QtWidgets.QLabel(self.frame_2)
        self.label_31.setGeometry(QtCore.QRect(140, 70, 16, 18))
        self.label_31.setObjectName("label_31")
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        self.label_29.setGeometry(QtCore.QRect(140, 40, 16, 18))
        self.label_29.setObjectName("label_29")
        self.le_soak_time = QtWidgets.QLineEdit(self.frame_2)
        self.le_soak_time.setGeometry(QtCore.QRect(90, 70, 41, 21))
        self.le_soak_time.setObjectName("le_soak_time")
        self.le_feed = QtWidgets.QLineEdit(self.frame_2)
        self.le_feed.setGeometry(QtCore.QRect(90, 40, 41, 21))
        self.le_feed.setObjectName("le_feed")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 33, 18))
        self.label_9.setObjectName("label_9")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 71, 18))
        self.label_14.setObjectName("label_14")
        self.lbl_mix_output = QtWidgets.QLabel(self.frame_2)
        self.lbl_mix_output.setGeometry(QtCore.QRect(10, 10, 221, 21))
        self.lbl_mix_output.setText("")
        self.lbl_mix_output.setObjectName("lbl_mix_output")
        self.lbl_pot_amount_1 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_pot_amount_1.setGeometry(QtCore.QRect(229, 268, 31, 21))
        self.lbl_pot_amount_1.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_pot_amount_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_pot_amount_1.setText("")
        self.lbl_pot_amount_1.setObjectName("lbl_pot_amount_1")
        self.label_32 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_32.setGeometry(QtCore.QRect(266, 270, 16, 18))
        self.label_32.setObjectName("label_32")
        self.lbl_pot_amount_2 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_pot_amount_2.setGeometry(QtCore.QRect(229, 298, 31, 21))
        self.lbl_pot_amount_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_pot_amount_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_pot_amount_2.setText("")
        self.lbl_pot_amount_2.setObjectName("lbl_pot_amount_2")
        self.label_33 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_33.setGeometry(QtCore.QRect(266, 300, 16, 18))
        self.label_33.setObjectName("label_33")
        self.lbl_pot_amount_3 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_pot_amount_3.setGeometry(QtCore.QRect(229, 328, 31, 21))
        self.lbl_pot_amount_3.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_pot_amount_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_pot_amount_3.setText("")
        self.lbl_pot_amount_3.setObjectName("lbl_pot_amount_3")
        self.label_34 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_34.setGeometry(QtCore.QRect(266, 330, 16, 18))
        self.label_34.setObjectName("label_34")
        self.lbl_pot_amount_4 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_pot_amount_4.setGeometry(QtCore.QRect(229, 358, 31, 21))
        self.lbl_pot_amount_4.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_pot_amount_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_pot_amount_4.setText("")
        self.lbl_pot_amount_4.setObjectName("lbl_pot_amount_4")
        self.label_35 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_35.setGeometry(QtCore.QRect(266, 360, 16, 18))
        self.label_35.setObjectName("label_35")
        self.lbl_pot_amount_5 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_pot_amount_5.setGeometry(QtCore.QRect(533, 266, 31, 21))
        self.lbl_pot_amount_5.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_pot_amount_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_pot_amount_5.setText("")
        self.lbl_pot_amount_5.setObjectName("lbl_pot_amount_5")
        self.label_36 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_36.setGeometry(QtCore.QRect(570, 268, 16, 18))
        self.label_36.setObjectName("label_36")
        self.lbl_pot_amount_6 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_pot_amount_6.setGeometry(QtCore.QRect(534, 298, 31, 21))
        self.lbl_pot_amount_6.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_pot_amount_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_pot_amount_6.setText("")
        self.lbl_pot_amount_6.setObjectName("lbl_pot_amount_6")
        self.label_37 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_37.setGeometry(QtCore.QRect(571, 300, 16, 18))
        self.label_37.setObjectName("label_37")
        self.lbl_pot_amount_7 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_pot_amount_7.setGeometry(QtCore.QRect(535, 328, 31, 21))
        self.lbl_pot_amount_7.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_pot_amount_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_pot_amount_7.setText("")
        self.lbl_pot_amount_7.setObjectName("lbl_pot_amount_7")
        self.label_38 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_38.setGeometry(QtCore.QRect(572, 330, 16, 18))
        self.label_38.setObjectName("label_38")
        self.lbl_pot_amount_8 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_pot_amount_8.setGeometry(QtCore.QRect(535, 359, 31, 21))
        self.lbl_pot_amount_8.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_pot_amount_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_pot_amount_8.setText("")
        self.lbl_pot_amount_8.setObjectName("lbl_pot_amount_8")
        self.label_39 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_39.setGeometry(QtCore.QRect(572, 361, 16, 18))
        self.label_39.setObjectName("label_39")
        self.pb_nutrients = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_nutrients.setGeometry(QtCore.QRect(20, 520, 75, 26))
        self.pb_nutrients.setAutoDefault(False)
        self.pb_nutrients.setObjectName("pb_nutrients")
        self.cb_mix = QtWidgets.QComboBox(DialogFeederManualMix)
        self.cb_mix.setGeometry(QtCore.QRect(370, 64, 41, 22))
        self.cb_mix.setObjectName("cb_mix")

        self.retranslateUi(DialogFeederManualMix)
        QtCore.QMetaObject.connectSlotsByName(DialogFeederManualMix)

    def retranslateUi(self, DialogFeederManualMix):
        _translate = QtCore.QCoreApplication.translate
        DialogFeederManualMix.setWindowTitle(_translate("DialogFeederManualMix", "Feeder Manual Mix"))
        self.label_6.setText(_translate("DialogFeederManualMix", "Load Recipie"))
        self.pb_load_1.setText(_translate("DialogFeederManualMix", "Area 1"))
        self.pb_load_2.setText(_translate("DialogFeederManualMix", "Area 2"))
        self.label_8.setText(_translate("DialogFeederManualMix", "Recipie"))
        self.lbl_recipie.setText(_translate("DialogFeederManualMix", "None"))
        self.label_10.setText(_translate("DialogFeederManualMix", "Feed Total Litres"))
        self.lbl_feed_total.setText(_translate("DialogFeederManualMix", "N/A"))
        self.label_11.setText(_translate("DialogFeederManualMix", "Mix"))
        self.label_4.setText(_translate("DialogFeederManualMix", "Water"))
        self.label_5.setText(_translate("DialogFeederManualMix", "Level"))
        self.label_27.setText(_translate("DialogFeederManualMix", "L"))
        self.pb_read.setText(_translate("DialogFeederManualMix", "Read"))
        self.pb_zero.setText(_translate("DialogFeederManualMix", "Zero"))
        self.label_26.setText(_translate("DialogFeederManualMix", "Fill To"))
        self.label_28.setText(_translate("DialogFeederManualMix", "L"))
        self.pb_fill_1.setText(_translate("DialogFeederManualMix", "Tank 1"))
        self.pb_drain.setText(_translate("DialogFeederManualMix", "Drain"))
        self.label_7.setText(_translate("DialogFeederManualMix", "Stir"))
        self.pb_stir_n.setText(_translate("DialogFeederManualMix", "Nutrients"))
        self.pb_stir_m.setText(_translate("DialogFeederManualMix", "Mix"))
        self.label_3.setText(_translate("DialogFeederManualMix", "Add Nutrients"))
        self.label_18.setText(_translate("DialogFeederManualMix", "ml"))
        self.lbl_added_1.setText(_translate("DialogFeederManualMix", "0"))
        self.pb_pump_1.setText(_translate("DialogFeederManualMix", "1"))
        self.label_19.setText(_translate("DialogFeederManualMix", "ml"))
        self.lbl_added_2.setText(_translate("DialogFeederManualMix", "0"))
        self.pb_pump_2.setText(_translate("DialogFeederManualMix", "2"))
        self.label_20.setText(_translate("DialogFeederManualMix", "ml"))
        self.lbl_added_3.setText(_translate("DialogFeederManualMix", "0"))
        self.pb_pump_3.setText(_translate("DialogFeederManualMix", "3"))
        self.label_21.setText(_translate("DialogFeederManualMix", "ml"))
        self.lbl_added_4.setText(_translate("DialogFeederManualMix", "0"))
        self.pb_pump_4.setText(_translate("DialogFeederManualMix", "4"))
        self.label_22.setText(_translate("DialogFeederManualMix", "ml"))
        self.lbl_added_5.setText(_translate("DialogFeederManualMix", "0"))
        self.pb_pump_5.setText(_translate("DialogFeederManualMix", "5"))
        self.label_23.setText(_translate("DialogFeederManualMix", "ml"))
        self.lbl_added_6.setText(_translate("DialogFeederManualMix", "0"))
        self.pb_pump_6.setText(_translate("DialogFeederManualMix", "6"))
        self.label_24.setText(_translate("DialogFeederManualMix", "ml"))
        self.lbl_added_7.setText(_translate("DialogFeederManualMix", "0"))
        self.pb_pump_7.setText(_translate("DialogFeederManualMix", "7"))
        self.label_25.setText(_translate("DialogFeederManualMix", "ml"))
        self.lbl_added_8.setText(_translate("DialogFeederManualMix", "0"))
        self.pb_pump_8.setText(_translate("DialogFeederManualMix", "8"))
        self.pb_clear.setText(_translate("DialogFeederManualMix", "Clear"))
        self.pb_stop.setText(_translate("DialogFeederManualMix", "Stop"))
        self.pb_close.setText(_translate("DialogFeederManualMix", "Close"))
        self.pb_fill_2.setText(_translate("DialogFeederManualMix", "Tank 2"))
        self.rb_v6_1.setText(_translate("DialogFeederManualMix", "Feed"))
        self.rb_v6_2.setText(_translate("DialogFeederManualMix", "Flush"))
        self.rb_v4_1.setText(_translate("DialogFeederManualMix", "Auto"))
        self.rb_v4_2.setText(_translate("DialogFeederManualMix", "Manual"))
        self.rb_v5_1.setText(_translate("DialogFeederManualMix", "Area 1"))
        self.rb_v5_2.setText(_translate("DialogFeederManualMix", "Area 2"))
        self.rb_v7_1.setText(_translate("DialogFeederManualMix", "Feed"))
        self.rb_v7_2.setText(_translate("DialogFeederManualMix", "Flush"))
        self.pb_add_all.setText(_translate("DialogFeederManualMix", "Add All"))
        self.pb_stop_mix.setText(_translate("DialogFeederManualMix", "Stop"))
        self.pb_stop_feed.setText(_translate("DialogFeederManualMix", "Stop"))
        self.label_13.setText(_translate("DialogFeederManualMix", "Flush"))
        self.label_30.setText(_translate("DialogFeederManualMix", "L"))
        self.pb_flush_2.setText(_translate("DialogFeederManualMix", "Area 2"))
        self.pb_flush_1.setText(_translate("DialogFeederManualMix", "Area 1"))
        self.pb_feed_continue.setText(_translate("DialogFeederManualMix", "Continue"))
        self.pb_feed.setText(_translate("DialogFeederManualMix", "Feed"))
        self.label_31.setText(_translate("DialogFeederManualMix", "S"))
        self.label_29.setText(_translate("DialogFeederManualMix", "L"))
        self.label_9.setText(_translate("DialogFeederManualMix", "Feed"))
        self.label_14.setText(_translate("DialogFeederManualMix", "Soak Time"))
        self.label_32.setText(_translate("DialogFeederManualMix", "ml"))
        self.label_33.setText(_translate("DialogFeederManualMix", "ml"))
        self.label_34.setText(_translate("DialogFeederManualMix", "ml"))
        self.label_35.setText(_translate("DialogFeederManualMix", "ml"))
        self.label_36.setText(_translate("DialogFeederManualMix", "ml"))
        self.label_37.setText(_translate("DialogFeederManualMix", "ml"))
        self.label_38.setText(_translate("DialogFeederManualMix", "ml"))
        self.label_39.setText(_translate("DialogFeederManualMix", "ml"))
        self.pb_nutrients.setText(_translate("DialogFeederManualMix", "Nutrients"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogFeederManualMix = QtWidgets.QDialog()
    ui = Ui_DialogFeederManualMix()
    ui.setupUi(DialogFeederManualMix)
    DialogFeederManualMix.show()
    sys.exit(app.exec_())

