# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogGraphEnviroment.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogGraphEnv(object):
    def setupUi(self, DialogGraphEnv):
        DialogGraphEnv.setObjectName("DialogGraphEnv")
        DialogGraphEnv.resize(1254, 615)
        font = QtGui.QFont()
        font.setPointSize(11)
        DialogGraphEnv.setFont(font)
        self.tabWidget = QtWidgets.QTabWidget(DialogGraphEnv)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1261, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(840, 10, 120, 61))
        self.groupBox_5.setObjectName("groupBox_5")
        self.temp_5_1 = QtWidgets.QCheckBox(self.groupBox_5)
        self.temp_5_1.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.temp_5_1.setObjectName("temp_5_1")
        self.ck_hum_4 = QtWidgets.QCheckBox(self.groupBox_5)
        self.ck_hum_4.setGeometry(QtCore.QRect(10, 20, 81, 19))
        self.ck_hum_4.setObjectName("ck_hum_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 0, 120, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.temp_2_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.temp_2_3.setGeometry(QtCore.QRect(0, 80, 111, 17))
        self.temp_2_3.setObjectName("temp_2_3")
        self.temp_2_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.temp_2_2.setGeometry(QtCore.QRect(0, 60, 111, 20))
        self.temp_2_2.setObjectName("temp_2_2")
        self.temp_2_1 = QtWidgets.QCheckBox(self.groupBox_2)
        self.temp_2_1.setGeometry(QtCore.QRect(0, 40, 111, 17))
        self.temp_2_1.setObjectName("temp_2_1")
        self.ck_hum_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.ck_hum_2.setGeometry(QtCore.QRect(0, 20, 81, 19))
        self.ck_hum_2.setObjectName("ck_hum_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(320, 0, 120, 101))
        self.groupBox.setObjectName("groupBox")
        self.temp_1_3 = QtWidgets.QCheckBox(self.groupBox)
        self.temp_1_3.setGeometry(QtCore.QRect(10, 80, 111, 17))
        self.temp_1_3.setObjectName("temp_1_3")
        self.temp_1_1 = QtWidgets.QCheckBox(self.groupBox)
        self.temp_1_1.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.temp_1_1.setObjectName("temp_1_1")
        self.temp_1_2 = QtWidgets.QCheckBox(self.groupBox)
        self.temp_1_2.setGeometry(QtCore.QRect(10, 60, 111, 20))
        self.temp_1_2.setObjectName("temp_1_2")
        self.ck_hum_1 = QtWidgets.QCheckBox(self.groupBox)
        self.ck_hum_1.setGeometry(QtCore.QRect(10, 20, 81, 19))
        self.ck_hum_1.setObjectName("ck_hum_1")
        self.cb_logs = QtWidgets.QComboBox(self.tab)
        self.cb_logs.setGeometry(QtCore.QRect(10, 40, 141, 22))
        self.cb_logs.setObjectName("cb_logs")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(580, 10, 120, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.temp_3_1 = QtWidgets.QCheckBox(self.groupBox_3)
        self.temp_3_1.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.temp_3_1.setObjectName("temp_3_1")
        self.ck_hum_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.ck_hum_3.setGeometry(QtCore.QRect(10, 20, 81, 19))
        self.ck_hum_3.setObjectName("ck_hum_3")
        self.pb_refresh = QtWidgets.QPushButton(self.tab)
        self.pb_refresh.setGeometry(QtCore.QRect(980, 10, 75, 23))
        self.pb_refresh.setObjectName("pb_refresh")
        self.ck_live = QtWidgets.QCheckBox(self.tab)
        self.ck_live.setGeometry(QtCore.QRect(270, 80, 70, 17))
        self.ck_live.setObjectName("ck_live")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(710, 10, 120, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.temp_4_1 = QtWidgets.QCheckBox(self.groupBox_4)
        self.temp_4_1.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.temp_4_1.setObjectName("temp_4_1")
        self.pb_close = QtWidgets.QPushButton(self.tab)
        self.pb_close.setGeometry(QtCore.QRect(1170, 10, 75, 23))
        self.pb_close.setObjectName("pb_close")
        self.wg_graph_1 = QtWidgets.QWidget(self.tab)
        self.wg_graph_1.setGeometry(QtCore.QRect(6, 100, 1241, 479))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wg_graph_1.sizePolicy().hasHeightForWidth())
        self.wg_graph_1.setSizePolicy(sizePolicy)
        self.wg_graph_1.setObjectName("wg_graph_1")
        self.cb_year = QtWidgets.QComboBox(self.tab)
        self.cb_year.setGeometry(QtCore.QRect(10, 10, 81, 22))
        self.cb_year.setObjectName("cb_year")
        self.cb_month = QtWidgets.QComboBox(self.tab)
        self.cb_month.setGeometry(QtCore.QRect(100, 10, 141, 22))
        self.cb_month.setObjectName("cb_month")
        self.pb_reload = QtWidgets.QPushButton(self.tab)
        self.pb_reload.setGeometry(QtCore.QRect(170, 40, 75, 23))
        self.pb_reload.setObjectName("pb_reload")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pb_close_2 = QtWidgets.QPushButton(self.tab_2)
        self.pb_close_2.setGeometry(QtCore.QRect(1170, 10, 75, 23))
        self.pb_close_2.setObjectName("pb_close_2")
        self.ck_out_1 = QtWidgets.QCheckBox(self.tab_2)
        self.ck_out_1.setGeometry(QtCore.QRect(320, 0, 71, 21))
        self.ck_out_1.setObjectName("ck_out_1")
        self.ck_out_2 = QtWidgets.QCheckBox(self.tab_2)
        self.ck_out_2.setGeometry(QtCore.QRect(320, 30, 71, 21))
        self.ck_out_2.setObjectName("ck_out_2")
        self.ck_out_3 = QtWidgets.QCheckBox(self.tab_2)
        self.ck_out_3.setGeometry(QtCore.QRect(320, 60, 71, 21))
        self.ck_out_3.setObjectName("ck_out_3")
        self.ck_out_4 = QtWidgets.QCheckBox(self.tab_2)
        self.ck_out_4.setGeometry(QtCore.QRect(410, 0, 91, 21))
        self.ck_out_4.setObjectName("ck_out_4")
        self.ck_out_5 = QtWidgets.QCheckBox(self.tab_2)
        self.ck_out_5.setGeometry(QtCore.QRect(410, 30, 121, 21))
        self.ck_out_5.setObjectName("ck_out_5")
        self.wg_graph_2 = QtWidgets.QWidget(self.tab_2)
        self.wg_graph_2.setGeometry(QtCore.QRect(6, 100, 1241, 479))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wg_graph_2.sizePolicy().hasHeightForWidth())
        self.wg_graph_2.setSizePolicy(sizePolicy)
        self.wg_graph_2.setObjectName("wg_graph_2")
        self.cb_year_2 = QtWidgets.QComboBox(self.tab_2)
        self.cb_year_2.setGeometry(QtCore.QRect(10, 10, 81, 22))
        self.cb_year_2.setObjectName("cb_year_2")
        self.cb_logs_2 = QtWidgets.QComboBox(self.tab_2)
        self.cb_logs_2.setGeometry(QtCore.QRect(10, 40, 141, 22))
        self.cb_logs_2.setObjectName("cb_logs_2")
        self.pb_reload_2 = QtWidgets.QPushButton(self.tab_2)
        self.pb_reload_2.setGeometry(QtCore.QRect(170, 40, 75, 23))
        self.pb_reload_2.setObjectName("pb_reload_2")
        self.cb_month_2 = QtWidgets.QComboBox(self.tab_2)
        self.cb_month_2.setGeometry(QtCore.QRect(100, 10, 141, 22))
        self.cb_month_2.setObjectName("cb_month_2")
        self.pb_refresh_2 = QtWidgets.QPushButton(self.tab_2)
        self.pb_refresh_2.setGeometry(QtCore.QRect(980, 10, 75, 23))
        self.pb_refresh_2.setObjectName("pb_refresh_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pb_close_3 = QtWidgets.QPushButton(self.tab_3)
        self.pb_close_3.setGeometry(QtCore.QRect(1170, 10, 75, 23))
        self.pb_close_3.setObjectName("pb_close_3")
        self.ck_fan_1 = QtWidgets.QCheckBox(self.tab_3)
        self.ck_fan_1.setGeometry(QtCore.QRect(340, 10, 71, 21))
        self.ck_fan_1.setObjectName("ck_fan_1")
        self.ck_fan_2 = QtWidgets.QCheckBox(self.tab_3)
        self.ck_fan_2.setGeometry(QtCore.QRect(430, 10, 71, 21))
        self.ck_fan_2.setObjectName("ck_fan_2")
        self.wg_graph_3 = QtWidgets.QWidget(self.tab_3)
        self.wg_graph_3.setGeometry(QtCore.QRect(4, 100, 1241, 479))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wg_graph_3.sizePolicy().hasHeightForWidth())
        self.wg_graph_3.setSizePolicy(sizePolicy)
        self.wg_graph_3.setObjectName("wg_graph_3")
        self.cb_year_3 = QtWidgets.QComboBox(self.tab_3)
        self.cb_year_3.setGeometry(QtCore.QRect(10, 10, 81, 22))
        self.cb_year_3.setObjectName("cb_year_3")
        self.cb_logs_3 = QtWidgets.QComboBox(self.tab_3)
        self.cb_logs_3.setGeometry(QtCore.QRect(10, 40, 141, 22))
        self.cb_logs_3.setObjectName("cb_logs_3")
        self.pb_reload_3 = QtWidgets.QPushButton(self.tab_3)
        self.pb_reload_3.setGeometry(QtCore.QRect(170, 40, 75, 23))
        self.pb_reload_3.setObjectName("pb_reload_3")
        self.cb_month_3 = QtWidgets.QComboBox(self.tab_3)
        self.cb_month_3.setGeometry(QtCore.QRect(100, 10, 141, 22))
        self.cb_month_3.setObjectName("cb_month_3")
        self.pb_refresh_3 = QtWidgets.QPushButton(self.tab_3)
        self.pb_refresh_3.setGeometry(QtCore.QRect(970, 10, 75, 23))
        self.pb_refresh_3.setObjectName("pb_refresh_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pb_close_4 = QtWidgets.QPushButton(self.tab_4)
        self.pb_close_4.setGeometry(QtCore.QRect(1160, 10, 75, 23))
        self.pb_close_4.setObjectName("pb_close_4")
        self.wg_graph_4 = QtWidgets.QWidget(self.tab_4)
        self.wg_graph_4.setGeometry(QtCore.QRect(4, 100, 1241, 479))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wg_graph_4.sizePolicy().hasHeightForWidth())
        self.wg_graph_4.setSizePolicy(sizePolicy)
        self.wg_graph_4.setObjectName("wg_graph_4")
        self.cb_year_4 = QtWidgets.QComboBox(self.tab_4)
        self.cb_year_4.setGeometry(QtCore.QRect(10, 10, 81, 22))
        self.cb_year_4.setObjectName("cb_year_4")
        self.cb_logs_4 = QtWidgets.QComboBox(self.tab_4)
        self.cb_logs_4.setGeometry(QtCore.QRect(10, 40, 141, 22))
        self.cb_logs_4.setObjectName("cb_logs_4")
        self.pb_reload_4 = QtWidgets.QPushButton(self.tab_4)
        self.pb_reload_4.setGeometry(QtCore.QRect(170, 40, 75, 23))
        self.pb_reload_4.setObjectName("pb_reload_4")
        self.cb_month_4 = QtWidgets.QComboBox(self.tab_4)
        self.cb_month_4.setGeometry(QtCore.QRect(100, 10, 141, 22))
        self.cb_month_4.setObjectName("cb_month_4")
        self.pb_refresh_4 = QtWidgets.QPushButton(self.tab_4)
        self.pb_refresh_4.setGeometry(QtCore.QRect(980, 10, 75, 23))
        self.pb_refresh_4.setObjectName("pb_refresh_4")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(DialogGraphEnv)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogGraphEnv)

    def retranslateUi(self, DialogGraphEnv):
        _translate = QtCore.QCoreApplication.translate
        DialogGraphEnv.setWindowTitle(_translate("DialogGraphEnv", "Enviroment Graph"))
        self.groupBox_5.setTitle(_translate("DialogGraphEnv", "Outside"))
        self.temp_5_1.setText(_translate("DialogGraphEnv", "Temperature"))
        self.ck_hum_4.setText(_translate("DialogGraphEnv", "Humidity"))
        self.groupBox_2.setTitle(_translate("DialogGraphEnv", "Area 2"))
        self.temp_2_3.setText(_translate("DialogGraphEnv", "Root"))
        self.temp_2_2.setText(_translate("DialogGraphEnv", "Canopy"))
        self.temp_2_1.setText(_translate("DialogGraphEnv", "Temperature"))
        self.ck_hum_2.setText(_translate("DialogGraphEnv", "Humidity"))
        self.groupBox.setTitle(_translate("DialogGraphEnv", "Area 1"))
        self.temp_1_3.setText(_translate("DialogGraphEnv", "Root"))
        self.temp_1_1.setText(_translate("DialogGraphEnv", "Temperature"))
        self.temp_1_2.setText(_translate("DialogGraphEnv", "Canopy"))
        self.ck_hum_1.setText(_translate("DialogGraphEnv", "Humidity"))
        self.groupBox_3.setTitle(_translate("DialogGraphEnv", "Drying"))
        self.temp_3_1.setText(_translate("DialogGraphEnv", "Temperature"))
        self.ck_hum_3.setText(_translate("DialogGraphEnv", "Humidity"))
        self.pb_refresh.setText(_translate("DialogGraphEnv", "Refresh"))
        self.ck_live.setText(_translate("DialogGraphEnv", "Live"))
        self.groupBox_4.setTitle(_translate("DialogGraphEnv", "Workshop"))
        self.temp_4_1.setText(_translate("DialogGraphEnv", "Temperature"))
        self.pb_close.setText(_translate("DialogGraphEnv", "Close"))
        self.pb_reload.setText(_translate("DialogGraphEnv", "Load File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DialogGraphEnv", "Sensors"))
        self.pb_close_2.setText(_translate("DialogGraphEnv", "Close"))
        self.ck_out_1.setText(_translate("DialogGraphEnv", "Area 1"))
        self.ck_out_2.setText(_translate("DialogGraphEnv", "Area 2"))
        self.ck_out_3.setText(_translate("DialogGraphEnv", "Area 3"))
        self.ck_out_4.setText(_translate("DialogGraphEnv", "Workshop"))
        self.ck_out_5.setText(_translate("DialogGraphEnv", "Water Heaters"))
        self.pb_reload_2.setText(_translate("DialogGraphEnv", "Load File"))
        self.pb_refresh_2.setText(_translate("DialogGraphEnv", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DialogGraphEnv", "Outputs"))
        self.pb_close_3.setText(_translate("DialogGraphEnv", "Close"))
        self.ck_fan_1.setText(_translate("DialogGraphEnv", "Fan 1"))
        self.ck_fan_2.setText(_translate("DialogGraphEnv", "Fan 2"))
        self.pb_reload_3.setText(_translate("DialogGraphEnv", "Load File"))
        self.pb_refresh_3.setText(_translate("DialogGraphEnv", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DialogGraphEnv", "Fans"))
        self.pb_close_4.setText(_translate("DialogGraphEnv", "Close"))
        self.pb_reload_4.setText(_translate("DialogGraphEnv", "Load File"))
        self.pb_refresh_4.setText(_translate("DialogGraphEnv", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("DialogGraphEnv", "Access"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogGraphEnv = QtWidgets.QWidget()
    ui = Ui_DialogGraphEnv()
    ui.setupUi(DialogGraphEnv)
    DialogGraphEnv.show()
    sys.exit(app.exec_())

