# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogFeederManualMix.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogFeederManualMix(object):
    def setupUi(self, DialogFeederManualMix):
        DialogFeederManualMix.setObjectName("DialogFeederManualMix")
        DialogFeederManualMix.resize(687, 643)
        font = QtGui.QFont()
        font.setPointSize(11)
        DialogFeederManualMix.setFont(font)
        self.label_6 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_6.setGeometry(QtCore.QRect(9, 9, 80, 18))
        self.label_6.setObjectName("label_6")
        self.pb_load_1 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_load_1.setGeometry(QtCore.QRect(197, 9, 75, 26))
        self.pb_load_1.setAutoDefault(False)
        self.pb_load_1.setObjectName("pb_load_1")
        self.pb_load_2 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_load_2.setGeometry(QtCore.QRect(293, 9, 75, 26))
        self.pb_load_2.setAutoDefault(False)
        self.pb_load_2.setObjectName("pb_load_2")
        self.label_8 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_8.setGeometry(QtCore.QRect(9, 41, 44, 18))
        self.label_8.setObjectName("label_8")
        self.lbl_recipie = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_recipie.setGeometry(QtCore.QRect(197, 41, 34, 18))
        self.lbl_recipie.setObjectName("lbl_recipie")
        self.label_10 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_10.setGeometry(QtCore.QRect(9, 65, 70, 18))
        self.label_10.setObjectName("label_10")
        self.lbl_feed_total = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_feed_total.setGeometry(QtCore.QRect(197, 65, 25, 18))
        self.lbl_feed_total.setObjectName("lbl_feed_total")
        self.label_11 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_11.setGeometry(QtCore.QRect(293, 65, 65, 18))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.lbl_mix_count = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_mix_count.setGeometry(QtCore.QRect(375, 65, 25, 18))
        self.lbl_mix_count.setObjectName("lbl_mix_count")
        self.label_12 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_12.setGeometry(QtCore.QRect(9, 89, 37, 18))
        self.label_12.setObjectName("label_12")
        self.lbl_feed_total_2 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_feed_total_2.setGeometry(QtCore.QRect(197, 89, 25, 18))
        self.lbl_feed_total_2.setObjectName("lbl_feed_total_2")
        self.line_6 = QtWidgets.QFrame(DialogFeederManualMix)
        self.line_6.setGeometry(QtCore.QRect(9, 113, 661, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_4 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_4.setGeometry(QtCore.QRect(9, 122, 40, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_5.setGeometry(QtCore.QRect(9, 146, 33, 18))
        self.label_5.setObjectName("label_5")
        self.label_27 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_27.setGeometry(QtCore.QRect(228, 146, 16, 18))
        self.label_27.setObjectName("label_27")
        self.pb_read = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_read.setGeometry(QtCore.QRect(253, 146, 75, 26))
        self.pb_read.setAutoDefault(False)
        self.pb_read.setObjectName("pb_read")
        self.pb_zero = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_zero.setGeometry(QtCore.QRect(600, 145, 75, 26))
        self.pb_zero.setAutoDefault(False)
        self.pb_zero.setObjectName("pb_zero")
        self.label_26 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_26.setGeometry(QtCore.QRect(130, 147, 37, 18))
        self.label_26.setObjectName("label_26")
        self.le_fill_to = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_fill_to.setGeometry(QtCore.QRect(173, 145, 51, 24))
        self.le_fill_to.setObjectName("le_fill_to")
        self.label_28 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_28.setGeometry(QtCore.QRect(107, 147, 16, 18))
        self.label_28.setObjectName("label_28")
        self.pb_fill_1 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_fill_1.setGeometry(QtCore.QRect(334, 145, 75, 26))
        self.pb_fill_1.setAutoDefault(False)
        self.pb_fill_1.setObjectName("pb_fill_1")
        self.pb_drain = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_drain.setGeometry(QtCore.QRect(510, 144, 75, 26))
        self.pb_drain.setObjectName("pb_drain")
        self.line_4 = QtWidgets.QFrame(DialogFeederManualMix)
        self.line_4.setGeometry(QtCore.QRect(9, 180, 671, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_7 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 20, 18))
        self.label_7.setObjectName("label_7")
        self.pb_stir_n = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_stir_n.setGeometry(QtCore.QRect(60, 200, 75, 26))
        self.pb_stir_n.setAutoDefault(False)
        self.pb_stir_n.setObjectName("pb_stir_n")
        self.pb_stir_m = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_stir_m.setGeometry(QtCore.QRect(510, 200, 75, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_stir_m.sizePolicy().hasHeightForWidth())
        self.pb_stir_m.setSizePolicy(sizePolicy)
        self.pb_stir_m.setAutoDefault(False)
        self.pb_stir_m.setObjectName("pb_stir_m")
        self.line_3 = QtWidgets.QFrame(DialogFeederManualMix)
        self.line_3.setGeometry(QtCore.QRect(9, 228, 671, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_3 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_3.setGeometry(QtCore.QRect(10, 240, 88, 18))
        self.label_3.setObjectName("label_3")
        self.le_ml_1 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_1.setGeometry(QtCore.QRect(9, 265, 57, 24))
        self.le_ml_1.setObjectName("le_ml_1")
        self.label_18 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_18.setGeometry(QtCore.QRect(70, 264, 16, 18))
        self.label_18.setObjectName("label_18")
        self.lbl_added_1 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_1.setGeometry(QtCore.QRect(117, 264, 16, 18))
        self.lbl_added_1.setText("")
        self.lbl_added_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_1.setObjectName("lbl_added_1")
        self.pb_pump_1 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_1.setGeometry(QtCore.QRect(190, 264, 75, 26))
        self.pb_pump_1.setAutoDefault(False)
        self.pb_pump_1.setObjectName("pb_pump_1")
        self.le_ml_2 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_2.setGeometry(QtCore.QRect(9, 297, 57, 24))
        self.le_ml_2.setObjectName("le_ml_2")
        self.label_19 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_19.setGeometry(QtCore.QRect(70, 296, 16, 18))
        self.label_19.setObjectName("label_19")
        self.lbl_added_2 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_2.setGeometry(QtCore.QRect(117, 296, 16, 18))
        self.lbl_added_2.setText("")
        self.lbl_added_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_2.setObjectName("lbl_added_2")
        self.pb_pump_2 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_2.setGeometry(QtCore.QRect(190, 296, 75, 26))
        self.pb_pump_2.setAutoDefault(False)
        self.pb_pump_2.setObjectName("pb_pump_2")
        self.le_ml_3 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_3.setGeometry(QtCore.QRect(9, 329, 57, 24))
        self.le_ml_3.setObjectName("le_ml_3")
        self.label_20 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_20.setGeometry(QtCore.QRect(70, 328, 16, 18))
        self.label_20.setObjectName("label_20")
        self.lbl_added_3 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_3.setGeometry(QtCore.QRect(117, 328, 16, 18))
        self.lbl_added_3.setText("")
        self.lbl_added_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_3.setObjectName("lbl_added_3")
        self.pb_pump_3 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_3.setGeometry(QtCore.QRect(190, 328, 75, 26))
        self.pb_pump_3.setAutoDefault(False)
        self.pb_pump_3.setObjectName("pb_pump_3")
        self.le_ml_4 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_4.setGeometry(QtCore.QRect(9, 361, 57, 24))
        self.le_ml_4.setObjectName("le_ml_4")
        self.label_21 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_21.setGeometry(QtCore.QRect(70, 360, 16, 18))
        self.label_21.setObjectName("label_21")
        self.lbl_added_4 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_4.setGeometry(QtCore.QRect(117, 360, 16, 18))
        self.lbl_added_4.setText("")
        self.lbl_added_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_4.setObjectName("lbl_added_4")
        self.pb_pump_4 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_4.setGeometry(QtCore.QRect(190, 360, 75, 26))
        self.pb_pump_4.setAutoDefault(False)
        self.pb_pump_4.setObjectName("pb_pump_4")
        self.le_ml_5 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_5.setGeometry(QtCore.QRect(312, 261, 57, 24))
        self.le_ml_5.setObjectName("le_ml_5")
        self.label_22 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_22.setGeometry(QtCore.QRect(373, 260, 16, 18))
        self.label_22.setObjectName("label_22")
        self.lbl_added_5 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_5.setGeometry(QtCore.QRect(420, 260, 16, 18))
        self.lbl_added_5.setText("")
        self.lbl_added_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_5.setObjectName("lbl_added_5")
        self.pb_pump_5 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_5.setGeometry(QtCore.QRect(493, 260, 75, 26))
        self.pb_pump_5.setAutoDefault(False)
        self.pb_pump_5.setObjectName("pb_pump_5")
        self.le_ml_6 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_6.setGeometry(QtCore.QRect(312, 293, 57, 24))
        self.le_ml_6.setObjectName("le_ml_6")
        self.label_23 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_23.setGeometry(QtCore.QRect(373, 292, 16, 18))
        self.label_23.setObjectName("label_23")
        self.lbl_added_6 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_6.setGeometry(QtCore.QRect(420, 292, 16, 18))
        self.lbl_added_6.setText("")
        self.lbl_added_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_6.setObjectName("lbl_added_6")
        self.pb_pump_6 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_6.setGeometry(QtCore.QRect(493, 292, 75, 26))
        self.pb_pump_6.setAutoDefault(False)
        self.pb_pump_6.setObjectName("pb_pump_6")
        self.le_ml_7 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_7.setGeometry(QtCore.QRect(312, 325, 57, 24))
        self.le_ml_7.setObjectName("le_ml_7")
        self.label_24 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_24.setGeometry(QtCore.QRect(373, 324, 16, 18))
        self.label_24.setObjectName("label_24")
        self.lbl_added_7 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_7.setGeometry(QtCore.QRect(420, 324, 16, 18))
        self.lbl_added_7.setText("")
        self.lbl_added_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_7.setObjectName("lbl_added_7")
        self.pb_pump_7 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_7.setGeometry(QtCore.QRect(493, 324, 75, 26))
        self.pb_pump_7.setAutoDefault(False)
        self.pb_pump_7.setObjectName("pb_pump_7")
        self.le_ml_8 = QtWidgets.QLineEdit(DialogFeederManualMix)
        self.le_ml_8.setGeometry(QtCore.QRect(312, 357, 57, 24))
        self.le_ml_8.setObjectName("le_ml_8")
        self.label_25 = QtWidgets.QLabel(DialogFeederManualMix)
        self.label_25.setGeometry(QtCore.QRect(373, 356, 16, 18))
        self.label_25.setObjectName("label_25")
        self.lbl_added_8 = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_added_8.setGeometry(QtCore.QRect(420, 356, 16, 18))
        self.lbl_added_8.setText("")
        self.lbl_added_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_added_8.setObjectName("lbl_added_8")
        self.pb_pump_8 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_pump_8.setGeometry(QtCore.QRect(493, 356, 75, 26))
        self.pb_pump_8.setAutoDefault(False)
        self.pb_pump_8.setObjectName("pb_pump_8")
        self.line_2 = QtWidgets.QFrame(DialogFeederManualMix)
        self.line_2.setGeometry(QtCore.QRect(10, 390, 681, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.te_messages = QtWidgets.QTextEdit(DialogFeederManualMix)
        self.te_messages.setGeometry(QtCore.QRect(10, 500, 400, 131))
        self.te_messages.setObjectName("te_messages")
        self.pb_clear = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_clear.setGeometry(QtCore.QRect(600, 470, 75, 26))
        self.pb_clear.setAutoDefault(False)
        self.pb_clear.setObjectName("pb_clear")
        self.pb_stop = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_stop.setGeometry(QtCore.QRect(600, 430, 75, 26))
        self.pb_stop.setObjectName("pb_stop")
        self.pb_close = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_close.setGeometry(QtCore.QRect(600, 590, 75, 26))
        self.pb_close.setAutoDefault(False)
        self.pb_close.setObjectName("pb_close")
        self.le_tank_level = QtWidgets.QLabel(DialogFeederManualMix)
        self.le_tank_level.setGeometry(QtCore.QRect(50, 146, 51, 20))
        self.le_tank_level.setFrameShape(QtWidgets.QFrame.Box)
        self.le_tank_level.setText("")
        self.le_tank_level.setObjectName("le_tank_level")
        self.pb_fill_2 = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_fill_2.setGeometry(QtCore.QRect(418, 145, 75, 26))
        self.pb_fill_2.setAutoDefault(False)
        self.pb_fill_2.setObjectName("pb_fill_2")
        self.frm_v6 = QtWidgets.QFrame(DialogFeederManualMix)
        self.frm_v6.setGeometry(QtCore.QRect(90, 440, 91, 51))
        self.frm_v6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_v6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_v6.setObjectName("frm_v6")
        self.rb_v6_1 = QtWidgets.QRadioButton(self.frm_v6)
        self.rb_v6_1.setGeometry(QtCore.QRect(30, 0, 51, 21))
        self.rb_v6_1.setObjectName("rb_v6_1")
        self.rb_v6_2 = QtWidgets.QRadioButton(self.frm_v6)
        self.rb_v6_2.setGeometry(QtCore.QRect(31, 30, 51, 21))
        self.rb_v6_2.setObjectName("rb_v6_2")
        self.frm_v4 = QtWidgets.QFrame(DialogFeederManualMix)
        self.frm_v4.setGeometry(QtCore.QRect(10, 410, 91, 80))
        self.frm_v4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_v4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_v4.setObjectName("frm_v4")
        self.rb_v4_1 = QtWidgets.QRadioButton(self.frm_v4)
        self.rb_v4_1.setGeometry(QtCore.QRect(20, -3, 82, 21))
        self.rb_v4_1.setObjectName("rb_v4_1")
        self.rb_v4_2 = QtWidgets.QRadioButton(self.frm_v4)
        self.rb_v4_2.setGeometry(QtCore.QRect(20, 27, 82, 21))
        self.rb_v4_2.setObjectName("rb_v4_2")
        self.frm_v5 = QtWidgets.QFrame(DialogFeederManualMix)
        self.frm_v5.setGeometry(QtCore.QRect(110, 407, 191, 21))
        self.frm_v5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_v5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_v5.setObjectName("frm_v5")
        self.rb_v5_1 = QtWidgets.QRadioButton(self.frm_v5)
        self.rb_v5_1.setGeometry(QtCore.QRect(10, -3, 82, 21))
        self.rb_v5_1.setObjectName("rb_v5_1")
        self.rb_v5_2 = QtWidgets.QRadioButton(self.frm_v5)
        self.rb_v5_2.setGeometry(QtCore.QRect(100, -1, 82, 21))
        self.rb_v5_2.setObjectName("rb_v5_2")
        self.frm_v7 = QtWidgets.QFrame(DialogFeederManualMix)
        self.frm_v7.setGeometry(QtCore.QRect(200, 430, 81, 61))
        self.frm_v7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_v7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_v7.setObjectName("frm_v7")
        self.rb_v7_1 = QtWidgets.QRadioButton(self.frm_v7)
        self.rb_v7_1.setGeometry(QtCore.QRect(10, 10, 61, 17))
        self.rb_v7_1.setObjectName("rb_v7_1")
        self.rb_v7_2 = QtWidgets.QRadioButton(self.frm_v7)
        self.rb_v7_2.setGeometry(QtCore.QRect(10, 40, 61, 17))
        self.rb_v7_2.setObjectName("rb_v7_2")
        self.pb_add_all = QtWidgets.QPushButton(DialogFeederManualMix)
        self.pb_add_all.setGeometry(QtCore.QRect(600, 360, 75, 23))
        self.pb_add_all.setObjectName("pb_add_all")
        self.lbl_status = QtWidgets.QLabel(DialogFeederManualMix)
        self.lbl_status.setGeometry(QtCore.QRect(190, 204, 261, 16))
        self.lbl_status.setText("")
        self.lbl_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_status.setObjectName("lbl_status")
        self.te_recipe = QtWidgets.QTextEdit(DialogFeederManualMix)
        self.te_recipe.setGeometry(QtCore.QRect(420, 0, 241, 121))
        self.te_recipe.setObjectName("te_recipe")

        self.retranslateUi(DialogFeederManualMix)
        QtCore.QMetaObject.connectSlotsByName(DialogFeederManualMix)

    def retranslateUi(self, DialogFeederManualMix):
        _translate = QtCore.QCoreApplication.translate
        DialogFeederManualMix.setWindowTitle(_translate("DialogFeederManualMix", "Feeder Manual Mix"))
        self.label_6.setText(_translate("DialogFeederManualMix", "Load Recipie"))
        self.pb_load_1.setText(_translate("DialogFeederManualMix", "Area 1"))
        self.pb_load_2.setText(_translate("DialogFeederManualMix", "Area 2"))
        self.label_8.setText(_translate("DialogFeederManualMix", "Recipie"))
        self.lbl_recipie.setText(_translate("DialogFeederManualMix", "None"))
        self.label_10.setText(_translate("DialogFeederManualMix", "Feed Total"))
        self.lbl_feed_total.setText(_translate("DialogFeederManualMix", "N/A"))
        self.label_11.setText(_translate("DialogFeederManualMix", "Mix Count"))
        self.lbl_mix_count.setText(_translate("DialogFeederManualMix", "N/A"))
        self.label_12.setText(_translate("DialogFeederManualMix", "Mixes"))
        self.lbl_feed_total_2.setText(_translate("DialogFeederManualMix", "N/A"))
        self.label_4.setText(_translate("DialogFeederManualMix", "Water"))
        self.label_5.setText(_translate("DialogFeederManualMix", "Level"))
        self.label_27.setText(_translate("DialogFeederManualMix", "L"))
        self.pb_read.setText(_translate("DialogFeederManualMix", "Read"))
        self.pb_zero.setText(_translate("DialogFeederManualMix", "Zero"))
        self.label_26.setText(_translate("DialogFeederManualMix", "Fill To"))
        self.label_28.setText(_translate("DialogFeederManualMix", "L"))
        self.pb_fill_1.setText(_translate("DialogFeederManualMix", "Tank 1"))
        self.pb_drain.setText(_translate("DialogFeederManualMix", "D"))
        self.label_7.setText(_translate("DialogFeederManualMix", "Stir"))
        self.pb_stir_n.setText(_translate("DialogFeederManualMix", "Nutrients"))
        self.pb_stir_m.setText(_translate("DialogFeederManualMix", "Mix"))
        self.label_3.setText(_translate("DialogFeederManualMix", "Add Nutrients"))
        self.label_18.setText(_translate("DialogFeederManualMix", "ml"))
        self.pb_pump_1.setText(_translate("DialogFeederManualMix", "1"))
        self.label_19.setText(_translate("DialogFeederManualMix", "ml"))
        self.pb_pump_2.setText(_translate("DialogFeederManualMix", "2"))
        self.label_20.setText(_translate("DialogFeederManualMix", "ml"))
        self.pb_pump_3.setText(_translate("DialogFeederManualMix", "3"))
        self.label_21.setText(_translate("DialogFeederManualMix", "ml"))
        self.pb_pump_4.setText(_translate("DialogFeederManualMix", "4"))
        self.label_22.setText(_translate("DialogFeederManualMix", "ml"))
        self.pb_pump_5.setText(_translate("DialogFeederManualMix", "5"))
        self.label_23.setText(_translate("DialogFeederManualMix", "ml"))
        self.pb_pump_6.setText(_translate("DialogFeederManualMix", "6"))
        self.label_24.setText(_translate("DialogFeederManualMix", "ml"))
        self.pb_pump_7.setText(_translate("DialogFeederManualMix", "7"))
        self.label_25.setText(_translate("DialogFeederManualMix", "ml"))
        self.pb_pump_8.setText(_translate("DialogFeederManualMix", "8"))
        self.pb_clear.setText(_translate("DialogFeederManualMix", "Clear"))
        self.pb_stop.setText(_translate("DialogFeederManualMix", "Stop"))
        self.pb_close.setText(_translate("DialogFeederManualMix", "Close"))
        self.pb_fill_2.setText(_translate("DialogFeederManualMix", "Tank 2"))
        self.rb_v6_1.setText(_translate("DialogFeederManualMix", "Feed"))
        self.rb_v6_2.setText(_translate("DialogFeederManualMix", "Flush"))
        self.rb_v4_1.setText(_translate("DialogFeederManualMix", "Auto"))
        self.rb_v4_2.setText(_translate("DialogFeederManualMix", "Manual"))
        self.rb_v5_1.setText(_translate("DialogFeederManualMix", "Area 1"))
        self.rb_v5_2.setText(_translate("DialogFeederManualMix", "Area 2"))
        self.rb_v7_1.setText(_translate("DialogFeederManualMix", "Feed"))
        self.rb_v7_2.setText(_translate("DialogFeederManualMix", "Flush"))
        self.pb_add_all.setText(_translate("DialogFeederManualMix", "Add All"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogFeederManualMix = QtWidgets.QDialog()
    ui = Ui_DialogFeederManualMix()
    ui.setupUi(DialogFeederManualMix)
    DialogFeederManualMix.show()
    sys.exit(app.exec_())

