# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogFeedRecipes.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogFeedRecipes(object):
    def setupUi(self, DialogFeedRecipes):
        DialogFeedRecipes.setObjectName("DialogFeedRecipes")
        DialogFeedRecipes.resize(392, 313)
        font = QtGui.QFont()
        font.setPointSize(10)
        DialogFeedRecipes.setFont(font)
        self.label_5 = QtWidgets.QLabel(DialogFeedRecipes)
        self.label_5.setGeometry(QtCore.QRect(350, 30, 21, 16))
        self.label_5.setObjectName("label_5")
        self.tw_recipe = QtWidgets.QTableWidget(DialogFeedRecipes)
        self.tw_recipe.setGeometry(QtCore.QRect(10, 80, 181, 221))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tw_recipe.setFont(font)
        self.tw_recipe.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_recipe.setAlternatingRowColors(True)
        self.tw_recipe.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_recipe.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_recipe.setObjectName("tw_recipe")
        self.tw_recipe.setColumnCount(0)
        self.tw_recipe.setRowCount(0)
        self.tw_recipe.verticalHeader().setVisible(False)
        self.pb_remove_item = QtWidgets.QPushButton(DialogFeedRecipes)
        self.pb_remove_item.setGeometry(QtCore.QRect(160, 58, 31, 23))
        self.pb_remove_item.setObjectName("pb_remove_item")
        self.label = QtWidgets.QLabel(DialogFeedRecipes)
        self.label.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.label.setObjectName("label")
        self.le_id = QtWidgets.QLineEdit(DialogFeedRecipes)
        self.le_id.setGeometry(QtCore.QRect(340, 50, 31, 20))
        self.le_id.setMouseTracking(False)
        self.le_id.setReadOnly(True)
        self.le_id.setObjectName("le_id")
        self.cb_recipes = QtWidgets.QComboBox(DialogFeedRecipes)
        self.cb_recipes.setGeometry(QtCore.QRect(80, 20, 241, 22))
        self.cb_recipes.setEditable(False)
        self.cb_recipes.setObjectName("cb_recipes")
        self.label_2 = QtWidgets.QLabel(DialogFeedRecipes)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 101, 21))
        self.label_2.setObjectName("label_2")
        self.pb_add_item = QtWidgets.QPushButton(DialogFeedRecipes)
        self.pb_add_item.setGeometry(QtCore.QRect(130, 58, 31, 23))
        self.pb_add_item.setObjectName("pb_add_item")
        self.pb_close = QtWidgets.QPushButton(DialogFeedRecipes)
        self.pb_close.setGeometry(QtCore.QRect(294, 280, 75, 23))
        self.pb_close.setObjectName("pb_close")
        self.te_info = QtWidgets.QTextEdit(DialogFeedRecipes)
        self.te_info.setGeometry(QtCore.QRect(204, 79, 171, 71))
        # self.te_info.setReadOnly(True)
        self.te_info.setObjectName("te_info")
        self.label_8 = QtWidgets.QLabel(DialogFeedRecipes)
        self.label_8.setGeometry(QtCore.QRect(200, 60, 71, 20))
        self.label_8.setObjectName("label_8")
        self.frm_edit = QtWidgets.QFrame(DialogFeedRecipes)
        self.frm_edit.setEnabled(False)
        self.frm_edit.setGeometry(QtCore.QRect(195, 160, 183, 101))
        self.frm_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.frm_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_edit.setObjectName("frm_edit")
        self.cb_nutrient = QtWidgets.QComboBox(self.frm_edit)
        self.cb_nutrient.setGeometry(QtCore.QRect(6, 10, 141, 22))
        self.cb_nutrient.setObjectName("cb_nutrient")
        self.pb_open = QtWidgets.QPushButton(self.frm_edit)
        self.pb_open.setGeometry(QtCore.QRect(145, 9, 31, 24))
        self.pb_open.setObjectName("pb_open")
        self.label_7 = QtWidgets.QLabel(self.frm_edit)
        self.label_7.setGeometry(QtCore.QRect(100, 43, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.frm_edit)
        self.label_6.setGeometry(QtCore.QRect(10, 41, 41, 16))
        self.label_6.setObjectName("label_6")
        self.le_frequency = QtWidgets.QLineEdit(self.frm_edit)
        self.le_frequency.setGeometry(QtCore.QRect(130, 40, 31, 20))
        self.le_frequency.setText("")
        self.le_frequency.setReadOnly(True)
        self.le_frequency.setObjectName("le_frequency")
        self.le_mls = QtWidgets.QLineEdit(self.frm_edit)
        self.le_mls.setGeometry(QtCore.QRect(50, 40, 31, 20))
        self.le_mls.setObjectName("le_mls")
        self.pb_save = QtWidgets.QPushButton(self.frm_edit)
        self.pb_save.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.pb_save.setObjectName("pb_save")
        self.pb_save_as = QtWidgets.QPushButton(self.frm_edit)
        self.pb_save_as.setGeometry(QtCore.QRect(100, 70, 75, 23))
        self.pb_save_as.setObjectName("pb_save_as")

        self.retranslateUi(DialogFeedRecipes)
        QtCore.QMetaObject.connectSlotsByName(DialogFeedRecipes)

    def retranslateUi(self, DialogFeedRecipes):
        _translate = QtCore.QCoreApplication.translate
        DialogFeedRecipes.setWindowTitle(_translate("DialogFeedRecipes", "Feed Recipes"))
        self.label_5.setText(_translate("DialogFeedRecipes", "ID"))
        self.pb_remove_item.setText(_translate("DialogFeedRecipes", "-"))
        self.label.setText(_translate("DialogFeedRecipes", "Recipe"))
        self.label_2.setText(_translate("DialogFeedRecipes", "Recipe Items"))
        self.pb_add_item.setText(_translate("DialogFeedRecipes", "+"))
        self.pb_close.setText(_translate("DialogFeedRecipes", "Close"))
        self.label_8.setText(_translate("DialogFeedRecipes", "Description"))
        self.pb_open.setText(_translate("DialogFeedRecipes", "..."))
        self.label_7.setText(_translate("DialogFeedRecipes", "Freq"))
        self.label_6.setText(_translate("DialogFeedRecipes", "mls/L"))
        self.pb_save.setText(_translate("DialogFeedRecipes", "Save"))
        self.pb_save_as.setText(_translate("DialogFeedRecipes", "Save As"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogFeedRecipes = QtWidgets.QWidget()
    ui = Ui_DialogFeedRecipes()
    ui.setupUi(DialogFeedRecipes)
    DialogFeedRecipes.show()
    sys.exit(app.exec_())

