# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogSensorSettings.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogSensorSettings(object):
    def setupUi(self, DialogSensorSettings):
        DialogSensorSettings.setObjectName("DialogSensorSettings")
        DialogSensorSettings.resize(257, 307)
        font = QtGui.QFont()
        font.setPointSize(11)
        DialogSensorSettings.setFont(font)
        self.pb_close = QtWidgets.QPushButton(DialogSensorSettings)
        self.pb_close.setGeometry(QtCore.QRect(160, 270, 75, 23))
        self.pb_close.setObjectName("pb_close")
        self.label_6 = QtWidgets.QLabel(DialogSensorSettings)
        self.label_6.setGeometry(QtCore.QRect(90, 110, 59, 18))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(DialogSensorSettings)
        self.label_7.setGeometry(QtCore.QRect(160, 110, 59, 18))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(DialogSensorSettings)
        self.label_8.setGeometry(QtCore.QRect(20, 110, 59, 18))
        self.label_8.setObjectName("label_8")
        self.lbl_high = QtWidgets.QLabel(DialogSensorSettings)
        self.lbl_high.setGeometry(QtCore.QRect(150, 170, 51, 20))
        self.lbl_high.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_high.setObjectName("lbl_high")
        self.lbl_set = QtWidgets.QLabel(DialogSensorSettings)
        self.lbl_set.setGeometry(QtCore.QRect(80, 170, 51, 20))
        self.lbl_set.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_set.setObjectName("lbl_set")
        self.lbl_low = QtWidgets.QLabel(DialogSensorSettings)
        self.lbl_low.setGeometry(QtCore.QRect(10, 170, 51, 20))
        self.lbl_low.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_low.setObjectName("lbl_low")
        self.pb_reset = QtWidgets.QPushButton(DialogSensorSettings)
        self.pb_reset.setGeometry(QtCore.QRect(210, 140, 31, 23))
        self.pb_reset.setObjectName("pb_reset")
        self.lbl_name = QtWidgets.QLabel(DialogSensorSettings)
        self.lbl_name.setGeometry(QtCore.QRect(10, 10, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name.setFont(font)
        self.lbl_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_name.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_connections = QtWidgets.QLabel(DialogSensorSettings)
        self.lbl_connections.setGeometry(QtCore.QRect(10, 220, 241, 41))
        self.lbl_connections.setText("")
        self.lbl_connections.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_connections.setObjectName("lbl_connections")
        self.label_9 = QtWidgets.QLabel(DialogSensorSettings)
        self.label_9.setGeometry(QtCore.QRect(10, 200, 101, 18))
        self.label_9.setObjectName("label_9")
        self.pb_set_fan = QtWidgets.QPushButton(DialogSensorSettings)
        self.pb_set_fan.setGeometry(QtCore.QRect(20, 270, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pb_set_fan.setFont(font)
        self.pb_set_fan.setObjectName("pb_set_fan")
        self.lbl_area = QtWidgets.QLabel(DialogSensorSettings)
        self.lbl_area.setGeometry(QtCore.QRect(10, 40, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_area.setFont(font)
        self.lbl_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_area.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_area.setObjectName("lbl_area")
        self.le_high = QtWidgets.QLineEdit(DialogSensorSettings)
        self.le_high.setGeometry(QtCore.QRect(150, 140, 51, 20))
        self.le_high.setAlignment(QtCore.Qt.AlignCenter)
        self.le_high.setObjectName("le_high")
        self.le_set = QtWidgets.QLineEdit(DialogSensorSettings)
        self.le_set.setGeometry(QtCore.QRect(78, 140, 57, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_set.setFont(font)
        self.le_set.setText("")
        self.le_set.setFrame(True)
        self.le_set.setAlignment(QtCore.Qt.AlignCenter)
        self.le_set.setObjectName("le_set")
        self.le_low = QtWidgets.QLineEdit(DialogSensorSettings)
        self.le_low.setGeometry(QtCore.QRect(10, 140, 51, 20))
        self.le_low.setAlignment(QtCore.Qt.AlignCenter)
        self.le_low.setObjectName("le_low")
        self.label_10 = QtWidgets.QLabel(DialogSensorSettings)
        self.label_10.setGeometry(QtCore.QRect(10, 73, 71, 18))
        self.label_10.setObjectName("label_10")
        self.pb_switch = QtWidgets.QPushButton(DialogSensorSettings)
        self.pb_switch.setGeometry(QtCore.QRect(80, 70, 75, 26))
        self.pb_switch.setObjectName("pb_switch")

        self.retranslateUi(DialogSensorSettings)
        QtCore.QMetaObject.connectSlotsByName(DialogSensorSettings)

    def retranslateUi(self, DialogSensorSettings):
        _translate = QtCore.QCoreApplication.translate
        DialogSensorSettings.setWindowTitle(_translate("DialogSensorSettings", "Sensor Settings"))
        self.pb_close.setText(_translate("DialogSensorSettings", "Close"))
        self.label_6.setText(_translate("DialogSensorSettings", "Set"))
        self.label_7.setText(_translate("DialogSensorSettings", "High"))
        self.label_8.setText(_translate("DialogSensorSettings", "Low"))
        self.lbl_high.setText(_translate("DialogSensorSettings", "0"))
        self.lbl_set.setText(_translate("DialogSensorSettings", "0"))
        self.lbl_low.setText(_translate("DialogSensorSettings", "0"))
        self.pb_reset.setText(_translate("DialogSensorSettings", "R"))
        self.lbl_name.setText(_translate("DialogSensorSettings", "Sensor"))
        self.label_9.setText(_translate("DialogSensorSettings", "Connections"))
        self.pb_set_fan.setText(_translate("DialogSensorSettings", "Set as Fan"))
        self.lbl_area.setText(_translate("DialogSensorSettings", "1"))
        self.label_10.setText(_translate("DialogSensorSettings", "Switch to"))
        self.pb_switch.setText(_translate("DialogSensorSettings", "Night"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogSensorSettings = QtWidgets.QWidget()
    ui = Ui_DialogSensorSettings()
    ui.setupUi(DialogSensorSettings)
    DialogSensorSettings.show()
    sys.exit(app.exec_())

