# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogIOVC.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_IO_VC(object):
    def setupUi(self, Dialog_IO_VC):
        Dialog_IO_VC.setObjectName("Dialog_IO_VC")
        Dialog_IO_VC.resize(516, 297)
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog_IO_VC.setFont(font)
        self.frame = QtWidgets.QFrame(Dialog_IO_VC)
        self.frame.setGeometry(QtCore.QRect(10, 30, 241, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label.setObjectName("label")
        self.le_out_s_1_0 = QtWidgets.QLineEdit(self.frame)
        self.le_out_s_1_0.setGeometry(QtCore.QRect(70, 20, 41, 20))
        self.le_out_s_1_0.setReadOnly(True)
        self.le_out_s_1_0.setObjectName("le_out_s_1_0")
        self.le_out_a_1_0 = QtWidgets.QLineEdit(self.frame)
        self.le_out_a_1_0.setGeometry(QtCore.QRect(120, 20, 41, 20))
        self.le_out_a_1_0.setReadOnly(True)
        self.le_out_a_1_0.setObjectName("le_out_a_1_0")
        self.pb_fix_1_0 = QtWidgets.QPushButton(self.frame)
        self.pb_fix_1_0.setEnabled(False)
        self.pb_fix_1_0.setGeometry(QtCore.QRect(180, 20, 51, 23))
        self.pb_fix_1_0.setObjectName("pb_fix_1_0")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.label_2.setObjectName("label_2")
        self.le_out_s_1_1 = QtWidgets.QLineEdit(self.frame)
        self.le_out_s_1_1.setGeometry(QtCore.QRect(70, 50, 41, 20))
        self.le_out_s_1_1.setReadOnly(True)
        self.le_out_s_1_1.setObjectName("le_out_s_1_1")
        self.le_out_a_1_1 = QtWidgets.QLineEdit(self.frame)
        self.le_out_a_1_1.setGeometry(QtCore.QRect(120, 50, 41, 20))
        self.le_out_a_1_1.setReadOnly(True)
        self.le_out_a_1_1.setObjectName("le_out_a_1_1")
        self.le_out_s_1_2 = QtWidgets.QLineEdit(self.frame)
        self.le_out_s_1_2.setGeometry(QtCore.QRect(70, 80, 41, 20))
        self.le_out_s_1_2.setReadOnly(True)
        self.le_out_s_1_2.setObjectName("le_out_s_1_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.label_3.setObjectName("label_3")
        self.le_out_a_1_2 = QtWidgets.QLineEdit(self.frame)
        self.le_out_a_1_2.setGeometry(QtCore.QRect(120, 80, 41, 20))
        self.le_out_a_1_2.setReadOnly(True)
        self.le_out_a_1_2.setObjectName("le_out_a_1_2")
        self.le_out_s_1_3 = QtWidgets.QLineEdit(self.frame)
        self.le_out_s_1_3.setGeometry(QtCore.QRect(70, 110, 41, 20))
        self.le_out_s_1_3.setReadOnly(True)
        self.le_out_s_1_3.setObjectName("le_out_s_1_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 61, 21))
        self.label_4.setObjectName("label_4")
        self.le_out_a_1_3 = QtWidgets.QLineEdit(self.frame)
        self.le_out_a_1_3.setGeometry(QtCore.QRect(120, 110, 41, 20))
        self.le_out_a_1_3.setReadOnly(True)
        self.le_out_a_1_3.setObjectName("le_out_a_1_3")
        self.le_out_s_1_4 = QtWidgets.QLineEdit(self.frame)
        self.le_out_s_1_4.setGeometry(QtCore.QRect(70, 140, 41, 20))
        self.le_out_s_1_4.setReadOnly(True)
        self.le_out_s_1_4.setObjectName("le_out_s_1_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 61, 21))
        self.label_5.setObjectName("label_5")
        self.le_out_a_1_4 = QtWidgets.QLineEdit(self.frame)
        self.le_out_a_1_4.setGeometry(QtCore.QRect(120, 140, 41, 20))
        self.le_out_a_1_4.setReadOnly(True)
        self.le_out_a_1_4.setObjectName("le_out_a_1_4")
        self.pb_fix_1_1 = QtWidgets.QPushButton(self.frame)
        self.pb_fix_1_1.setEnabled(False)
        self.pb_fix_1_1.setGeometry(QtCore.QRect(180, 50, 51, 23))
        self.pb_fix_1_1.setObjectName("pb_fix_1_1")
        self.pb_fix_1_2 = QtWidgets.QPushButton(self.frame)
        self.pb_fix_1_2.setEnabled(False)
        self.pb_fix_1_2.setGeometry(QtCore.QRect(180, 80, 51, 23))
        self.pb_fix_1_2.setObjectName("pb_fix_1_2")
        self.pb_fix_1_3 = QtWidgets.QPushButton(self.frame)
        self.pb_fix_1_3.setEnabled(False)
        self.pb_fix_1_3.setGeometry(QtCore.QRect(180, 110, 51, 23))
        self.pb_fix_1_3.setObjectName("pb_fix_1_3")
        self.pb_fix_1_4 = QtWidgets.QPushButton(self.frame)
        self.pb_fix_1_4.setEnabled(False)
        self.pb_fix_1_4.setGeometry(QtCore.QRect(180, 140, 51, 23))
        self.pb_fix_1_4.setObjectName("pb_fix_1_4")
        self.frame_2 = QtWidgets.QFrame(Dialog_IO_VC)
        self.frame_2.setGeometry(QtCore.QRect(260, 30, 241, 221))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_6.setObjectName("label_6")
        self.le_out_s_2_0 = QtWidgets.QLineEdit(self.frame_2)
        self.le_out_s_2_0.setGeometry(QtCore.QRect(70, 20, 41, 20))
        self.le_out_s_2_0.setReadOnly(True)
        self.le_out_s_2_0.setObjectName("le_out_s_2_0")
        self.le_out_a_2_0 = QtWidgets.QLineEdit(self.frame_2)
        self.le_out_a_2_0.setGeometry(QtCore.QRect(120, 20, 41, 20))
        self.le_out_a_2_0.setReadOnly(True)
        self.le_out_a_2_0.setObjectName("le_out_a_2_0")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(10, 110, 61, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 140, 61, 21))
        self.label_10.setObjectName("label_10")
        self.le_out_s_2_1 = QtWidgets.QLineEdit(self.frame_2)
        self.le_out_s_2_1.setGeometry(QtCore.QRect(70, 50, 41, 20))
        self.le_out_s_2_1.setReadOnly(True)
        self.le_out_s_2_1.setObjectName("le_out_s_2_1")
        self.le_out_a_2_1 = QtWidgets.QLineEdit(self.frame_2)
        self.le_out_a_2_1.setGeometry(QtCore.QRect(120, 50, 41, 20))
        self.le_out_a_2_1.setReadOnly(True)
        self.le_out_a_2_1.setObjectName("le_out_a_2_1")
        self.le_out_s_2_2 = QtWidgets.QLineEdit(self.frame_2)
        self.le_out_s_2_2.setGeometry(QtCore.QRect(70, 80, 41, 20))
        self.le_out_s_2_2.setReadOnly(True)
        self.le_out_s_2_2.setObjectName("le_out_s_2_2")
        self.le_out_a_2_2 = QtWidgets.QLineEdit(self.frame_2)
        self.le_out_a_2_2.setGeometry(QtCore.QRect(120, 80, 41, 20))
        self.le_out_a_2_2.setReadOnly(True)
        self.le_out_a_2_2.setObjectName("le_out_a_2_2")
        self.le_out_s_2_3 = QtWidgets.QLineEdit(self.frame_2)
        self.le_out_s_2_3.setGeometry(QtCore.QRect(70, 110, 41, 20))
        self.le_out_s_2_3.setReadOnly(True)
        self.le_out_s_2_3.setObjectName("le_out_s_2_3")
        self.le_out_a_2_3 = QtWidgets.QLineEdit(self.frame_2)
        self.le_out_a_2_3.setGeometry(QtCore.QRect(120, 110, 41, 20))
        self.le_out_a_2_3.setReadOnly(True)
        self.le_out_a_2_3.setObjectName("le_out_a_2_3")
        self.le_out_s_2_4 = QtWidgets.QLineEdit(self.frame_2)
        self.le_out_s_2_4.setGeometry(QtCore.QRect(70, 140, 41, 20))
        self.le_out_s_2_4.setReadOnly(True)
        self.le_out_s_2_4.setObjectName("le_out_s_2_4")
        self.le_out_a_2_4 = QtWidgets.QLineEdit(self.frame_2)
        self.le_out_a_2_4.setGeometry(QtCore.QRect(120, 140, 41, 20))
        self.le_out_a_2_4.setReadOnly(True)
        self.le_out_a_2_4.setObjectName("le_out_a_2_4")
        self.pb_fix_2_0 = QtWidgets.QPushButton(self.frame_2)
        self.pb_fix_2_0.setEnabled(False)
        self.pb_fix_2_0.setGeometry(QtCore.QRect(170, 20, 51, 23))
        self.pb_fix_2_0.setObjectName("pb_fix_2_0")
        self.pb_fix_2_1 = QtWidgets.QPushButton(self.frame_2)
        self.pb_fix_2_1.setEnabled(False)
        self.pb_fix_2_1.setGeometry(QtCore.QRect(170, 50, 51, 23))
        self.pb_fix_2_1.setObjectName("pb_fix_2_1")
        self.pb_fix_2_2 = QtWidgets.QPushButton(self.frame_2)
        self.pb_fix_2_2.setEnabled(False)
        self.pb_fix_2_2.setGeometry(QtCore.QRect(170, 80, 51, 23))
        self.pb_fix_2_2.setObjectName("pb_fix_2_2")
        self.pb_fix_2_3 = QtWidgets.QPushButton(self.frame_2)
        self.pb_fix_2_3.setEnabled(False)
        self.pb_fix_2_3.setGeometry(QtCore.QRect(170, 110, 51, 23))
        self.pb_fix_2_3.setObjectName("pb_fix_2_3")
        self.pb_fix_2_4 = QtWidgets.QPushButton(self.frame_2)
        self.pb_fix_2_4.setEnabled(False)
        self.pb_fix_2_4.setGeometry(QtCore.QRect(170, 140, 51, 23))
        self.pb_fix_2_4.setObjectName("pb_fix_2_4")
        self.pb_close = QtWidgets.QPushButton(Dialog_IO_VC)
        self.pb_close.setGeometry(QtCore.QRect(410, 260, 75, 23))
        self.pb_close.setObjectName("pb_close")
        self.pb_request = QtWidgets.QPushButton(Dialog_IO_VC)
        self.pb_request.setGeometry(QtCore.QRect(20, 260, 91, 27))
        self.pb_request.setObjectName("pb_request")

        self.retranslateUi(Dialog_IO_VC)
        QtCore.QMetaObject.connectSlotsByName(Dialog_IO_VC)

    def retranslateUi(self, Dialog_IO_VC):
        _translate = QtCore.QCoreApplication.translate
        Dialog_IO_VC.setWindowTitle(_translate("Dialog_IO_VC", "I/O VC"))
        self.label.setText(_translate("Dialog_IO_VC", "Light"))
        self.pb_fix_1_0.setText(_translate("Dialog_IO_VC", "Fix"))
        self.label_2.setText(_translate("Dialog_IO_VC", "Heater 1"))
        self.label_3.setText(_translate("Dialog_IO_VC", "Heater 2"))
        self.label_4.setText(_translate("Dialog_IO_VC", "Aux"))
        self.label_5.setText(_translate("Dialog_IO_VC", "Socket"))
        self.pb_fix_1_1.setText(_translate("Dialog_IO_VC", "Fix"))
        self.pb_fix_1_2.setText(_translate("Dialog_IO_VC", "Fix"))
        self.pb_fix_1_3.setText(_translate("Dialog_IO_VC", "Fix"))
        self.pb_fix_1_4.setText(_translate("Dialog_IO_VC", "Fix"))
        self.label_6.setText(_translate("Dialog_IO_VC", "Light"))
        self.label_7.setText(_translate("Dialog_IO_VC", "Heater 1"))
        self.label_8.setText(_translate("Dialog_IO_VC", "Heater 2"))
        self.label_9.setText(_translate("Dialog_IO_VC", "Aux"))
        self.label_10.setText(_translate("Dialog_IO_VC", "Socket"))
        self.pb_fix_2_0.setText(_translate("Dialog_IO_VC", "Fix"))
        self.pb_fix_2_1.setText(_translate("Dialog_IO_VC", "Fix"))
        self.pb_fix_2_2.setText(_translate("Dialog_IO_VC", "Fix"))
        self.pb_fix_2_3.setText(_translate("Dialog_IO_VC", "Fix"))
        self.pb_fix_2_4.setText(_translate("Dialog_IO_VC", "Fix"))
        self.pb_close.setText(_translate("Dialog_IO_VC", "Close"))
        self.pb_request.setText(_translate("Dialog_IO_VC", "Request"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_IO_VC = QtWidgets.QWidget()
    ui = Ui_Dialog_IO_VC()
    ui.setupUi(Dialog_IO_VC)
    Dialog_IO_VC.show()
    sys.exit(app.exec_())

