# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogStrains.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogStrains(object):
    def setupUi(self, DialogStrains):
        DialogStrains.setObjectName("DialogStrains")
        DialogStrains.resize(884, 769)
        font = QtGui.QFont()
        font.setPointSize(11)
        DialogStrains.setFont(font)
        self.pb_close = QtWidgets.QPushButton(DialogStrains)
        self.pb_close.setGeometry(QtCore.QRect(691, 734, 75, 26))
        self.pb_close.setAutoDefault(False)
        self.pb_close.setObjectName("pb_close")
        self.lw_strains = QtWidgets.QListWidget(DialogStrains)
        self.lw_strains.setGeometry(QtCore.QRect(9, 70, 297, 691))
        self.lw_strains.setMaximumSize(QtCore.QSize(297, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lw_strains.setFont(font)
        self.lw_strains.setAlternatingRowColors(True)
        self.lw_strains.setObjectName("lw_strains")
        self.pb_save = QtWidgets.QPushButton(DialogStrains)
        self.pb_save.setEnabled(False)
        self.pb_save.setGeometry(QtCore.QRect(502, 734, 75, 26))
        self.pb_save.setObjectName("pb_save")
        self.pb_new = QtWidgets.QPushButton(DialogStrains)
        self.pb_new.setGeometry(QtCore.QRect(312, 734, 75, 26))
        self.pb_new.setAutoDefault(False)
        self.pb_new.setObjectName("pb_new")
        self.label_14 = QtWidgets.QLabel(DialogStrains)
        self.label_14.setGeometry(QtCore.QRect(9, 9, 43, 18))
        self.label_14.setObjectName("label_14")
        self.frame = QtWidgets.QFrame(DialogStrains)
        self.frame.setGeometry(QtCore.QRect(312, 33, 563, 695))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.le_sativa = QtWidgets.QLineEdit(self.frame)
        self.le_sativa.setGeometry(QtCore.QRect(100, 70, 64, 24))
        self.le_sativa.setObjectName("le_sativa")
        self.te_info = QtWidgets.QTextEdit(self.frame)
        self.te_info.setGeometry(QtCore.QRect(66, 347, 481, 117))
        self.te_info.setObjectName("te_info")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(9, 470, 38, 18))
        self.label_12.setObjectName("label_12")
        self.le_dur_min = QtWidgets.QLineEdit(self.frame)
        self.le_dur_min.setGeometry(QtCore.QRect(356, 10, 64, 24))
        self.le_dur_min.setObjectName("le_dur_min")
        self.le_height = QtWidgets.QLineEdit(self.frame)
        self.le_height.setGeometry(QtCore.QRect(414, 40, 131, 24))
        self.le_height.setObjectName("le_height")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(9, 70, 85, 18))
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(9, 347, 27, 18))
        self.label_11.setObjectName("label_11")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(258, 10, 93, 18))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(520, 10, 31, 18))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(360, 40, 41, 18))
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(170, 70, 39, 18))
        self.label_6.setObjectName("label_6")
        self.le_yeild = QtWidgets.QLineEdit(self.frame)
        self.le_yeild.setGeometry(QtCore.QRect(378, 70, 167, 24))
        self.le_yeild.setObjectName("le_yeild")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(9, 230, 38, 18))
        self.label_9.setObjectName("label_9")
        self.le_name = QtWidgets.QLineEdit(self.frame)
        self.le_name.setGeometry(QtCore.QRect(66, 10, 181, 24))
        self.le_name.setObjectName("le_name")
        self.le_dur_max = QtWidgets.QLineEdit(self.frame)
        self.le_dur_max.setGeometry(QtCore.QRect(450, 10, 64, 24))
        self.le_dur_max.setObjectName("le_dur_max")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(9, 150, 47, 18))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(308, 70, 30, 18))
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(9, 40, 51, 18))
        self.label_13.setObjectName("label_13")
        self.le_breeder = QtWidgets.QLineEdit(self.frame)
        self.le_breeder.setGeometry(QtCore.QRect(66, 40, 181, 24))
        self.le_breeder.setObjectName("le_breeder")
        self.le_indica = QtWidgets.QLineEdit(self.frame)
        self.le_indica.setGeometry(QtCore.QRect(215, 70, 87, 24))
        self.le_indica.setObjectName("le_indica")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(426, 10, 18, 18))
        self.label_3.setObjectName("label_3")
        self.te_notes = QtWidgets.QTextEdit(self.frame)
        self.te_notes.setGeometry(QtCore.QRect(66, 470, 481, 117))
        self.te_notes.setObjectName("te_notes")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(9, 10, 39, 18))
        self.label.setObjectName("label")
        self.le_genetics = QtWidgets.QLineEdit(self.frame)
        self.le_genetics.setGeometry(QtCore.QRect(67, 310, 481, 24))
        self.le_genetics.setText("")
        self.le_genetics.setObjectName("le_genetics")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(10, 310, 61, 18))
        self.label_15.setObjectName("label_15")
        self.le_qty = QtWidgets.QLineEdit(self.frame)
        self.le_qty.setGeometry(QtCore.QRect(290, 40, 51, 24))
        self.le_qty.setObjectName("le_qty")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(260, 40, 41, 18))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(10, 600, 61, 18))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(140, 640, 38, 18))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(20, 640, 38, 18))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(300, 600, 101, 20))
        self.label_20.setObjectName("label_20")
        self.le_supplier = QtWidgets.QLineEdit(self.frame)
        self.le_supplier.setGeometry(QtCore.QRect(70, 600, 211, 24))
        self.le_supplier.setObjectName("le_supplier")
        self.le_price = QtWidgets.QLineEdit(self.frame)
        self.le_price.setGeometry(QtCore.QRect(70, 640, 64, 24))
        self.le_price.setObjectName("le_price")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(330, 640, 41, 20))
        self.label_21.setObjectName("label_21")
        self.le_last_date = QtWidgets.QLineEdit(self.frame)
        self.le_last_date.setGeometry(QtCore.QRect(380, 640, 161, 20))
        self.le_last_date.setPlaceholderText("")
        self.le_last_date.setObjectName("le_last_date")
        self.le_flavour = QtWidgets.QTextEdit(self.frame)
        self.le_flavour.setGeometry(QtCore.QRect(66, 150, 481, 71))
        self.le_flavour.setObjectName("le_flavour")
        self.le_effect = QtWidgets.QTextEdit(self.frame)
        self.le_effect.setGeometry(QtCore.QRect(68, 230, 481, 71))
        self.le_effect.setObjectName("le_effect")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(10, 114, 85, 18))
        self.label_22.setObjectName("label_22")
        self.le_thc = QtWidgets.QLineEdit(self.frame)
        self.le_thc.setGeometry(QtCore.QRect(100, 110, 64, 24))
        self.le_thc.setObjectName("le_thc")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(180, 113, 39, 18))
        self.label_23.setObjectName("label_23")
        self.le_cbd = QtWidgets.QLineEdit(self.frame)
        self.le_cbd.setGeometry(QtCore.QRect(220, 110, 64, 24))
        self.le_cbd.setObjectName("le_cbd")
        self.de_pur_date = QtWidgets.QDateEdit(self.frame)
        self.de_pur_date.setGeometry(QtCore.QRect(400, 600, 110, 22))
        self.de_pur_date.setCalendarPopup(True)
        self.de_pur_date.setObjectName("de_pur_date")
        self.pb_today = QtWidgets.QPushButton(self.frame)
        self.pb_today.setGeometry(QtCore.QRect(510, 600, 31, 23))
        self.pb_today.setObjectName("pb_today")
        self.cb_starting = QtWidgets.QComboBox(DialogStrains)
        self.cb_starting.setEnabled(False)
        self.cb_starting.setGeometry(QtCore.QRect(230, 40, 69, 22))
        self.cb_starting.setObjectName("cb_starting")
        self.label_24 = QtWidgets.QLabel(DialogStrains)
        self.label_24.setGeometry(QtCore.QRect(160, 40, 61, 21))
        self.label_24.setObjectName("label_24")
        self.cb_filter = QtWidgets.QComboBox(DialogStrains)
        self.cb_filter.setGeometry(QtCore.QRect(10, 40, 131, 22))
        self.cb_filter.setObjectName("cb_filter")

        self.retranslateUi(DialogStrains)
        QtCore.QMetaObject.connectSlotsByName(DialogStrains)
        DialogStrains.setTabOrder(self.le_name, self.le_dur_min)
        DialogStrains.setTabOrder(self.le_dur_min, self.le_dur_max)
        DialogStrains.setTabOrder(self.le_dur_max, self.le_breeder)
        DialogStrains.setTabOrder(self.le_breeder, self.le_qty)
        DialogStrains.setTabOrder(self.le_qty, self.le_height)
        DialogStrains.setTabOrder(self.le_height, self.le_sativa)
        DialogStrains.setTabOrder(self.le_sativa, self.le_indica)
        DialogStrains.setTabOrder(self.le_indica, self.le_yeild)
        DialogStrains.setTabOrder(self.le_yeild, self.le_thc)
        DialogStrains.setTabOrder(self.le_thc, self.le_cbd)
        DialogStrains.setTabOrder(self.le_cbd, self.le_flavour)
        DialogStrains.setTabOrder(self.le_flavour, self.le_effect)
        DialogStrains.setTabOrder(self.le_effect, self.le_genetics)
        DialogStrains.setTabOrder(self.le_genetics, self.te_info)
        DialogStrains.setTabOrder(self.te_info, self.te_notes)
        DialogStrains.setTabOrder(self.te_notes, self.le_supplier)
        DialogStrains.setTabOrder(self.le_supplier, self.le_price)
        DialogStrains.setTabOrder(self.le_price, self.le_last_date)
        DialogStrains.setTabOrder(self.le_last_date, self.lw_strains)
        DialogStrains.setTabOrder(self.lw_strains, self.pb_new)
        DialogStrains.setTabOrder(self.pb_new, self.pb_close)
        DialogStrains.setTabOrder(self.pb_close, self.pb_save)

    def retranslateUi(self, DialogStrains):
        _translate = QtCore.QCoreApplication.translate
        DialogStrains.setWindowTitle(_translate("DialogStrains", "Strains"))
        self.pb_close.setText(_translate("DialogStrains", "Close"))
        self.pb_save.setText(_translate("DialogStrains", "Save"))
        self.pb_new.setText(_translate("DialogStrains", "New"))
        self.label_14.setText(_translate("DialogStrains", "Strains"))
        self.label_12.setText(_translate("DialogStrains", "Notes"))
        self.label_5.setText(_translate("DialogStrains", "Type  Sativia"))
        self.label_11.setText(_translate("DialogStrains", "Info"))
        self.label_2.setText(_translate("DialogStrains", "Duration From"))
        self.label_4.setText(_translate("DialogStrains", "days"))
        self.label_7.setText(_translate("DialogStrains", "Height"))
        self.label_6.setText(_translate("DialogStrains", "Indica"))
        self.label_9.setText(_translate("DialogStrains", "Effect"))
        self.label_8.setText(_translate("DialogStrains", "Flavour"))
        self.label_10.setText(_translate("DialogStrains", "Yeild"))
        self.label_13.setText(_translate("DialogStrains", "Breeder"))
        self.label_3.setText(_translate("DialogStrains", "To"))
        self.label.setText(_translate("DialogStrains", "Name"))
        self.label_15.setText(_translate("DialogStrains", "Genetics"))
        self.label_16.setText(_translate("DialogStrains", "Qty"))
        self.label_17.setText(_translate("DialogStrains", "Supplier"))
        self.label_18.setText(_translate("DialogStrains", "each"))
        self.label_19.setText(_translate("DialogStrains", "Price"))
        self.label_20.setText(_translate("DialogStrains", "Purchase Date"))
        self.label_21.setText(_translate("DialogStrains", "Used"))
        self.label_22.setText(_translate("DialogStrains", "THC"))
        self.label_23.setText(_translate("DialogStrains", "CBD"))
        self.pb_today.setText(_translate("DialogStrains", "T"))
        self.label_24.setText(_translate("DialogStrains", "Starting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogStrains = QtWidgets.QDialog()
    ui = Ui_DialogStrains()
    ui.setupUi(DialogStrains)
    DialogStrains.show()
    sys.exit(app.exec_())

