# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogWorkshopSettings.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogWorkshopSetting(object):
    def setupUi(self, DialogWorkshopSetting):
        DialogWorkshopSetting.setObjectName("DialogWorkshopSetting")
        DialogWorkshopSetting.resize(246, 388)
        font = QtGui.QFont()
        font.setPointSize(11)
        DialogWorkshopSetting.setFont(font)
        self.cb_mode = QtWidgets.QComboBox(DialogWorkshopSetting)
        self.cb_mode.setGeometry(QtCore.QRect(80, 50, 151, 24))
        self.cb_mode.setProperty("area", 1)
        self.cb_mode.setProperty("item", 1)
        self.cb_mode.setObjectName("cb_mode")
        self.label_46 = QtWidgets.QLabel(DialogWorkshopSetting)
        self.label_46.setGeometry(QtCore.QRect(20, 50, 36, 18))
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.frm_timer = QtWidgets.QFrame(DialogWorkshopSetting)
        self.frm_timer.setGeometry(QtCore.QRect(20, 110, 221, 71))
        self.frm_timer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_timer.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frm_timer.setObjectName("frm_timer")
        self.label_47 = QtWidgets.QLabel(self.frm_timer)
        self.label_47.setGeometry(QtCore.QRect(10, 8, 38, 18))
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.frm_timer)
        self.label_48.setGeometry(QtCore.QRect(10, 36, 61, 18))
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.tm_duration = QtWidgets.QTimeEdit(self.frm_timer)
        self.tm_duration.setGeometry(QtCore.QRect(80, 35, 91, 22))
        self.tm_duration.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 10, 0)))
        self.tm_duration.setMaximumTime(QtCore.QTime(5, 0, 0))
        self.tm_duration.setMinimumTime(QtCore.QTime(0, 10, 0))
        self.tm_duration.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.tm_duration.setObjectName("tm_duration")
        self.pb_close = QtWidgets.QPushButton(DialogWorkshopSetting)
        self.pb_close.setGeometry(QtCore.QRect(160, 350, 75, 25))
        self.pb_close.setObjectName("pb_close")
        self.lbl_name = QtWidgets.QLabel(DialogWorkshopSetting)
        self.lbl_name.setGeometry(QtCore.QRect(10, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name.setFont(font)
        self.lbl_name.setObjectName("lbl_name")
        self.ck_auto_boost = QtWidgets.QCheckBox(DialogWorkshopSetting)
        self.ck_auto_boost.setGeometry(QtCore.QRect(20, 83, 191, 21))
        self.ck_auto_boost.setObjectName("ck_auto_boost")
        self.frm_sensor = QtWidgets.QFrame(DialogWorkshopSetting)
        self.frm_sensor.setGeometry(QtCore.QRect(20, 190, 221, 71))
        self.frm_sensor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_sensor.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frm_sensor.setObjectName("frm_sensor")
        self.le_max = QtWidgets.QLineEdit(self.frm_sensor)
        self.le_max.setGeometry(QtCore.QRect(130, 40, 41, 21))
        self.le_max.setObjectName("le_max")
        self.cb_sensor_ = QtWidgets.QComboBox(self.frm_sensor)
        self.cb_sensor_.setGeometry(QtCore.QRect(59, 10, 151, 24))
        self.cb_sensor_.setMinimumSize(QtCore.QSize(140, 0))
        self.cb_sensor_.setProperty("area", 1)
        self.cb_sensor_.setProperty("item", 1)
        self.cb_sensor_.setObjectName("cb_sensor_")
        self.le_min = QtWidgets.QLineEdit(self.frm_sensor)
        self.le_min.setGeometry(QtCore.QRect(40, 40, 41, 21))
        self.le_min.setObjectName("le_min")
        self.label_49 = QtWidgets.QLabel(self.frm_sensor)
        self.label_49.setGeometry(QtCore.QRect(0, 40, 41, 20))
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.frm_sensor)
        self.label_50.setGeometry(QtCore.QRect(10, 10, 44, 18))
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.pb_reset = QtWidgets.QPushButton(self.frm_sensor)
        self.pb_reset.setGeometry(QtCore.QRect(180, 40, 31, 23))
        self.pb_reset.setObjectName("pb_reset")
        self.label_51 = QtWidgets.QLabel(self.frm_sensor)
        self.label_51.setGeometry(QtCore.QRect(90, 40, 41, 20))
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.frm_sensor_2 = QtWidgets.QFrame(DialogWorkshopSetting)
        self.frm_sensor_2.setGeometry(QtCore.QRect(20, 270, 221, 71))
        self.frm_sensor_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_sensor_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frm_sensor_2.setObjectName("frm_sensor_2")
        self.le_min_frost = QtWidgets.QLineEdit(self.frm_sensor_2)
        self.le_min_frost.setGeometry(QtCore.QRect(60, 40, 41, 21))
        self.le_min_frost.setObjectName("le_min_frost")
        self.label_52 = QtWidgets.QLabel(self.frm_sensor_2)
        self.label_52.setGeometry(QtCore.QRect(10, 40, 41, 20))
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.ck_frost = QtWidgets.QCheckBox(self.frm_sensor_2)
        self.ck_frost.setGeometry(QtCore.QRect(10, 10, 131, 17))
        self.ck_frost.setObjectName("ck_frost")
        self.le_max_frost = QtWidgets.QLineEdit(self.frm_sensor_2)
        self.le_max_frost.setGeometry(QtCore.QRect(160, 40, 41, 21))
        self.le_max_frost.setObjectName("le_max_frost")
        self.label_53 = QtWidgets.QLabel(self.frm_sensor_2)
        self.label_53.setGeometry(QtCore.QRect(120, 40, 41, 20))
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.ck_lock = QtWidgets.QCheckBox(DialogWorkshopSetting)
        self.ck_lock.setGeometry(QtCore.QRect(30, 357, 71, 20))
        self.ck_lock.setObjectName("ck_lock")
        self.ck_occupied = QtWidgets.QCheckBox(DialogWorkshopSetting)
        self.ck_occupied.setGeometry(QtCore.QRect(120, 82, 121, 23))
        self.ck_occupied.setObjectName("ck_occupied")
        self.label_46.setBuddy(self.label_46)

        self.retranslateUi(DialogWorkshopSetting)
        QtCore.QMetaObject.connectSlotsByName(DialogWorkshopSetting)
        DialogWorkshopSetting.setTabOrder(self.cb_mode, self.pb_close)

    def retranslateUi(self, DialogWorkshopSetting):
        _translate = QtCore.QCoreApplication.translate
        DialogWorkshopSetting.setWindowTitle(_translate("DialogWorkshopSetting", "Workshop Heater Settings"))
        self.label_46.setText(_translate("DialogWorkshopSetting", "Mode"))
        self.label_47.setText(_translate("DialogWorkshopSetting", "Timer"))
        self.label_48.setText(_translate("DialogWorkshopSetting", "Duration"))
        self.pb_close.setText(_translate("DialogWorkshopSetting", "Close"))
        self.lbl_name.setText(_translate("DialogWorkshopSetting", "Workshop"))
        self.ck_auto_boost.setText(_translate("DialogWorkshopSetting", "Auto Boost"))
        self.label_49.setText(_translate("DialogWorkshopSetting", "Min"))
        self.label_50.setText(_translate("DialogWorkshopSetting", "Sensor"))
        self.pb_reset.setText(_translate("DialogWorkshopSetting", "R"))
        self.label_51.setText(_translate("DialogWorkshopSetting", "Max"))
        self.label_52.setText(_translate("DialogWorkshopSetting", "Min"))
        self.ck_frost.setText(_translate("DialogWorkshopSetting", "Frost Protection"))
        self.label_53.setText(_translate("DialogWorkshopSetting", "Max"))
        self.ck_lock.setText(_translate("DialogWorkshopSetting", "Lock"))
        self.ck_occupied.setText(_translate("DialogWorkshopSetting", "Only Occupied"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogWorkshopSetting = QtWidgets.QWidget()
    ui = Ui_DialogWorkshopSetting()
    ui.setupUi(DialogWorkshopSetting)
    DialogWorkshopSetting.show()
    sys.exit(app.exec_())

