# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogFeederCalibrate.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogFeederCalibrate(object):
    def setupUi(self, dialogFeederCalibrate):
        dialogFeederCalibrate.setObjectName("dialogFeederCalibrate")
        dialogFeederCalibrate.resize(892, 420)
        font = QtGui.QFont()
        font.setPointSize(11)
        dialogFeederCalibrate.setFont(font)
        self.frame_2 = QtWidgets.QFrame(dialogFeederCalibrate)
        self.frame_2.setGeometry(QtCore.QRect(9, 9, 871, 321))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 34, 54, 18))
        self.label_4.setObjectName("label_4")
        self.lbl_name_c_1 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_1.setGeometry(QtCore.QRect(10, 61, 85, 18))
        self.lbl_name_c_1.setObjectName("lbl_name_c_1")
        self.le_dur_1 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_1.setGeometry(QtCore.QRect(104, 59, 70, 24))
        self.le_dur_1.setObjectName("le_dur_1")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(180, 58, 51, 18))
        self.label_6.setObjectName("label_6")
        self.pb_run_1 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_1.setGeometry(QtCore.QRect(234, 58, 70, 26))
        self.pb_run_1.setObjectName("pb_run_1")
        self.le_result_1 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_1.setGeometry(QtCore.QRect(310, 59, 64, 24))
        self.le_result_1.setObjectName("le_result_1")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(378, 58, 22, 18))
        self.label_7.setObjectName("label_7")
        self.lbl_name_c_2 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_2.setGeometry(QtCore.QRect(10, 93, 85, 18))
        self.lbl_name_c_2.setObjectName("lbl_name_c_2")
        self.le_dur_2 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_2.setGeometry(QtCore.QRect(104, 91, 70, 24))
        self.le_dur_2.setObjectName("le_dur_2")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(180, 90, 45, 18))
        self.label_9.setObjectName("label_9")
        self.pb_run_2 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_2.setGeometry(QtCore.QRect(234, 90, 70, 26))
        self.pb_run_2.setObjectName("pb_run_2")
        self.le_result_2 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_2.setGeometry(QtCore.QRect(310, 91, 64, 24))
        self.le_result_2.setObjectName("le_result_2")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(378, 90, 22, 18))
        self.label_11.setObjectName("label_11")
        self.lbl_name_c_3 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_3.setGeometry(QtCore.QRect(10, 125, 85, 18))
        self.lbl_name_c_3.setObjectName("lbl_name_c_3")
        self.le_dur_3 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_3.setGeometry(QtCore.QRect(104, 123, 70, 24))
        self.le_dur_3.setObjectName("le_dur_3")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(180, 122, 45, 18))
        self.label_12.setObjectName("label_12")
        self.pb_run_3 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_3.setGeometry(QtCore.QRect(234, 122, 70, 26))
        self.pb_run_3.setObjectName("pb_run_3")
        self.le_result_3 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_3.setGeometry(QtCore.QRect(310, 123, 64, 24))
        self.le_result_3.setObjectName("le_result_3")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(378, 122, 22, 18))
        self.label_14.setObjectName("label_14")
        self.lbl_name_c_4 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_4.setGeometry(QtCore.QRect(10, 157, 85, 18))
        self.lbl_name_c_4.setObjectName("lbl_name_c_4")
        self.le_dur_4 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_4.setGeometry(QtCore.QRect(104, 155, 70, 24))
        self.le_dur_4.setObjectName("le_dur_4")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(180, 154, 45, 18))
        self.label_15.setObjectName("label_15")
        self.pb_run_4 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_4.setGeometry(QtCore.QRect(234, 154, 70, 26))
        self.pb_run_4.setObjectName("pb_run_4")
        self.le_result_4 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_4.setGeometry(QtCore.QRect(310, 155, 64, 24))
        self.le_result_4.setObjectName("le_result_4")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(378, 154, 22, 18))
        self.label_17.setObjectName("label_17")
        self.lbl_name_c_6 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_6.setGeometry(QtCore.QRect(10, 220, 85, 18))
        self.lbl_name_c_6.setObjectName("lbl_name_c_6")
        self.le_dur_5 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_5.setGeometry(QtCore.QRect(104, 187, 70, 24))
        self.le_dur_5.setObjectName("le_dur_5")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(180, 186, 45, 18))
        self.label_18.setObjectName("label_18")
        self.pb_run_5 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_5.setGeometry(QtCore.QRect(234, 186, 70, 26))
        self.pb_run_5.setObjectName("pb_run_5")
        self.le_result_5 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_5.setGeometry(QtCore.QRect(310, 187, 64, 24))
        self.le_result_5.setObjectName("le_result_5")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(378, 186, 22, 18))
        self.label_20.setObjectName("label_20")
        self.lbl_name_c_5 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_5.setGeometry(QtCore.QRect(10, 189, 85, 18))
        self.lbl_name_c_5.setObjectName("lbl_name_c_5")
        self.le_dur_6 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_6.setGeometry(QtCore.QRect(104, 219, 70, 24))
        self.le_dur_6.setObjectName("le_dur_6")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(180, 218, 45, 18))
        self.label_21.setObjectName("label_21")
        self.pb_run_6 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_6.setGeometry(QtCore.QRect(234, 218, 70, 26))
        self.pb_run_6.setObjectName("pb_run_6")
        self.le_result_6 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_6.setGeometry(QtCore.QRect(310, 219, 64, 24))
        self.le_result_6.setObjectName("le_result_6")
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setGeometry(QtCore.QRect(378, 218, 22, 18))
        self.label_23.setObjectName("label_23")
        self.lbl_name_c_7 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_7.setGeometry(QtCore.QRect(10, 250, 85, 18))
        self.lbl_name_c_7.setObjectName("lbl_name_c_7")
        self.le_dur_7 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_7.setGeometry(QtCore.QRect(104, 251, 70, 24))
        self.le_dur_7.setObjectName("le_dur_7")
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        self.label_24.setGeometry(QtCore.QRect(180, 250, 45, 18))
        self.label_24.setObjectName("label_24")
        self.pb_run_7 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_7.setGeometry(QtCore.QRect(234, 250, 70, 26))
        self.pb_run_7.setObjectName("pb_run_7")
        self.le_result_7 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_7.setGeometry(QtCore.QRect(310, 251, 64, 24))
        self.le_result_7.setObjectName("le_result_7")
        self.label_26 = QtWidgets.QLabel(self.frame_2)
        self.label_26.setGeometry(QtCore.QRect(378, 250, 22, 18))
        self.label_26.setObjectName("label_26")
        self.lbl_name_c_8 = QtWidgets.QLabel(self.frame_2)
        self.lbl_name_c_8.setGeometry(QtCore.QRect(10, 282, 85, 18))
        self.lbl_name_c_8.setObjectName("lbl_name_c_8")
        self.le_dur_8 = QtWidgets.QLineEdit(self.frame_2)
        self.le_dur_8.setGeometry(QtCore.QRect(104, 283, 70, 24))
        self.le_dur_8.setObjectName("le_dur_8")
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        self.label_27.setGeometry(QtCore.QRect(180, 282, 45, 18))
        self.label_27.setObjectName("label_27")
        self.pb_run_8 = QtWidgets.QPushButton(self.frame_2)
        self.pb_run_8.setGeometry(QtCore.QRect(234, 282, 70, 26))
        self.pb_run_8.setObjectName("pb_run_8")
        self.le_result_8 = QtWidgets.QLineEdit(self.frame_2)
        self.le_result_8.setGeometry(QtCore.QRect(310, 283, 64, 24))
        self.le_result_8.setObjectName("le_result_8")
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        self.label_29.setGeometry(QtCore.QRect(378, 282, 22, 18))
        self.label_29.setObjectName("label_29")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(306, 34, 39, 18))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 181, 18))
        self.label_3.setObjectName("label_3")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(510, 30, 39, 18))
        self.label_22.setObjectName("label_22")
        self.le_test_1 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_1.setGeometry(QtCore.QRect(482, 61, 64, 24))
        self.le_test_1.setObjectName("le_test_1")
        self.label_25 = QtWidgets.QLabel(self.frame_2)
        self.label_25.setGeometry(QtCore.QRect(550, 60, 22, 18))
        self.label_25.setObjectName("label_25")
        self.pb_dispense_1 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_1.setGeometry(QtCore.QRect(580, 60, 70, 26))
        self.pb_dispense_1.setObjectName("pb_dispense_1")
        self.lbl_current_1 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_1.setGeometry(QtCore.QRect(668, 64, 190, 18))
        self.lbl_current_1.setText("")
        self.lbl_current_1.setObjectName("lbl_current_1")
        self.pb_dispense_2 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_2.setGeometry(QtCore.QRect(578, 91, 70, 26))
        self.pb_dispense_2.setObjectName("pb_dispense_2")
        self.lbl_current_2 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_2.setGeometry(QtCore.QRect(666, 95, 190, 18))
        self.lbl_current_2.setText("")
        self.lbl_current_2.setObjectName("lbl_current_2")
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        self.label_28.setGeometry(QtCore.QRect(548, 91, 22, 18))
        self.label_28.setObjectName("label_28")
        self.le_test_2 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_2.setGeometry(QtCore.QRect(480, 92, 64, 24))
        self.le_test_2.setObjectName("le_test_2")
        self.pb_dispense_3 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_3.setGeometry(QtCore.QRect(578, 122, 70, 26))
        self.pb_dispense_3.setObjectName("pb_dispense_3")
        self.lbl_current_3 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_3.setGeometry(QtCore.QRect(666, 126, 190, 18))
        self.lbl_current_3.setText("")
        self.lbl_current_3.setObjectName("lbl_current_3")
        self.label_30 = QtWidgets.QLabel(self.frame_2)
        self.label_30.setGeometry(QtCore.QRect(548, 122, 22, 18))
        self.label_30.setObjectName("label_30")
        self.le_test_3 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_3.setGeometry(QtCore.QRect(480, 123, 64, 24))
        self.le_test_3.setObjectName("le_test_3")
        self.pb_dispense_4 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_4.setGeometry(QtCore.QRect(578, 154, 70, 26))
        self.pb_dispense_4.setObjectName("pb_dispense_4")
        self.lbl_current_4 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_4.setGeometry(QtCore.QRect(666, 158, 190, 18))
        self.lbl_current_4.setText("")
        self.lbl_current_4.setObjectName("lbl_current_4")
        self.label_31 = QtWidgets.QLabel(self.frame_2)
        self.label_31.setGeometry(QtCore.QRect(548, 154, 22, 18))
        self.label_31.setObjectName("label_31")
        self.le_test_4 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_4.setGeometry(QtCore.QRect(480, 155, 64, 24))
        self.le_test_4.setObjectName("le_test_4")
        self.pb_dispense_5 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_5.setGeometry(QtCore.QRect(578, 186, 70, 26))
        self.pb_dispense_5.setObjectName("pb_dispense_5")
        self.lbl_current_5 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_5.setGeometry(QtCore.QRect(666, 190, 190, 18))
        self.lbl_current_5.setText("")
        self.lbl_current_5.setObjectName("lbl_current_5")
        self.label_32 = QtWidgets.QLabel(self.frame_2)
        self.label_32.setGeometry(QtCore.QRect(548, 186, 22, 18))
        self.label_32.setObjectName("label_32")
        self.le_test_5 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_5.setGeometry(QtCore.QRect(480, 187, 64, 24))
        self.le_test_5.setObjectName("le_test_5")
        self.pb_dispense_6 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_6.setGeometry(QtCore.QRect(578, 219, 70, 26))
        self.pb_dispense_6.setObjectName("pb_dispense_6")
        self.lbl_current_6 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_6.setGeometry(QtCore.QRect(666, 223, 190, 18))
        self.lbl_current_6.setText("")
        self.lbl_current_6.setObjectName("lbl_current_6")
        self.label_33 = QtWidgets.QLabel(self.frame_2)
        self.label_33.setGeometry(QtCore.QRect(548, 219, 22, 18))
        self.label_33.setObjectName("label_33")
        self.le_test_6 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_6.setGeometry(QtCore.QRect(480, 220, 64, 24))
        self.le_test_6.setObjectName("le_test_6")
        self.pb_dispense_7 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_7.setGeometry(QtCore.QRect(578, 250, 70, 26))
        self.pb_dispense_7.setObjectName("pb_dispense_7")
        self.lbl_current_7 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_7.setGeometry(QtCore.QRect(666, 254, 190, 18))
        self.lbl_current_7.setText("")
        self.lbl_current_7.setObjectName("lbl_current_7")
        self.label_34 = QtWidgets.QLabel(self.frame_2)
        self.label_34.setGeometry(QtCore.QRect(548, 250, 22, 18))
        self.label_34.setObjectName("label_34")
        self.le_test_7 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_7.setGeometry(QtCore.QRect(480, 251, 64, 24))
        self.le_test_7.setObjectName("le_test_7")
        self.pb_dispense_8 = QtWidgets.QPushButton(self.frame_2)
        self.pb_dispense_8.setGeometry(QtCore.QRect(578, 282, 70, 26))
        self.pb_dispense_8.setObjectName("pb_dispense_8")
        self.lbl_current_8 = QtWidgets.QLabel(self.frame_2)
        self.lbl_current_8.setGeometry(QtCore.QRect(666, 286, 190, 18))
        self.lbl_current_8.setText("")
        self.lbl_current_8.setObjectName("lbl_current_8")
        self.label_35 = QtWidgets.QLabel(self.frame_2)
        self.label_35.setGeometry(QtCore.QRect(548, 282, 22, 18))
        self.label_35.setObjectName("label_35")
        self.le_test_8 = QtWidgets.QLineEdit(self.frame_2)
        self.le_test_8.setGeometry(QtCore.QRect(480, 283, 64, 24))
        self.le_test_8.setObjectName("le_test_8")
        self.pb_save_1 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_1.setGeometry(QtCore.QRect(410, 60, 61, 26))
        self.pb_save_1.setObjectName("pb_save_1")
        self.pb_save_3 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_3.setGeometry(QtCore.QRect(410, 120, 61, 26))
        self.pb_save_3.setObjectName("pb_save_3")
        self.pb_save_4 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_4.setGeometry(QtCore.QRect(410, 150, 61, 26))
        self.pb_save_4.setObjectName("pb_save_4")
        self.pb_save_5 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_5.setGeometry(QtCore.QRect(410, 186, 61, 26))
        self.pb_save_5.setObjectName("pb_save_5")
        self.pb_save_6 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_6.setGeometry(QtCore.QRect(410, 220, 61, 26))
        self.pb_save_6.setObjectName("pb_save_6")
        self.pb_save_7 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_7.setGeometry(QtCore.QRect(410, 250, 61, 26))
        self.pb_save_7.setObjectName("pb_save_7")
        self.pb_save_8 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_8.setGeometry(QtCore.QRect(410, 280, 61, 26))
        self.pb_save_8.setObjectName("pb_save_8")
        self.pb_save_2 = QtWidgets.QPushButton(self.frame_2)
        self.pb_save_2.setGeometry(QtCore.QRect(410, 90, 61, 26))
        self.pb_save_2.setObjectName("pb_save_2")
        self.frame = QtWidgets.QFrame(dialogFeederCalibrate)
        self.frame.setGeometry(QtCore.QRect(10, 340, 501, 71))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.pb_run_mix = QtWidgets.QPushButton(self.frame)
        self.pb_run_mix.setGeometry(QtCore.QRect(215, 30, 75, 26))
        self.pb_run_mix.setObjectName("pb_run_mix")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 64, 18))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(10, 2, 201, 18))
        self.label_10.setObjectName("label_10")
        self.le_dur_mix = QtWidgets.QLineEdit(self.frame)
        self.le_dur_mix.setGeometry(QtCore.QRect(80, 30, 93, 24))
        self.le_dur_mix.setObjectName("le_dur_mix")
        self.le_result_mix = QtWidgets.QLineEdit(self.frame)
        self.le_result_mix.setGeometry(QtCore.QRect(296, 30, 68, 24))
        self.le_result_mix.setObjectName("le_result_mix")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(296, 10, 68, 18))
        self.label_13.setObjectName("label_13")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(179, 30, 30, 26))
        self.label_16.setObjectName("label_16")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(370, 30, 22, 26))
        self.label_19.setObjectName("label_19")
        self.pb_save_mix = QtWidgets.QPushButton(self.frame)
        self.pb_save_mix.setGeometry(QtCore.QRect(400, 30, 61, 26))
        self.pb_save_mix.setObjectName("pb_save_mix")
        self.pb_close = QtWidgets.QPushButton(dialogFeederCalibrate)
        self.pb_close.setGeometry(QtCore.QRect(780, 360, 75, 23))
        self.pb_close.setObjectName("pb_close")
        self.pb_stop = QtWidgets.QPushButton(dialogFeederCalibrate)
        self.pb_stop.setGeometry(QtCore.QRect(580, 340, 81, 41))
        self.pb_stop.setObjectName("pb_stop")

        self.retranslateUi(dialogFeederCalibrate)
        QtCore.QMetaObject.connectSlotsByName(dialogFeederCalibrate)

    def retranslateUi(self, dialogFeederCalibrate):
        _translate = QtCore.QCoreApplication.translate
        dialogFeederCalibrate.setWindowTitle(_translate("dialogFeederCalibrate", "Feeder Calibration"))
        self.label_4.setText(_translate("dialogFeederCalibrate", "Duration"))
        self.lbl_name_c_1.setText(_translate("dialogFeederCalibrate", "TextLabel"))
        self.le_dur_1.setText(_translate("dialogFeederCalibrate", "1000"))
        self.label_6.setText(_translate("dialogFeederCalibrate", "mSecs"))
        self.pb_run_1.setText(_translate("dialogFeederCalibrate", "Run"))
        self.label_7.setText(_translate("dialogFeederCalibrate", "mls"))
        self.lbl_name_c_2.setText(_translate("dialogFeederCalibrate", "TextLabel"))
        self.le_dur_2.setText(_translate("dialogFeederCalibrate", "1000"))
        self.label_9.setText(_translate("dialogFeederCalibrate", "mSecs"))
        self.pb_run_2.setText(_translate("dialogFeederCalibrate", "Run"))
        self.label_11.setText(_translate("dialogFeederCalibrate", "mls"))
        self.lbl_name_c_3.setText(_translate("dialogFeederCalibrate", "TextLabel"))
        self.le_dur_3.setText(_translate("dialogFeederCalibrate", "1000"))
        self.label_12.setText(_translate("dialogFeederCalibrate", "mSecs"))
        self.pb_run_3.setText(_translate("dialogFeederCalibrate", "Run"))
        self.label_14.setText(_translate("dialogFeederCalibrate", "mls"))
        self.lbl_name_c_4.setText(_translate("dialogFeederCalibrate", "TextLabel"))
        self.le_dur_4.setText(_translate("dialogFeederCalibrate", "1000"))
        self.label_15.setText(_translate("dialogFeederCalibrate", "mSecs"))
        self.pb_run_4.setText(_translate("dialogFeederCalibrate", "Run"))
        self.label_17.setText(_translate("dialogFeederCalibrate", "mls"))
        self.lbl_name_c_6.setText(_translate("dialogFeederCalibrate", "TextLabel"))
        self.le_dur_5.setText(_translate("dialogFeederCalibrate", "1000"))
        self.label_18.setText(_translate("dialogFeederCalibrate", "mSecs"))
        self.pb_run_5.setText(_translate("dialogFeederCalibrate", "Run"))
        self.label_20.setText(_translate("dialogFeederCalibrate", "mls"))
        self.lbl_name_c_5.setText(_translate("dialogFeederCalibrate", "TextLabel"))
        self.le_dur_6.setText(_translate("dialogFeederCalibrate", "1000"))
        self.label_21.setText(_translate("dialogFeederCalibrate", "mSecs"))
        self.pb_run_6.setText(_translate("dialogFeederCalibrate", "Run"))
        self.label_23.setText(_translate("dialogFeederCalibrate", "mls"))
        self.lbl_name_c_7.setText(_translate("dialogFeederCalibrate", "TextLabel"))
        self.le_dur_7.setText(_translate("dialogFeederCalibrate", "1000"))
        self.label_24.setText(_translate("dialogFeederCalibrate", "mSecs"))
        self.pb_run_7.setText(_translate("dialogFeederCalibrate", "Run"))
        self.label_26.setText(_translate("dialogFeederCalibrate", "mls"))
        self.lbl_name_c_8.setText(_translate("dialogFeederCalibrate", "TextLabel"))
        self.le_dur_8.setText(_translate("dialogFeederCalibrate", "1000"))
        self.label_27.setText(_translate("dialogFeederCalibrate", "mSecs"))
        self.pb_run_8.setText(_translate("dialogFeederCalibrate", "Run"))
        self.label_29.setText(_translate("dialogFeederCalibrate", "mls"))
        self.label_5.setText(_translate("dialogFeederCalibrate", "Result"))
        self.label_3.setText(_translate("dialogFeederCalibrate", "Nutrient Pump Calibration"))
        self.label_22.setText(_translate("dialogFeederCalibrate", "Test"))
        self.label_25.setText(_translate("dialogFeederCalibrate", "mls"))
        self.pb_dispense_1.setText(_translate("dialogFeederCalibrate", "Dispense"))
        self.pb_dispense_2.setText(_translate("dialogFeederCalibrate", "Dispense"))
        self.label_28.setText(_translate("dialogFeederCalibrate", "mls"))
        self.pb_dispense_3.setText(_translate("dialogFeederCalibrate", "Dispense"))
        self.label_30.setText(_translate("dialogFeederCalibrate", "mls"))
        self.pb_dispense_4.setText(_translate("dialogFeederCalibrate", "Dispense"))
        self.label_31.setText(_translate("dialogFeederCalibrate", "mls"))
        self.pb_dispense_5.setText(_translate("dialogFeederCalibrate", "Dispense"))
        self.label_32.setText(_translate("dialogFeederCalibrate", "mls"))
        self.pb_dispense_6.setText(_translate("dialogFeederCalibrate", "Dispense"))
        self.label_33.setText(_translate("dialogFeederCalibrate", "mls"))
        self.pb_dispense_7.setText(_translate("dialogFeederCalibrate", "Dispense"))
        self.label_34.setText(_translate("dialogFeederCalibrate", "mls"))
        self.pb_dispense_8.setText(_translate("dialogFeederCalibrate", "Dispense"))
        self.label_35.setText(_translate("dialogFeederCalibrate", "mls"))
        self.pb_save_1.setText(_translate("dialogFeederCalibrate", "Save"))
        self.pb_save_3.setText(_translate("dialogFeederCalibrate", "Save"))
        self.pb_save_4.setText(_translate("dialogFeederCalibrate", "Save"))
        self.pb_save_5.setText(_translate("dialogFeederCalibrate", "Save"))
        self.pb_save_6.setText(_translate("dialogFeederCalibrate", "Save"))
        self.pb_save_7.setText(_translate("dialogFeederCalibrate", "Save"))
        self.pb_save_8.setText(_translate("dialogFeederCalibrate", "Save"))
        self.pb_save_2.setText(_translate("dialogFeederCalibrate", "Save"))
        self.pb_run_mix.setText(_translate("dialogFeederCalibrate", "Run"))
        self.label_8.setText(_translate("dialogFeederCalibrate", "Duration"))
        self.label_10.setText(_translate("dialogFeederCalibrate", "Mix Feed Pump Calibration"))
        self.le_dur_mix.setInputMask(_translate("dialogFeederCalibrate", "09"))
        self.le_dur_mix.setText(_translate("dialogFeederCalibrate", "5"))
        self.label_13.setText(_translate("dialogFeederCalibrate", "Result"))
        self.label_16.setText(_translate("dialogFeederCalibrate", "Secs"))
        self.label_19.setText(_translate("dialogFeederCalibrate", "mls"))
        self.pb_save_mix.setText(_translate("dialogFeederCalibrate", "Save"))
        self.pb_close.setText(_translate("dialogFeederCalibrate", "Close"))
        self.pb_stop.setText(_translate("dialogFeederCalibrate", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialogFeederCalibrate = QtWidgets.QDialog()
    ui = Ui_dialogFeederCalibrate()
    ui.setupUi(dialogFeederCalibrate)
    dialogFeederCalibrate.show()
    sys.exit(app.exec_())

