# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogSettings.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogSettings(object):
    def setupUi(self, DialogSettings):
        DialogSettings.setObjectName("DialogSettings")
        DialogSettings.resize(564, 332)
        font = QtGui.QFont()
        font.setPointSize(11)
        DialogSettings.setFont(font)
        self.tabWidget = QtWidgets.QTabWidget(DialogSettings)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 791, 271))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.system = QtWidgets.QWidget()
        self.system.setObjectName("system")
        self.groupBox_3 = QtWidgets.QGroupBox(self.system)
        self.groupBox_3.setGeometry(QtCore.QRect(160, 10, 261, 181))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.label_22.setObjectName("label_22")
        self.pb_db_open = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_db_open.setGeometry(QtCore.QRect(150, 150, 75, 23))
        self.pb_db_open.setObjectName("pb_db_open")
        self.le_db_host = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_db_host.setGeometry(QtCore.QRect(100, 30, 141, 20))
        self.le_db_host.setObjectName("le_db_host")
        self.le_db_user_name = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_db_user_name.setGeometry(QtCore.QRect(100, 60, 141, 20))
        self.le_db_user_name.setObjectName("le_db_user_name")
        self.le_db_password = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_db_password.setGeometry(QtCore.QRect(100, 90, 141, 20))
        self.le_db_password.setObjectName("le_db_password")
        self.le_db_name = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_db_name.setGeometry(QtCore.QRect(100, 120, 141, 20))
        self.le_db_name.setObjectName("le_db_name")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(20, 120, 81, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(20, 60, 81, 16))
        self.label_25.setObjectName("label_25")
        self.pb_back_up = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_back_up.setGeometry(QtCore.QRect(20, 150, 75, 25))
        self.pb_back_up.setAutoDefault(False)
        self.pb_back_up.setObjectName("pb_back_up")
        self.label_26 = QtWidgets.QLabel(self.system)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label_26.setObjectName("label_26")
        self.cb_system_mode = QtWidgets.QComboBox(self.system)
        self.cb_system_mode.setGeometry(QtCore.QRect(10, 40, 111, 22))
        self.cb_system_mode.setObjectName("cb_system_mode")
        self.tabWidget.addTab(self.system, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(10, 10, 151, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.label.setObjectName("label")
        self.pbusoperate = QtWidgets.QPushButton(self.frame)
        self.pbusoperate.setGeometry(QtCore.QRect(20, 130, 61, 23))
        self.pbusoperate.setCheckable(False)
        self.pbusoperate.setChecked(False)
        self.pbusoperate.setAutoDefault(True)
        self.pbusoperate.setDefault(False)
        self.pbusoperate.setFlat(False)
        self.pbusoperate.setObjectName("pbusoperate")
        self.rbustank_1 = QtWidgets.QRadioButton(self.frame)
        self.rbustank_1.setGeometry(QtCore.QRect(20, 40, 101, 17))
        self.rbustank_1.setObjectName("rbustank_1")
        self.leusreading = QtWidgets.QLineEdit(self.frame)
        self.leusreading.setGeometry(QtCore.QRect(20, 160, 91, 20))
        self.leusreading.setObjectName("leusreading")
        self.leusliters = QtWidgets.QLineEdit(self.frame)
        self.leusliters.setGeometry(QtCore.QRect(20, 190, 41, 20))
        self.leusliters.setObjectName("leusliters")
        self.lblusoperate = QtWidgets.QLabel(self.frame)
        self.lblusoperate.setGeometry(QtCore.QRect(100, 130, 21, 21))
        self.lblusoperate.setText("")
        self.lblusoperate.setObjectName("lblusoperate")
        self.rbustank_2 = QtWidgets.QRadioButton(self.frame)
        self.rbustank_2.setGeometry(QtCore.QRect(20, 70, 101, 17))
        self.rbustank_2.setObjectName("rbustank_2")
        self.rbustank_3 = QtWidgets.QRadioButton(self.frame)
        self.rbustank_3.setGeometry(QtCore.QRect(20, 100, 101, 17))
        self.rbustank_3.setObjectName("rbustank_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 194, 47, 13))
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(170, 10, 141, 221))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.label_5.setObjectName("label_5")
        self.pbsvmove = QtWidgets.QPushButton(self.frame_2)
        self.pbsvmove.setGeometry(QtCore.QRect(30, 190, 61, 23))
        self.pbsvmove.setCheckable(False)
        self.pbsvmove.setChecked(False)
        self.pbsvmove.setAutoDefault(True)
        self.pbsvmove.setDefault(False)
        self.pbsvmove.setFlat(False)
        self.pbsvmove.setObjectName("pbsvmove")
        self.lesvposition = QtWidgets.QLineEdit(self.frame_2)
        self.lesvposition.setGeometry(QtCore.QRect(60, 160, 41, 20))
        self.lesvposition.setObjectName("lesvposition")
        self.lblusoperate_3 = QtWidgets.QLabel(self.frame_2)
        self.lblusoperate_3.setGeometry(QtCore.QRect(100, 130, 21, 21))
        self.lblusoperate_3.setText("")
        self.lblusoperate_3.setObjectName("lblusoperate_3")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 164, 47, 13))
        self.label_6.setObjectName("label_6")
        self.rsservovalve_1 = QtWidgets.QRadioButton(self.frame_2)
        self.rsservovalve_1.setGeometry(QtCore.QRect(20, 30, 82, 17))
        self.rsservovalve_1.setObjectName("rsservovalve_1")
        self.rsservovalve_2 = QtWidgets.QRadioButton(self.frame_2)
        self.rsservovalve_2.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.rsservovalve_2.setObjectName("rsservovalve_2")
        self.rsservovalve_3 = QtWidgets.QRadioButton(self.frame_2)
        self.rsservovalve_3.setGeometry(QtCore.QRect(20, 70, 82, 17))
        self.rsservovalve_3.setObjectName("rsservovalve_3")
        self.rsservovalve_4 = QtWidgets.QRadioButton(self.frame_2)
        self.rsservovalve_4.setGeometry(QtCore.QRect(20, 90, 82, 17))
        self.rsservovalve_4.setObjectName("rsservovalve_4")
        self.rsservovalve_5 = QtWidgets.QRadioButton(self.frame_2)
        self.rsservovalve_5.setGeometry(QtCore.QRect(20, 110, 82, 17))
        self.rsservovalve_5.setObjectName("rsservovalve_5")
        self.rsservovalve_6 = QtWidgets.QRadioButton(self.frame_2)
        self.rsservovalve_6.setGeometry(QtCore.QRect(20, 130, 82, 17))
        self.rsservovalve_6.setObjectName("rsservovalve_6")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(320, 10, 171, 221))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.lesoil_1 = QtWidgets.QLineEdit(self.frame_3)
        self.lesoil_1.setGeometry(QtCore.QRect(30, 40, 41, 20))
        self.lesoil_1.setObjectName("lesoil_1")
        self.lesoil_3 = QtWidgets.QLineEdit(self.frame_3)
        self.lesoil_3.setGeometry(QtCore.QRect(30, 70, 41, 20))
        self.lesoil_3.setObjectName("lesoil_3")
        self.lesoil_5 = QtWidgets.QLineEdit(self.frame_3)
        self.lesoil_5.setGeometry(QtCore.QRect(30, 100, 41, 20))
        self.lesoil_5.setObjectName("lesoil_5")
        self.lesoil_6 = QtWidgets.QLineEdit(self.frame_3)
        self.lesoil_6.setGeometry(QtCore.QRect(110, 100, 41, 20))
        self.lesoil_6.setObjectName("lesoil_6")
        self.lesoil_7 = QtWidgets.QLineEdit(self.frame_3)
        self.lesoil_7.setGeometry(QtCore.QRect(30, 130, 41, 20))
        self.lesoil_7.setObjectName("lesoil_7")
        self.lesoil_8 = QtWidgets.QLineEdit(self.frame_3)
        self.lesoil_8.setGeometry(QtCore.QRect(110, 130, 41, 20))
        self.lesoil_8.setObjectName("lesoil_8")
        self.lesoil_4 = QtWidgets.QLineEdit(self.frame_3)
        self.lesoil_4.setGeometry(QtCore.QRect(110, 70, 41, 20))
        self.lesoil_4.setObjectName("lesoil_4")
        self.lesoil_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lesoil_2.setGeometry(QtCore.QRect(110, 40, 41, 20))
        self.lesoil_2.setObjectName("lesoil_2")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(50, 10, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(90, 40, 16, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(10, 70, 16, 16))
        self.label_10.setObjectName("label_10")
        self.pbsoilread = QtWidgets.QPushButton(self.frame_3)
        self.pbsoilread.setGeometry(QtCore.QRect(40, 180, 75, 23))
        self.pbsoilread.setObjectName("pbsoilread")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(90, 70, 16, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(10, 100, 16, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(90, 102, 16, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(10, 132, 16, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(90, 132, 16, 16))
        self.label_15.setObjectName("label_15")
        self.lblsoiloperate = QtWidgets.QLabel(self.frame_3)
        self.lblsoiloperate.setGeometry(QtCore.QRect(130, 180, 21, 21))
        self.lblsoiloperate.setText("")
        self.lblsoiloperate.setObjectName("lblsoiloperate")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.te_ports = QtWidgets.QTextEdit(self.tab)
        self.te_ports.setGeometry(QtCore.QRect(10, 30, 301, 161))
        self.te_ports.setObjectName("te_ports")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 47, 13))
        self.label_7.setObjectName("label_7")
        self.pb_rescan_ports = QtWidgets.QPushButton(self.tab)
        self.pb_rescan_ports.setGeometry(QtCore.QRect(10, 200, 75, 23))
        self.pb_rescan_ports.setObjectName("pb_rescan_ports")
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setGeometry(QtCore.QRect(340, 30, 120, 111))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 91, 16))
        self.label_8.setObjectName("label_8")
        self.le_ss_port = QtWidgets.QLineEdit(self.frame_4)
        self.le_ss_port.setGeometry(QtCore.QRect(20, 40, 61, 20))
        self.le_ss_port.setObjectName("le_ss_port")
        self.pb_ss_update = QtWidgets.QPushButton(self.frame_4)
        self.pb_ss_update.setGeometry(QtCore.QRect(20, 70, 75, 23))
        self.pb_ss_update.setObjectName("pb_ss_update")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 251, 231))
        self.groupBox.setObjectName("groupBox")
        self.le_kd_1 = QtWidgets.QLineEdit(self.groupBox)
        self.le_kd_1.setGeometry(QtCore.QRect(50, 90, 51, 20))
        self.le_kd_1.setObjectName("le_kd_1")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(20, 60, 31, 21))
        self.label_17.setObjectName("label_17")
        self.le_kp_1 = QtWidgets.QLineEdit(self.groupBox)
        self.le_kp_1.setGeometry(QtCore.QRect(50, 30, 51, 20))
        self.le_kp_1.setObjectName("le_kp_1")
        self.le_ki_1 = QtWidgets.QLineEdit(self.groupBox)
        self.le_ki_1.setGeometry(QtCore.QRect(50, 60, 51, 20))
        self.le_ki_1.setObjectName("le_ki_1")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(20, 90, 31, 21))
        self.label_18.setObjectName("label_18")
        self.pb_reset_fan_1 = QtWidgets.QPushButton(self.groupBox)
        self.pb_reset_fan_1.setGeometry(QtCore.QRect(20, 160, 61, 23))
        self.pb_reset_fan_1.setObjectName("pb_reset_fan_1")
        self.pb_save_fans_1 = QtWidgets.QPushButton(self.groupBox)
        self.pb_save_fans_1.setGeometry(QtCore.QRect(20, 190, 61, 23))
        self.pb_save_fans_1.setObjectName("pb_save_fans_1")
        self.ck_test = QtWidgets.QCheckBox(self.groupBox)
        self.ck_test.setGeometry(QtCore.QRect(170, 200, 61, 21))
        self.ck_test.setObjectName("ck_test")
        self.pb_show_log_1 = QtWidgets.QPushButton(self.groupBox)
        self.pb_show_log_1.setGeometry(QtCore.QRect(160, 160, 75, 31))
        self.pb_show_log_1.setObjectName("pb_show_log_1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 10, 251, 231))
        self.groupBox_2.setObjectName("groupBox_2")
        self.le_kd_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_kd_2.setGeometry(QtCore.QRect(50, 90, 51, 20))
        self.le_kd_2.setObjectName("le_kd_2")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(20, 60, 31, 21))
        self.label_20.setObjectName("label_20")
        self.le_kp_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_kp_2.setGeometry(QtCore.QRect(50, 30, 51, 20))
        self.le_kp_2.setObjectName("le_kp_2")
        self.le_ki_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_ki_2.setGeometry(QtCore.QRect(50, 60, 51, 20))
        self.le_ki_2.setObjectName("le_ki_2")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(20, 90, 31, 21))
        self.label_21.setObjectName("label_21")
        self.pb_reset_fan_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_reset_fan_2.setGeometry(QtCore.QRect(20, 160, 61, 23))
        self.pb_reset_fan_2.setObjectName("pb_reset_fan_2")
        self.pb_save_fans_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_save_fans_2.setGeometry(QtCore.QRect(20, 190, 61, 23))
        self.pb_save_fans_2.setObjectName("pb_save_fans_2")
        self.ck_test_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.ck_test_2.setGeometry(QtCore.QRect(170, 200, 61, 21))
        self.ck_test_2.setObjectName("ck_test_2")
        self.pb_show_log_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_show_log_2.setGeometry(QtCore.QRect(160, 160, 75, 31))
        self.pb_show_log_2.setObjectName("pb_show_log_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.pb_close = QtWidgets.QPushButton(DialogSettings)
        self.pb_close.setGeometry(QtCore.QRect(470, 290, 75, 23))
        self.pb_close.setObjectName("pb_close")

        self.retranslateUi(DialogSettings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogSettings)

    def retranslateUi(self, DialogSettings):
        _translate = QtCore.QCoreApplication.translate
        DialogSettings.setWindowTitle(_translate("DialogSettings", "Settings"))
        self.groupBox_3.setTitle(_translate("DialogSettings", "Database"))
        self.label_22.setText(_translate("DialogSettings", "Host"))
        self.pb_db_open.setText(_translate("DialogSettings", "Save"))
        self.label_23.setText(_translate("DialogSettings", "Password"))
        self.label_24.setText(_translate("DialogSettings", "DB Name"))
        self.label_25.setText(_translate("DialogSettings", "User Name"))
        self.pb_back_up.setText(_translate("DialogSettings", "Back Up"))
        self.label_26.setText(_translate("DialogSettings", "Operation Mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.system), _translate("DialogSettings", "System"))
        self.label.setText(_translate("DialogSettings", "Tank Volume Sensors"))
        self.pbusoperate.setText(_translate("DialogSettings", "Read"))
        self.rbustank_1.setText(_translate("DialogSettings", "Water Tank 1"))
        self.rbustank_2.setText(_translate("DialogSettings", "Water Tank 2"))
        self.rbustank_3.setText(_translate("DialogSettings", "Feed Mix Tank"))
        self.label_2.setText(_translate("DialogSettings", "Litres"))
        self.label_5.setText(_translate("DialogSettings", "Servo Valves"))
        self.pbsvmove.setText(_translate("DialogSettings", "Move"))
        self.label_6.setText(_translate("DialogSettings", "Position"))
        self.rsservovalve_1.setText(_translate("DialogSettings", "Tank 1"))
        self.rsservovalve_2.setText(_translate("DialogSettings", "Tank 2"))
        self.rsservovalve_3.setText(_translate("DialogSettings", "Feed 1"))
        self.rsservovalve_4.setText(_translate("DialogSettings", "Feed 2"))
        self.rsservovalve_5.setText(_translate("DialogSettings", "Drain 1"))
        self.rsservovalve_6.setText(_translate("DialogSettings", "Drain 2"))
        self.label_3.setText(_translate("DialogSettings", "Soil Senors"))
        self.label_4.setText(_translate("DialogSettings", "1"))
        self.label_9.setText(_translate("DialogSettings", "2"))
        self.label_10.setText(_translate("DialogSettings", "3"))
        self.pbsoilread.setText(_translate("DialogSettings", "Read"))
        self.label_11.setText(_translate("DialogSettings", "4"))
        self.label_12.setText(_translate("DialogSettings", "5"))
        self.label_13.setText(_translate("DialogSettings", "6"))
        self.label_14.setText(_translate("DialogSettings", "7"))
        self.label_15.setText(_translate("DialogSettings", "8"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DialogSettings", "Hardware Test"))
        self.label_7.setText(_translate("DialogSettings", "Ports"))
        self.pb_rescan_ports.setText(_translate("DialogSettings", "Rescan"))
        self.label_8.setText(_translate("DialogSettings", "SS Unit Port"))
        self.pb_ss_update.setText(_translate("DialogSettings", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DialogSettings", "Com Ports"))
        self.groupBox.setTitle(_translate("DialogSettings", "Fan 1"))
        self.label_16.setText(_translate("DialogSettings", "Kp"))
        self.label_17.setText(_translate("DialogSettings", "Ki"))
        self.label_18.setText(_translate("DialogSettings", "Kd"))
        self.pb_reset_fan_1.setText(_translate("DialogSettings", "Reset"))
        self.pb_save_fans_1.setText(_translate("DialogSettings", "Save"))
        self.ck_test.setText(_translate("DialogSettings", "Log"))
        self.pb_show_log_1.setText(_translate("DialogSettings", "Show Log"))
        self.groupBox_2.setTitle(_translate("DialogSettings", "Fan 2"))
        self.label_19.setText(_translate("DialogSettings", "Kp"))
        self.label_20.setText(_translate("DialogSettings", "Ki"))
        self.label_21.setText(_translate("DialogSettings", "Kd"))
        self.pb_reset_fan_2.setText(_translate("DialogSettings", "Reset"))
        self.pb_save_fans_2.setText(_translate("DialogSettings", "Save"))
        self.ck_test_2.setText(_translate("DialogSettings", "Log"))
        self.pb_show_log_2.setText(_translate("DialogSettings", "Show Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DialogSettings", "Fans"))
        self.pb_close.setText(_translate("DialogSettings", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogSettings = QtWidgets.QDialog()
    ui = Ui_DialogSettings()
    ui.setupUi(DialogSettings)
    DialogSettings.show()
    sys.exit(app.exec_())

