# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogProcessManager.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogProcessManager(object):
    def setupUi(self, dialogProcessManager):
        dialogProcessManager.setObjectName("dialogProcessManager")
        dialogProcessManager.resize(400, 533)
        font = QtGui.QFont()
        font.setPointSize(11)
        dialogProcessManager.setFont(font)
        self.cb_process = QtWidgets.QComboBox(dialogProcessManager)
        self.cb_process.setGeometry(QtCore.QRect(80, 20, 61, 22))
        self.cb_process.setObjectName("cb_process")
        self.label_12 = QtWidgets.QLabel(dialogProcessManager)
        self.label_12.setGeometry(QtCore.QRect(10, 16, 61, 31))
        self.label_12.setObjectName("label_12")
        self.cb_strain_1 = QtWidgets.QComboBox(dialogProcessManager)
        self.cb_strain_1.setGeometry(QtCore.QRect(80, 60, 261, 22))
        self.cb_strain_1.setObjectName("cb_strain_1")
        self.cb_strain_2 = QtWidgets.QComboBox(dialogProcessManager)
        self.cb_strain_2.setGeometry(QtCore.QRect(80, 90, 261, 22))
        self.cb_strain_2.setObjectName("cb_strain_2")
        self.cb_strain_3 = QtWidgets.QComboBox(dialogProcessManager)
        self.cb_strain_3.setGeometry(QtCore.QRect(80, 120, 261, 22))
        self.cb_strain_3.setObjectName("cb_strain_3")
        self.cb_strain_4 = QtWidgets.QComboBox(dialogProcessManager)
        self.cb_strain_4.setGeometry(QtCore.QRect(80, 150, 261, 22))
        self.cb_strain_4.setObjectName("cb_strain_4")
        self.cb_strain_5 = QtWidgets.QComboBox(dialogProcessManager)
        self.cb_strain_5.setGeometry(QtCore.QRect(80, 180, 261, 22))
        self.cb_strain_5.setObjectName("cb_strain_5")
        self.cb_strain_6 = QtWidgets.QComboBox(dialogProcessManager)
        self.cb_strain_6.setGeometry(QtCore.QRect(80, 210, 261, 22))
        self.cb_strain_6.setObjectName("cb_strain_6")
        self.cb_strain_7 = QtWidgets.QComboBox(dialogProcessManager)
        self.cb_strain_7.setGeometry(QtCore.QRect(80, 240, 261, 22))
        self.cb_strain_7.setObjectName("cb_strain_7")
        self.cb_strain_8 = QtWidgets.QComboBox(dialogProcessManager)
        self.cb_strain_8.setGeometry(QtCore.QRect(80, 270, 261, 22))
        self.cb_strain_8.setObjectName("cb_strain_8")
        self.label_2 = QtWidgets.QLabel(dialogProcessManager)
        self.label_2.setGeometry(QtCore.QRect(40, 309, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(dialogProcessManager)
        self.label.setGeometry(QtCore.QRect(40, 420, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.le_dur = QtWidgets.QLineEdit(dialogProcessManager)
        self.le_dur.setGeometry(QtCore.QRect(270, 310, 61, 20))
        self.le_dur.setReadOnly(True)
        self.le_dur.setObjectName("le_dur")
        self.pb_find = QtWidgets.QPushButton(dialogProcessManager)
        self.pb_find.setGeometry(QtCore.QRect(250, 420, 75, 23))
        self.pb_find.setObjectName("pb_find")
        self.de_start = QtWidgets.QDateEdit(dialogProcessManager)
        self.de_start.setGeometry(QtCore.QRect(120, 420, 110, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.de_start.setFont(font)
        self.de_start.setCalendarPopup(True)
        self.de_start.setObjectName("de_start")
        self.le_end_date = QtWidgets.QLineEdit(dialogProcessManager)
        self.le_end_date.setEnabled(True)
        self.le_end_date.setGeometry(QtCore.QRect(120, 460, 113, 20))
        self.le_end_date.setReadOnly(True)
        self.le_end_date.setObjectName("le_end_date")
        self.pb_end = QtWidgets.QPushButton(dialogProcessManager)
        self.pb_end.setGeometry(QtCore.QRect(110, 490, 75, 23))
        self.pb_end.setObjectName("pb_end")
        self.label_3 = QtWidgets.QLabel(dialogProcessManager)
        self.label_3.setGeometry(QtCore.QRect(40, 460, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pb_start = QtWidgets.QPushButton(dialogProcessManager)
        self.pb_start.setGeometry(QtCore.QRect(20, 490, 75, 23))
        self.pb_start.setObjectName("pb_start")
        self.cb_patterns = QtWidgets.QComboBox(dialogProcessManager)
        self.cb_patterns.setGeometry(QtCore.QRect(110, 309, 151, 22))
        self.cb_patterns.setObjectName("cb_patterns")
        self.le_end_date_2 = QtWidgets.QLineEdit(dialogProcessManager)
        self.le_end_date_2.setEnabled(True)
        self.le_end_date_2.setGeometry(QtCore.QRect(240, 460, 113, 20))
        self.le_end_date_2.setReadOnly(True)
        self.le_end_date_2.setObjectName("le_end_date_2")
        self.pb_save = QtWidgets.QPushButton(dialogProcessManager)
        self.pb_save.setGeometry(QtCore.QRect(200, 490, 75, 23))
        self.pb_save.setObjectName("pb_save")
        self.pb_close = QtWidgets.QPushButton(dialogProcessManager)
        self.pb_close.setGeometry(QtCore.QRect(310, 490, 75, 23))
        self.pb_close.setObjectName("pb_close")
        self.frm_auto_cal = QtWidgets.QFrame(dialogProcessManager)
        self.frm_auto_cal.setGeometry(QtCore.QRect(20, 340, 361, 61))
        self.frm_auto_cal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_auto_cal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_auto_cal.setObjectName("frm_auto_cal")
        self.lbl_auto_cal_2 = QtWidgets.QLabel(self.frm_auto_cal)
        self.lbl_auto_cal_2.setGeometry(QtCore.QRect(150, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_auto_cal_2.setFont(font)
        self.lbl_auto_cal_2.setObjectName("lbl_auto_cal_2")
        self.lbl_auto_cal = QtWidgets.QLabel(self.frm_auto_cal)
        self.lbl_auto_cal.setGeometry(QtCore.QRect(10, 0, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_auto_cal.setFont(font)
        self.lbl_auto_cal.setObjectName("lbl_auto_cal")
        self.le_total = QtWidgets.QLineEdit(self.frm_auto_cal)
        self.le_total.setGeometry(QtCore.QRect(200, 31, 61, 20))
        self.le_total.setReadOnly(True)
        self.le_total.setObjectName("le_total")
        self.le_longest = QtWidgets.QLineEdit(self.frm_auto_cal)
        self.le_longest.setGeometry(QtCore.QRect(200, 3, 61, 20))
        self.le_longest.setReadOnly(True)
        self.le_longest.setObjectName("le_longest")
        self.le_shortest = QtWidgets.QLineEdit(self.frm_auto_cal)
        self.le_shortest.setGeometry(QtCore.QRect(280, 4, 61, 20))
        self.le_shortest.setReadOnly(True)
        self.le_shortest.setObjectName("le_shortest")
        self.label_13 = QtWidgets.QLabel(dialogProcessManager)
        self.label_13.setGeometry(QtCore.QRect(190, 10, 61, 31))
        self.label_13.setObjectName("label_13")
        self.le_qty = QtWidgets.QLineEdit(dialogProcessManager)
        self.le_qty.setGeometry(QtCore.QRect(260, 20, 61, 20))
        self.le_qty.setReadOnly(False)
        self.le_qty.setObjectName("le_qty")

        self.retranslateUi(dialogProcessManager)
        QtCore.QMetaObject.connectSlotsByName(dialogProcessManager)

    def retranslateUi(self, dialogProcessManager):
        _translate = QtCore.QCoreApplication.translate
        dialogProcessManager.setWindowTitle(_translate("dialogProcessManager", "Process Manager"))
        self.label_12.setText(_translate("dialogProcessManager", "Process"))
        self.label_2.setText(_translate("dialogProcessManager", "Pattern"))
        self.label.setText(_translate("dialogProcessManager", "Start Date"))
        self.pb_find.setText(_translate("dialogProcessManager", "Find"))
        self.pb_end.setText(_translate("dialogProcessManager", "End"))
        self.label_3.setText(_translate("dialogProcessManager", "End Date"))
        self.pb_start.setText(_translate("dialogProcessManager", "Start"))
        self.pb_save.setText(_translate("dialogProcessManager", "Save"))
        self.pb_close.setText(_translate("dialogProcessManager", "Close"))
        self.lbl_auto_cal_2.setText(_translate("dialogProcessManager", "Total"))
        self.lbl_auto_cal.setText(_translate("dialogProcessManager", "Auto Cal - Longest Finishing"))
        self.label_13.setText(_translate("dialogProcessManager", "Quantity"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialogProcessManager = QtWidgets.QWidget()
    ui = Ui_dialogProcessManager()
    ui.setupUi(dialogProcessManager)
    dialogProcessManager.show()
    sys.exit(app.exec_())

