# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogDispatchReports.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogDispatchReport(object):
    def setupUi(self, DialogDispatchReport):
        DialogDispatchReport.setObjectName("DialogDispatchReport")
        DialogDispatchReport.resize(1075, 656)
        font = QtGui.QFont()
        font.setPointSize(11)
        DialogDispatchReport.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(DialogDispatchReport)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(DialogDispatchReport)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(9, 41, 271, 523))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(529, 41, 513, 523))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(529, 9, 82, 26))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pb_refresh = QtWidgets.QPushButton(self.tab_2)
        self.pb_refresh.setObjectName("pb_refresh")
        self.gridLayout_2.addWidget(self.pb_refresh, 0, 2, 1, 1)
        self.te_weeks_summary = QtWidgets.QTextEdit(self.tab_2)
        self.te_weeks_summary.setMaximumSize(QtCore.QSize(300, 16777215))
        self.te_weeks_summary.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.te_weeks_summary.setObjectName("te_weeks_summary")
        self.gridLayout_2.addWidget(self.te_weeks_summary, 1, 0, 2, 1)
        self.te_weeks_summary_2 = QtWidgets.QTextEdit(self.tab_2)
        self.te_weeks_summary_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.te_weeks_summary_2.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.te_weeks_summary_2.setObjectName("te_weeks_summary_2")
        self.gridLayout_2.addWidget(self.te_weeks_summary_2, 1, 1, 2, 1)
        self.te_weeks_summary_3 = QtWidgets.QTextEdit(self.tab_2)
        self.te_weeks_summary_3.setMinimumSize(QtCore.QSize(490, 0))
        self.te_weeks_summary_3.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.te_weeks_summary_3.setObjectName("te_weeks_summary_3")
        self.gridLayout_2.addWidget(self.te_weeks_summary_3, 1, 2, 1, 1)
        self.wg_graph_1 = QtWidgets.QWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wg_graph_1.sizePolicy().hasHeightForWidth())
        self.wg_graph_1.setSizePolicy(sizePolicy)
        self.wg_graph_1.setObjectName("wg_graph_1")
        self.gridLayout_2.addWidget(self.wg_graph_1, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.wg_graph_4 = QtWidgets.QWidget(self.tab_4)
        self.wg_graph_4.setGeometry(QtCore.QRect(10, 10, 1031, 461))
        self.wg_graph_4.setObjectName("wg_graph_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.cb_client = QtWidgets.QComboBox(self.tab_3)
        self.cb_client.setGeometry(QtCore.QRect(60, 20, 69, 22))
        self.cb_client.setObjectName("cb_client")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(20, 23, 41, 20))
        self.label.setObjectName("label")
        self.cb_jar = QtWidgets.QComboBox(self.tab_3)
        self.cb_jar.setGeometry(QtCore.QRect(180, 20, 69, 22))
        self.cb_jar.setObjectName("cb_jar")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(150, 20, 41, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(380, 20, 41, 20))
        self.label_3.setObjectName("label_3")
        self.cb_strain = QtWidgets.QComboBox(self.tab_3)
        self.cb_strain.setGeometry(QtCore.QRect(420, 20, 69, 22))
        self.cb_strain.setObjectName("cb_strain")
        self.de_start = QtWidgets.QDateEdit(self.tab_3)
        self.de_start.setGeometry(QtCore.QRect(560, 20, 110, 22))
        self.de_start.setCalendarPopup(True)
        self.de_start.setObjectName("de_start")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(510, 20, 41, 20))
        self.label_4.setObjectName("label_4")
        self.de_end = QtWidgets.QDateEdit(self.tab_3)
        self.de_end.setGeometry(QtCore.QRect(750, 20, 110, 22))
        self.de_end.setCalendarPopup(True)
        self.de_end.setObjectName("de_end")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(700, 20, 41, 20))
        self.label_5.setObjectName("label_5")
        self.te_search = QtWidgets.QTextEdit(self.tab_3)
        self.te_search.setGeometry(QtCore.QRect(10, 60, 351, 491))
        self.te_search.setObjectName("te_search")
        self.wg_plot_search = QtWidgets.QWidget(self.tab_3)
        self.wg_plot_search.setGeometry(QtCore.QRect(380, 60, 571, 371))
        self.wg_plot_search.setObjectName("wg_plot_search")
        self.pb_search = QtWidgets.QPushButton(self.tab_3)
        self.pb_search.setGeometry(QtCore.QRect(870, 20, 75, 23))
        self.pb_search.setObjectName("pb_search")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(260, 20, 41, 20))
        self.label_6.setObjectName("label_6")
        self.cb_type = QtWidgets.QComboBox(self.tab_3)
        self.cb_type.setGeometry(QtCore.QRect(300, 20, 69, 22))
        self.cb_type.setObjectName("cb_type")
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pb_close = QtWidgets.QPushButton(DialogDispatchReport)
        self.pb_close.setObjectName("pb_close")
        self.horizontalLayout.addWidget(self.pb_close)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(DialogDispatchReport)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogDispatchReport)

    def retranslateUi(self, DialogDispatchReport):
        _translate = QtCore.QCoreApplication.translate
        DialogDispatchReport.setWindowTitle(_translate("DialogDispatchReport", "Dispatch Reports"))
        self.pushButton.setText(_translate("DialogDispatchReport", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DialogDispatchReport", "Tab 1"))
        self.pb_refresh.setText(_translate("DialogDispatchReport", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DialogDispatchReport", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("DialogDispatchReport", "Page"))
        self.label.setText(_translate("DialogDispatchReport", "Client"))
        self.label_2.setText(_translate("DialogDispatchReport", "Jar"))
        self.label_3.setText(_translate("DialogDispatchReport", "Strain"))
        self.label_4.setText(_translate("DialogDispatchReport", "From"))
        self.label_5.setText(_translate("DialogDispatchReport", "To"))
        self.pb_search.setText(_translate("DialogDispatchReport", "Search"))
        self.label_6.setText(_translate("DialogDispatchReport", "Type"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DialogDispatchReport", "Search"))
        self.pb_close.setText(_translate("DialogDispatchReport", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogDispatchReport = QtWidgets.QDialog()
    ui = Ui_DialogDispatchReport()
    ui.setupUi(DialogDispatchReport)
    DialogDispatchReport.show()
    sys.exit(app.exec_())

