# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogSoilSensors.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogSoilSensors(object):
    def setupUi(self, DialogSoilSensors):
        DialogSoilSensors.setObjectName("DialogSoilSensors")
        DialogSoilSensors.resize(256, 275)
        font = QtGui.QFont()
        font.setPointSize(11)
        DialogSoilSensors.setFont(font)
        self.lbl_name = QtWidgets.QLabel(DialogSoilSensors)
        self.lbl_name.setGeometry(QtCore.QRect(20, 10, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name.setFont(font)
        self.lbl_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_name.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_name.setObjectName("lbl_name")
        self.le_reading_1_3 = QtWidgets.QLineEdit(DialogSoilSensors)
        self.le_reading_1_3.setGeometry(QtCore.QRect(100, 140, 64, 24))
        self.le_reading_1_3.setReadOnly(True)
        self.le_reading_1_3.setObjectName("le_reading_1_3")
        self.label_12 = QtWidgets.QLabel(DialogSoilSensors)
        self.label_12.setGeometry(QtCore.QRect(30, 40, 64, 42))
        self.label_12.setObjectName("label_12")
        self.le_avg_1 = QtWidgets.QLineEdit(DialogSoilSensors)
        self.le_avg_1.setGeometry(QtCore.QRect(30, 80, 64, 24))
        self.le_avg_1.setReadOnly(True)
        self.le_avg_1.setObjectName("le_avg_1")
        self.label_3 = QtWidgets.QLabel(DialogSoilSensors)
        self.label_3.setGeometry(QtCore.QRect(16, 80, 8, 24))
        self.label_3.setObjectName("label_3")
        self.ck_active_1_1 = QtWidgets.QCheckBox(DialogSoilSensors)
        self.ck_active_1_1.setGeometry(QtCore.QRect(170, 81, 62, 22))
        self.ck_active_1_1.setObjectName("ck_active_1_1")
        self.le_reading_1_2 = QtWidgets.QLineEdit(DialogSoilSensors)
        self.le_reading_1_2.setGeometry(QtCore.QRect(100, 110, 64, 24))
        self.le_reading_1_2.setReadOnly(True)
        self.le_reading_1_2.setObjectName("le_reading_1_2")
        self.le_avg_4 = QtWidgets.QLineEdit(DialogSoilSensors)
        self.le_avg_4.setGeometry(QtCore.QRect(30, 170, 64, 24))
        self.le_avg_4.setObjectName("le_avg_4")
        self.ck_active_1_4 = QtWidgets.QCheckBox(DialogSoilSensors)
        self.ck_active_1_4.setGeometry(QtCore.QRect(170, 171, 62, 22))
        self.ck_active_1_4.setObjectName("ck_active_1_4")
        self.le_reading_1_4 = QtWidgets.QLineEdit(DialogSoilSensors)
        self.le_reading_1_4.setGeometry(QtCore.QRect(100, 170, 64, 24))
        self.le_reading_1_4.setReadOnly(True)
        self.le_reading_1_4.setObjectName("le_reading_1_4")
        self.le_avg_2 = QtWidgets.QLineEdit(DialogSoilSensors)
        self.le_avg_2.setGeometry(QtCore.QRect(30, 110, 64, 24))
        self.le_avg_2.setObjectName("le_avg_2")
        self.le_avg_3 = QtWidgets.QLineEdit(DialogSoilSensors)
        self.le_avg_3.setGeometry(QtCore.QRect(30, 140, 64, 24))
        self.le_avg_3.setObjectName("le_avg_3")
        self.label_5 = QtWidgets.QLabel(DialogSoilSensors)
        self.label_5.setGeometry(QtCore.QRect(16, 140, 8, 24))
        self.label_5.setObjectName("label_5")
        self.ck_active_1_2 = QtWidgets.QCheckBox(DialogSoilSensors)
        self.ck_active_1_2.setGeometry(QtCore.QRect(170, 111, 62, 22))
        self.ck_active_1_2.setObjectName("ck_active_1_2")
        self.label_4 = QtWidgets.QLabel(DialogSoilSensors)
        self.label_4.setGeometry(QtCore.QRect(16, 110, 8, 24))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(DialogSoilSensors)
        self.label_6.setGeometry(QtCore.QRect(16, 170, 8, 24))
        self.label_6.setObjectName("label_6")
        self.ck_active_1_3 = QtWidgets.QCheckBox(DialogSoilSensors)
        self.ck_active_1_3.setGeometry(QtCore.QRect(170, 141, 62, 22))
        self.ck_active_1_3.setObjectName("ck_active_1_3")
        self.le_avg_5 = QtWidgets.QLineEdit(DialogSoilSensors)
        self.le_avg_5.setGeometry(QtCore.QRect(30, 210, 64, 24))
        self.le_avg_5.setObjectName("le_avg_5")
        self.le_reading_1_1 = QtWidgets.QLineEdit(DialogSoilSensors)
        self.le_reading_1_1.setGeometry(QtCore.QRect(100, 80, 64, 24))
        self.le_reading_1_1.setReadOnly(True)
        self.le_reading_1_1.setObjectName("le_reading_1_1")
        self.ck_active_all = QtWidgets.QCheckBox(DialogSoilSensors)
        self.ck_active_all.setGeometry(QtCore.QRect(130, 46, 91, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ck_active_all.setFont(font)
        self.ck_active_all.setObjectName("ck_active_all")
        self.pb_close = QtWidgets.QPushButton(DialogSoilSensors)
        self.pb_close.setGeometry(QtCore.QRect(170, 240, 75, 23))
        self.pb_close.setObjectName("pb_close")
        self.pushButton = QtWidgets.QPushButton(DialogSoilSensors)
        self.pushButton.setGeometry(QtCore.QRect(120, 210, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(DialogSoilSensors)
        QtCore.QMetaObject.connectSlotsByName(DialogSoilSensors)

    def retranslateUi(self, DialogSoilSensors):
        _translate = QtCore.QCoreApplication.translate
        DialogSoilSensors.setWindowTitle(_translate("DialogSoilSensors", "Soil Sensors"))
        self.lbl_name.setText(_translate("DialogSoilSensors", "Soil Sensors"))
        self.label_12.setText(_translate("DialogSoilSensors", "Average"))
        self.label_3.setText(_translate("DialogSoilSensors", "1"))
        self.ck_active_1_1.setText(_translate("DialogSoilSensors", "Active"))
        self.ck_active_1_4.setText(_translate("DialogSoilSensors", "Active"))
        self.label_5.setText(_translate("DialogSoilSensors", "3"))
        self.ck_active_1_2.setText(_translate("DialogSoilSensors", "Active"))
        self.label_4.setText(_translate("DialogSoilSensors", "2"))
        self.label_6.setText(_translate("DialogSoilSensors", "4"))
        self.ck_active_1_3.setText(_translate("DialogSoilSensors", "Active"))
        self.ck_active_all.setText(_translate("DialogSoilSensors", "Area On"))
        self.pb_close.setText(_translate("DialogSoilSensors", "Close"))
        self.pushButton.setText(_translate("DialogSoilSensors", "Advanced"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogSoilSensors = QtWidgets.QWidget()
    ui = Ui_DialogSoilSensors()
    ui.setupUi(DialogSoilSensors)
    DialogSoilSensors.show()
    sys.exit(app.exec_())

