# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/py/dialogGraphEnviroment.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogGraphEnv(object):
    def setupUi(self, DialogGraphEnv):
        DialogGraphEnv.setObjectName("DialogGraphEnv")
        DialogGraphEnv.resize(1254, 581)
        font = QtGui.QFont()
        font.setPointSize(11)
        DialogGraphEnv.setFont(font)
        self.cb_logs = QtWidgets.QComboBox(DialogGraphEnv)
        self.cb_logs.setGeometry(QtCore.QRect(20, 40, 141, 22))
        self.cb_logs.setObjectName("cb_logs")
        self.pb_close = QtWidgets.QPushButton(DialogGraphEnv)
        self.pb_close.setGeometry(QtCore.QRect(1090, 20, 75, 23))
        self.pb_close.setObjectName("pb_close")
        self.wg_graph_1 = QtWidgets.QWidget(DialogGraphEnv)
        self.wg_graph_1.setGeometry(QtCore.QRect(10, 110, 1231, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wg_graph_1.sizePolicy().hasHeightForWidth())
        self.wg_graph_1.setSizePolicy(sizePolicy)
        self.wg_graph_1.setObjectName("wg_graph_1")
        self.pb_refresh = QtWidgets.QPushButton(DialogGraphEnv)
        self.pb_refresh.setGeometry(QtCore.QRect(970, 20, 75, 23))
        self.pb_refresh.setObjectName("pb_refresh")
        self.ck_live = QtWidgets.QCheckBox(DialogGraphEnv)
        self.ck_live.setGeometry(QtCore.QRect(20, 10, 70, 17))
        self.ck_live.setObjectName("ck_live")
        self.groupBox = QtWidgets.QGroupBox(DialogGraphEnv)
        self.groupBox.setGeometry(QtCore.QRect(180, 10, 120, 101))
        self.groupBox.setObjectName("groupBox")
        self.temp_1_3 = QtWidgets.QCheckBox(self.groupBox)
        self.temp_1_3.setGeometry(QtCore.QRect(10, 80, 111, 17))
        self.temp_1_3.setObjectName("temp_1_3")
        self.temp_1_1 = QtWidgets.QCheckBox(self.groupBox)
        self.temp_1_1.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.temp_1_1.setObjectName("temp_1_1")
        self.temp_1_2 = QtWidgets.QCheckBox(self.groupBox)
        self.temp_1_2.setGeometry(QtCore.QRect(10, 60, 111, 20))
        self.temp_1_2.setObjectName("temp_1_2")
        self.ck_hum_1 = QtWidgets.QCheckBox(self.groupBox)
        self.ck_hum_1.setGeometry(QtCore.QRect(10, 20, 81, 19))
        self.ck_hum_1.setObjectName("ck_hum_1")
        self.groupBox_2 = QtWidgets.QGroupBox(DialogGraphEnv)
        self.groupBox_2.setGeometry(QtCore.QRect(310, 10, 120, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.temp_2_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.temp_2_3.setGeometry(QtCore.QRect(0, 80, 111, 17))
        self.temp_2_3.setObjectName("temp_2_3")
        self.temp_2_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.temp_2_2.setGeometry(QtCore.QRect(0, 60, 111, 20))
        self.temp_2_2.setObjectName("temp_2_2")
        self.temp_2_1 = QtWidgets.QCheckBox(self.groupBox_2)
        self.temp_2_1.setGeometry(QtCore.QRect(0, 40, 111, 17))
        self.temp_2_1.setObjectName("temp_2_1")
        self.ck_hum_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.ck_hum_2.setGeometry(QtCore.QRect(0, 20, 81, 19))
        self.ck_hum_2.setObjectName("ck_hum_2")
        self.groupBox_3 = QtWidgets.QGroupBox(DialogGraphEnv)
        self.groupBox_3.setGeometry(QtCore.QRect(440, 10, 120, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.temp_3_1 = QtWidgets.QCheckBox(self.groupBox_3)
        self.temp_3_1.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.temp_3_1.setObjectName("temp_3_1")
        self.ck_hum_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.ck_hum_3.setGeometry(QtCore.QRect(10, 20, 81, 19))
        self.ck_hum_3.setObjectName("ck_hum_3")
        self.groupBox_4 = QtWidgets.QGroupBox(DialogGraphEnv)
        self.groupBox_4.setGeometry(QtCore.QRect(570, 10, 120, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.temp_4_1 = QtWidgets.QCheckBox(self.groupBox_4)
        self.temp_4_1.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.temp_4_1.setObjectName("temp_4_1")
        self.groupBox_5 = QtWidgets.QGroupBox(DialogGraphEnv)
        self.groupBox_5.setGeometry(QtCore.QRect(700, 10, 120, 80))
        self.groupBox_5.setObjectName("groupBox_5")
        self.temp_5_1 = QtWidgets.QCheckBox(self.groupBox_5)
        self.temp_5_1.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.temp_5_1.setObjectName("temp_5_1")
        self.ck_hum_4 = QtWidgets.QCheckBox(self.groupBox_5)
        self.ck_hum_4.setGeometry(QtCore.QRect(10, 20, 81, 19))
        self.ck_hum_4.setObjectName("ck_hum_4")

        self.retranslateUi(DialogGraphEnv)
        QtCore.QMetaObject.connectSlotsByName(DialogGraphEnv)

    def retranslateUi(self, DialogGraphEnv):
        _translate = QtCore.QCoreApplication.translate
        DialogGraphEnv.setWindowTitle(_translate("DialogGraphEnv", "Enviroment Graph"))
        self.pb_close.setText(_translate("DialogGraphEnv", "Close"))
        self.pb_refresh.setText(_translate("DialogGraphEnv", "Refresh"))
        self.ck_live.setText(_translate("DialogGraphEnv", "Live"))
        self.groupBox.setTitle(_translate("DialogGraphEnv", "Area 1"))
        self.temp_1_3.setText(_translate("DialogGraphEnv", "Root"))
        self.temp_1_1.setText(_translate("DialogGraphEnv", "Temperature"))
        self.temp_1_2.setText(_translate("DialogGraphEnv", "Canopy"))
        self.ck_hum_1.setText(_translate("DialogGraphEnv", "Humidity"))
        self.groupBox_2.setTitle(_translate("DialogGraphEnv", "Area 2"))
        self.temp_2_3.setText(_translate("DialogGraphEnv", "Root"))
        self.temp_2_2.setText(_translate("DialogGraphEnv", "Canopy"))
        self.temp_2_1.setText(_translate("DialogGraphEnv", "Temperature"))
        self.ck_hum_2.setText(_translate("DialogGraphEnv", "Humidity"))
        self.groupBox_3.setTitle(_translate("DialogGraphEnv", "Drying"))
        self.temp_3_1.setText(_translate("DialogGraphEnv", "Temperature"))
        self.ck_hum_3.setText(_translate("DialogGraphEnv", "Humidity"))
        self.groupBox_4.setTitle(_translate("DialogGraphEnv", "Workshop"))
        self.temp_4_1.setText(_translate("DialogGraphEnv", "Temperature"))
        self.groupBox_5.setTitle(_translate("DialogGraphEnv", "Outside"))
        self.temp_5_1.setText(_translate("DialogGraphEnv", "Temperature"))
        self.ck_hum_4.setText(_translate("DialogGraphEnv", "Humidity"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogGraphEnv = QtWidgets.QWidget()
    ui = Ui_DialogGraphEnv()
    ui.setupUi(DialogGraphEnv)
    DialogGraphEnv.show()
    sys.exit(app.exec_())

